"""The Armenian alphabet. Sources:

- `<https://www.unicode.org/charts/PDF/U0530.pdf>`_

"""

__author__ = ["Caio Geraldes <caio.geraldes@usp.br>"]


UPPER = [
    "\u0531",  # Ա ARMENIAN CAPITAL LETTER AYB
    "\u0535",  # Ե ARMENIAN CAPITAL LETTER ECH
    "\u0537",  # Է ARMENIAN CAPITAL LETTER EH
    "\u0538",  # Ը ARMENIAN CAPITAL LETTER ET
    "\u053b",  # Ի ARMENIAN CAPITAL LETTER INI
    "\u0548",  # Ո ARMENIAN CAPITAL LETTER VO
    "\u0555",  # Օ ARMENIAN CAPITAL LETTER OH
]

LOWER = [
    "\u0561",  # ա ARMENIAN SMALL LETTER AYB
    "\u0565",  # ե ARMENIAN SMALL LETTER ECH
    "\u0567",  # է ARMENIAN SMALL LETTER EH
    "\u0568",  # ը ARMENIAN SMALL LETTER ET
    "\u056b",  # ի ARMENIAN SMALL LETTER INI
    "\u0578",  # ո ARMENIAN SMALL LETTER VO
    "\u0585",  # օ ARMENIAN SMALL LETTER OH
]

LOWER_LIGATURES = ["\u0587"]  # և ARMENIAN SMALL LIGATURE ECH YIWN

UPPER_SEMIVOWELS = [
    "\u0545",  # Յ ARMENIAN CAPITAL LETTER YI
    "\u0552",  # Ւ ARMENIAN CAPITAL LETTER YIWN
]

LOWER_SEMIVOWELS = [
    "\u0575",  # յ ARMENIAN SMALL LETTER YI
    "\u0582",  # ւ ARMENIAN SMALL LETTER YIWN
]

UPPER_CONSONANTS = [
    "\u0532",  # Բ ARMENIAN CAPITAL LETTER BEN
    "\u0533",  # Գ ARMENIAN CAPITAL LETTER GIM
    "\u0534",  # Դ ARMENIAN CAPITAL LETTER DA
    "\u0536",  # Զ ARMENIAN CAPITAL LETTER ZA
    "\u0539",  # Թ ARMENIAN CAPITAL LETTER TO
    "\u053a",  # Ժ ARMENIAN CAPITAL LETTER ZHE
    "\u053c",  # Լ ARMENIAN CAPITAL LETTER LIWN
    "\u053d",  # Խ ARMENIAN CAPITAL LETTER XEH
    "\u053e",  # Ծ ARMENIAN CAPITAL LETTER CA
    "\u053f",  # Կ ARMENIAN CAPITAL LETTER KEN
    "\u0540",  # Հ ARMENIAN CAPITAL LETTER HO
    "\u0541",  # Ձ ARMENIAN CAPITAL LETTER JA
    "\u0542",  # Ղ ARMENIAN CAPITAL LETTER GHAD
    "\u0543",  # Ճ ARMENIAN CAPITAL LETTER CHEH
    "\u0544",  # Մ ARMENIAN CAPITAL LETTER MEN
    "\u0546",  # Ն ARMENIAN CAPITAL LETTER NOW
    "\u0547",  # Շ ARMENIAN CAPITAL LETTER SHA
    "\u0549",  # Չ ARMENIAN CAPITAL LETTER CHA
    "\u054a",  # Պ ARMENIAN CAPITAL LETTER PEH
    "\u054b",  # Ջ ARMENIAN CAPITAL LETTER JHEH
    "\u054c",  # Ռ ARMENIAN CAPITAL LETTER RA
    "\u054d",  # Ս ARMENIAN CAPITAL LETTER SEH
    "\u054e",  # Վ ARMENIAN CAPITAL LETTER VEW
    "\u054f",  # Տ ARMENIAN CAPITAL LETTER TIWN
    "\u0550",  # Ր ARMENIAN CAPITAL LETTER REH
    "\u0551",  # Ց ARMENIAN CAPITAL LETTER CO
    "\u0553",  # Փ ARMENIAN CAPITAL LETTER PIWR
    "\u0554",  # Ք ARMENIAN CAPITAL LETTER KEH
    "\u0555",  # Օ ARMENIAN CAPITAL LETTER OH
    "\u0556",  # Ֆ ARMENIAN CAPITAL LETTER FEH
]


LOWER_CONSONANTS = [
    "\u0562",  # բ ARMENIAN SMALL LETTER BEN
    "\u0563",  # գ ARMENIAN SMALL LETTER GIM
    "\u0564",  # դ ARMENIAN SMALL LETTER DA
    "\u0566",  # զ ARMENIAN SMALL LETTER ZA
    "\u0569",  # թ ARMENIAN SMALL LETTER TO
    "\u056a",  # ժ ARMENIAN SMALL LETTER ZHE
    "\u056c",  # լ ARMENIAN SMALL LETTER LIWN
    "\u056d",  # խ ARMENIAN SMALL LETTER XEH
    "\u056e",  # ծ ARMENIAN SMALL LETTER CA
    "\u056f",  # կ ARMENIAN SMALL LETTER KEN
    "\u0570",  # հ ARMENIAN SMALL LETTER HO
    "\u0571",  # ձ ARMENIAN SMALL LETTER JA
    "\u0572",  # ղ ARMENIAN SMALL LETTER GHAD
    "\u0573",  # ճ ARMENIAN SMALL LETTER CHEH
    "\u0574",  # մ ARMENIAN SMALL LETTER MEN
    "\u0576",  # ն ARMENIAN SMALL LETTER NOW
    "\u0577",  # շ ARMENIAN SMALL LETTER SHA
    "\u0579",  # չ ARMENIAN SMALL LETTER CHA
    "\u057a",  # պ ARMENIAN SMALL LETTER PEH
    "\u057b",  # ջ ARMENIAN SMALL LETTER JHEH
    "\u057c",  # ռ ARMENIAN SMALL LETTER RA
    "\u057d",  # ս ARMENIAN SMALL LETTER SEH
    "\u057e",  # վ ARMENIAN SMALL LETTER VEW
    "\u057f",  # տ ARMENIAN SMALL LETTER TIWN
    "\u0580",  # ր ARMENIAN SMALL LETTER REH
    "\u0581",  # ց ARMENIAN SMALL LETTER CO
    "\u0583",  # փ ARMENIAN SMALL LETTER PIWR
    "\u0584",  # ք ARMENIAN SMALL LETTER KEH
    "\u0586",  # ֆ ARMENIAN SMALL LETTER FEH
]

PUNCTUATION = [
    "\u0589",  # ։ ARMENIAN FULL STOP
    "\u058a",  # ֊ ARMENIAN HYPHEN = yentamna
    "\u055b",  # ՛ ARMENIAN EMPHASIS MARK = shesht
    "\u055c",  # ՜ ARMENIAN EXCLAMATION MARK = batsaganchakan nshan
    "\u055d",  # ՝ ARMENIAN COMMA = bowt
    "\u055e",  # ՞ ARMENIAN QUESTION MARK = hartsakan nshan
    "\u055f",  # ՟ ARMENIAN ABBREVIATION MARK = patiw
]
