entities = [("Abel", "REL"),
("Abilant", "LOC"),
("Abirun", "CHI"),
("Abisme", "CHI"),
("Abraham", "REL"),
("Absalon", "REL"),
("Acelin", "CHI"),
("Acenssion", "FEST"),
("Achilles", "CLAS"),
("Acre", "LOC"),
("Adam", "REL"),
("Adan", "REL"),
("Aelroth", "CHI"),
("Affrike", "LOC"),
("Agaba", "REL"),
("Agamennon", "CLAS"),
("aignelet", "VIL"),
("Aimer", "CHI"),
("Aimeri", "CHI"),
("Ais", "LOC"),
("Albanie", "LOC"),
("Alde", "CHI"),
("Alemaigne", "LOC"),
("Alemans", "NAT"),
("Aleverne", "LOC"),
("Alexandre", "CLAS"),
("Alexandrie", "LOC"),
("Alexandrin", "CLAS"),
("Alexandrine", "LOC"),
("Alexis", "REL"),
("Alixandre", "CLAS"),
("Almace", "S"),
("Almaris", "CHI"),
("Alphaïen", "CHI"),
("Alsis", "LOC"),
("Alverne", "LOC"),
("Amborres d’Oluferne", "CHI"),
("Ambure", "CHI"),
("Ameri", "CHI"),
("Amiens", "LOC"),
("Amiral", "CHI"),
("Andret", "CHI"),
("Andrez", "CHI"),
("Angers", "LOC"),
("Angevin", "NAT"),
("Anglois", "NAT"),
("Anjou", "LOC"),
("Anseïs", "CHI"),
("Antelme de Maience", "CHI"),
("Antigone", "CLAS"),
("Antioche", "LOC"),
("Apolin", "CLAS"),
("Apollin", "CLAS"),
("Apoloine", "CLAS"),
("Arabe", "NAT"),
("Arabie", "LOC"),
("Arcadie", "LOC"),
("Ardene", "LOC"),
("Argoilles", "NAT"),
("Argoillie", "NAT"),
("Argone", "LOC"),
("Aristote", "CLAS"),
("Arrabe", "NAT"),
("Arrabit", "LOC"),
("Arrabiz", "LOC"),
("Arragon", "LOC"),
("Arras", "LOC"),
("Artu", "CHI"),
("Artur", "CHI"),
("Artus", "CHI"),
("Artus de Bretaigne", "CHI"),
("Astors", "CHI"),
("Astramariz", "CHI"),
("Attun", "CHI"),
("Austorie", "CHI"),
("Avalun", "LOC"),
("Avers", "NAT"),
("Babiloine", "LOC"),
("Bade", "LOC"),
("Bademagu", "CHI"),
("Bademagus", "CHI"),
("Bademaguz", "CHI"),
("Baivere", "LOC"),
("Baivers", "LOC"),
("Baivier", "LOC"),
("Balaguez", "LOC"),
("Balasgued", "LOC"),
("Baldewin", "CHI"),
("Baldise", "LOC"),
("Balide", "LOC"),
("Baligant", "CHI"),
("Barbamusche", "ANI"),
("Barbefluet", "LOC"),
("Basan", "CHI"),
("Basant", "CHI"),
("Basbrun", "CHI"),
("Bascle", "LOC"),
("Basilie", "CHI"),
("Basilies", "CHI"),
("Baudas", "LOC"),
("Bavier", "LOC"),
("Bede", "AUT"),
("Bel Joeor", "ANI"),
("Belneor", "LOC"),
("Berenger", "CHI"),
("Berengers", "CHI"),
("Berin", "LOC"),
("Bernard", "CHI"),
("Berox", "AUT"),
("Berte", "CHI"),
("Berte as grans piés", "CHI"),
("Berteram", "CHI"),
("Bertram", "CHI"),
("Besençun", "LOC"),
("Besgun", "VIL"),
("Bevon", "CHI"),
("Bire", "LOC"),
("Biterne", "LOC"),
("Blaceflor", "CHI"),
("Blaive", "REL"),
("Blancandrins", "CHI"),
("Blanceflo", "CHI"),
("Blanceflor", "CHI"),
("Blanceflore", "CHI"),
("Blanceflors", "CHI"),
("Blanchandrins", "CHI"),
("Blaru", "VIL"),
("Blerain", "A"),
("Blere", "A"),
("Blos", "LOC"),
("Bonivent", "LOC"),
("Borguignuns", "NAT"),
("Bougerie", "LOC"),
("Boulogne", "LOC"),
("boulongne", "LOC"),
("Bourgoigne", "LOC"),
("Bourgongne", "LOC"),
("Bramidonie", "CHI"),
("Bramimunde", "CHI"),
("Breban", "LOC"),
("Breibançon", "LOC"),
("Brengain", "CHI"),
("Brenguein", "CHI"),
("Bretagne la Menur", "LOC"),
("bretaigen", "LOC"),
("Bretaigne", "LOC"),
("Bretaigne la Menur", "LOC"),
("Bretanz", "LOC"),
("Bretun", "NAT"),
("Bretuns", "NAT"),
("Brochet", "ANI"),
("Bruise", "LOC"),
("Brunain", "ANI"),
("Bruns", "LOC"),
("Brusban", "LOC"),
("Bucifax", "CHI"),
("Bugre", "NAT"),
("Buluigneis", "NAT"),
("Burdel", "LOC"),
("Burgoine", "LOC"),
("Burguigne", "LOC"),
("Butentrot", "LOC"),
("Calabre", "LOC"),
("Calcide", "LOC"),
("Califerne", "LOC"),
("Camp Flori", "LOC"),
("Canabeus", "CHI"),
("Canelius", "NAT"),
("Capadoce", "LOC"),
("Capadosse", "LOC"),
("Capuel", "CHI"),
("Carcasonie", "LOC"),
("Carduel", "LOC"),
("Carle", "CHI"),
("Carlemagnes", "CHI"),
("Carlemain", "CHI"),
("Carlemaine", "CHI"),
("Carlemaines", "CHI"),
("CARLES", "CHI"),
("Carles", "CHI"),
("Carles de France", "CHI"),
("Carles li Magnes", "CHI"),
("Carleun ", "LOC"),
("Carloon", "LOC"),
("Carlun", "LOC"),
("Cartres", "LOC"),
("Caruënt", "LOC"),
("Castel de Valfunde", "LOC"),
("Castele", "LOC"),
("Cazmarine", "LOC"),
("Cervestre", "REL"),
("Cesar", "CLAS"),
("Chaitivel", "TIT"),
("challemasre", "VIL"),
("Chanpaigne", "LOC"),
("Charle ", "CHI"),
("Charlemagne", "CHI"),
("Charlemaigne", "CHI"),
("Charlemaine", "CHI"),
("Charles", "CHI"),
("Charles Maines", "CHI"),
("Charlun", "CHI"),
("Chastellet", "LOC"),
("Chatons", "CHI"),
("Cheriant", "LOC"),
("Chernuble", "CHI"),
("Chernubles", "CHI"),
("Chernubles de Munigre", "CHI"),
("Cherubin", "CLAS"),
("Chevalier du guet", "CHI"),
("Cholet", "LOC"),
("Christine", "AUT"),
("Cinglor", "CHI"),
("Clarbone", "LOC"),
("Clarïen", "CHI"),
("Clarifan", "CHI"),
("Clarin de Balaguet", "CHI"),
("Clavers", "CHI"),
("Climborins", "CHI"),
("Climorins", "CHI"),
("Coguillanz de Mautirec", "CHI"),
("Colin Laurens", "VIL"),
("Commibles", "LOC"),
("Constans", "LOC"),
("Constantinoble ", "LOC"),
("Constentinoble", "LOC"),
("Cordres", "LOC"),
("Coris", "CHI"),
("Corneualeis", "LOC"),
("Cornoaille", "LOC"),
("Cornot", "NAT"),
("Cornoualle", "LOC"),
("Cornuaille", "LOC"),
("Cornuelan", "NAT"),
("Cornuelois", "NAT"),
("Corsablix", "CHI"),
("Corsalis", "CHI"),
("Costantin", "CLAS"),
("Costentin", "CLAS/LOC"),
("Costentinnoble", "LOC"),
("Costentinoble", "LOC"),
("Costuntinoble", "LOC"),
("Crestïens", "AUT"),
("Crisans de Rome", "CHI"),
("Cristus", "REL"),
("Croiz Partie", "LOC"),
("Cuerlion", "LOC"),
("Cupido", "CLAS"),
("Daciens", "CLAS"),
("Daires", "CLAS"),
("Damedex", "REL"),
("Damledé", "REL"),
("Damledieu", "REL"),
("Damne-Dé", "REL"),
("Damnedeu", "REL"),
("Dampnedeu", "REL"),
("Danaalain", "CHI"),
("Daniel", "REL"),
("Dapamort", "CHI"),
("Dathan", "REL"),
("David", "REL"),
("Dé", "REL"),
("Delbora", "REL"),
("Denemarche", "LOC"),
("Denise", "REL"),
("Denoalan", "CHI"),
("Des", "REL"),
("Deu", "REL"),
("Deus", "REL"),
("Deücalion", "CLAS"),
("Dex", "REL"),
("Dido", "CLAS"),
("Dieu", "REL"),
("dieu", "REL"),
("Dieus", "REL"),
("Dieux", "REL"),
("Digun", "LOC"),
("Dinan", "LOC"),
("Dinas", "LOC"),
("Dinoalain", "CHI"),
("Diu", "REL"),
("Dol", "LOC"),
("Donbes", "LOC"),
("Donoalen", "CHI"),
("Droün", "CHI"),
("Duëlas", "LOC"),
("Dun", "LOC"),
("Dureaume", "LOC"),
("Durelme", "LOC"),
("Durendal", "SW"),
("Durestant", "LOC"),
("dyable", "REL"),
("Dyane", "CLAS"),
("Echo", "CLAS"),
("Egipte", "LOC"),
("Eis", "LOC"),
("Elaine", "CLAS"),
("Eliduc", "CHI"),
("Elidus", "CHI"),
("Eneas", "CLAS"),
("Eneslepas", "CHI"),
("Enfer", "LOC"),
("Enfruns", "NAT"),
("Engleis", "NAT"),
("Engletere", "LOC"),
("Engleterre", "LOC"),
("Envers sur le Rosne", "LOC"),
("Equitaine", "LOC"),
("Equitan", "CHI"),
("Ermines", "LOC"),
("Ernalz", "CHI"),
("Esclavoz", "NAT"),
("Escoce", "LOC"),
("Escoz", "LOC"),
("Escremiz de Valterne", "CHI"),
("Esme", "REL"),
("Espaigne", "LOC"),
("Espaigneis", "NAT"),
("Espaine", "LOC"),
("Estamarin", "CHI"),
("Estefne", "REL"),
("Estorgans", "CHI"),
("Esturganz", "CHI"),
("Esturguz", "CHI"),
("Ethiope", "LOC"),
("Eudropin", "CHI"),
("Eufemiiens", "CHI"),
("Eufrates", "LOC"),
("Eugiez", "CHI"),
("Evains", "CHI"),
("Evrol", "REL"),
("Excestre", "LOC"),
("Excoce", "LOC"),
("Faires", "CHI"),
("Faldrun de Pui", "CHI"),
("Falsaron", "CHI"),
("Felis", "CHI"),
("Ferlin", "LOC"),
("Flamenc", "NAT"),
("Flamengs", "NAT"),
("Flamens", "NAT"),
("Flandres", "LOC"),
("Flemenc", "NAT"),
("Floire", "CHI"),
("Floires", "CHI"),
("Flore", "CHI"),
("Floredee", "LOC"),
("Flores", "CHI"),
("Flurit", "CHI"),
("Foiz", "LOC"),
("Fournier", "VIL"),
("Fraisne", "CHI"),
("Fraisnes", "CHI"),
("Franc", "NAT"),
("France", "LOC"),
("Franceis", "NAT"),
("François", "NAT"),
("Francor", "NAT"),
("Françoy Villon", "AUT"),
("Francs", "NAT"),
("Frise", "LOC"),
("Frisuns", "NAT"),
("Frocin", "VIL"),
("Frocine", "VIL"),
("Frocins", "VIL"),
("Fronde", "LOC"),
("gabriel", "REL"),
("Gabriel", "REL"),
("Gaides", "CHI"),
("Gaidon", "CHI"),
("Gaidons", "CHI"),
("Gaifiers", "CHI"),
("Galafes", "CHI"),
("Gales", "LOC"),
("Galice", "LOC"),
("Galisse", "LOC"),
("Gallois", "NAT"),
("Galne", "LOC"),
("Gant", "LOC"),
("Garmalie", "CHI"),
("Gascoigne", "LOC"),
("Gascuigne", "LOC"),
("Gaugains", "CHI"),
("Gauvain", "CHI"),
("Gauvains", "CHI"),
("Gavoie", "LOC"),
("Gebuin", "CHI"),
("Gédéon", "CHI"),
("Gefrei d’Anjou", "CHI"),
("Gefreit d’Anjou", "CHI"),
("Geifreit", "CHI"),
("Gemalfin", "CHI"),
("Genin", "CHI"),
("george", "REL"),
("Gerard", "CHI"),
("Gerard de Russillun", "CHI"),
("Gerart de Rossillon", "CHI"),
("Gerers", "CHI"),
("Gerflet", "CHI"),
("Gerin", "CHI"),
("Gibuins", "CHI"),
("Gilie", "CHI"),
("Girard Gossuïn", "VIL"),
("Girflez", "CHI"),
("Girunde", "LOC"),
("Gloris", "CHI"),
("Godefroiz de Leigni", "CHI"),
("Godoïne", "CHI"),
("Godselmes", "CHI"),
("Golias", "REL"),
("Gorre", "LOC"),
("Gotte", "LOC"),
("Goudoïne", "CHI"),
("Gouvernal", "CHI"),
("Gouvieulx", "LOC"),
("Governal", "CHI"),
("Governauz de Roberdic", "CHI"),
("Gramimund", "ANI"),
("Grandonie", "CHI"),
("Grandonies", "CHI"),
("Grece", "LOC"),
("Greignor", "CHI"),
("Griu", "NAT"),
("Grius", "NAT"),
("Gros", "LOC"),
("Gros Figuier", "LOC"),
("Grossaille", "LOC"),
("Guales", "LOC"),
("Gualter", "CHI"),
("Gualter de Hums", "CHI"),
("Gualter de l’Hum", "CHI"),
("Gualters", "CHI"),
("Guarlan", "CHI"),
("Guascuigne", "LOC"),
("Guascuinz de Burdele", "CHI"),
("Guascuinz Engeler", "CHI"),
("Gué Aventuros", "LOC"),
("Guenelon", "CHI"),
("Guenelons", "CHI"),
("Guenelun", "CHI"),
("Guenes", "CHI"),
("Guenievre", "CHI"),
("Guesnes", "CHI"),
("Guhtlande", "LOC"),
("Guigemar", "CHI"),
("Guildeluëc", "CHI"),
("Guillames", "CHI"),
("Guillaume", "CHI"),
("guillaume", "CHI"),
("Guillaume Cottin", "VIL"),
("Guillaume De Lorris", "AUT"),
("Guillaume Villon", "VIL"),
("guillemette", "VIL"),
("Guillemette", "VIL"),
("Guilliadun", "CHI"),
("Guillot Gueutry", "VIL"),
("Guinables", "CHI"),
("Guineman", "CHI"),
("Guinemans", "CHI"),
("Guinemer", "CHI"),
("Guitsand", "LOC"),
("Guneman", "CHI"),
("Gurun", "LOC"),
("Haimer", "CHI"),
("Halteclere", "SW"),
("Haltoïe", "CHI"),
("Hamon de Galice", "CHI"),
("Hector", "CLAS"),
("Helaine", "CLAS"),
("Henoiers", "LOC"),
("Henri", "CHI"),
("Hermans", "CHI"),
("Hester", "REL"),
("Hoilas", "CHI"),
("Hongerie", "LOC"),
("Hudent", "ANI"),
("Hugue", "CHI"),
("Hugun", "CHI"),
("Hums", "LOC"),
("Hungerie", "LOC"),
("Hungre", "LOC"),
("Hungres", "LOC"),
("Husdan", "ANI"),
("Husdant", "ANI"),
("Husdens", "ANI"),
("Husdent", "ANI"),
("Husdenz", "ANI"),
("iehan", "REL"),
("iehan de noyon", "ANI"),
("Ignores", "!"),
("Imphe", "LOC"),
("Innocenz", "REL"),
("ioceaulme", "VIL"),
("Irlande", "LOC"),
("Irlandë", "LOC"),
("Iseut", "CHI"),
("Isneldone", "LOC"),
("Israel", "LOC"),
("Ivain", "CHI"),
("Ivains", "CHI"),
("Ivein", "CHI"),
("Ivon", "CHI"),
("Ivorie", "CHI"),
("Iyesses", "LOC"),
("Iysses", "LOC"),
("Jacques Cardon", "VIL"),
("Jacques Raguier", "VIL"),
("Jaianz", "CHI"),
("Jangleu", "CHI"),
("Jasque", "REL"),
("Jehan", "VIL"),
("Jehan le Cornu", "VIL"),
("Jehan Marceau", "VIL"),
("Jehan Mautaint", "VIL"),
("Jehan Raguier", "VIL"),
("Jehan Trouvé", "VIL"),
("Jehanne de Millieres", "VIL"),
("Jericho", "LOC"),
("Jerico", "LOC"),
("Jerusalem", "LOC"),
("Jesu", "REL"),
("Jesu-Crist", "REL"),
("Jesum", "REL"),
("Jesus", "REL"),
("Jesus-Crist", "REL"),
("Jhesu", "REL"),
("Jhesus", "REL"),
("jhesuscrist", "REL"),
("Jobel", "REL"),
("Johan", "REL"),
("Johanne", "REL"),
("Joiuse", "SW"),
("Jonas", "REL"),
("Josué", "REL"),
("Joüner", "CHI"),
("Jozeran de Provence", "CHI"),
("Jozerans", "CHI"),
("Judeus", "REL"),
("Judith", "REL"),
("Juliane", "CHI"),
("Juno", "CLAS"),
("Juras", "!"),
("Jurfaleu", "CHI"),
("Jurfaret", "CHI"),
("Justin de Val Ferree", "CHI"),
("Kardoeil", "LOC"),
("Karle", "CHI"),
("Karlemagne", "CHI"),
("Karlemaine", "CHI"),
("Karlemaines", "CHI"),
("Karles", "CHI"),
("Karles li Magnes", "CHI"),
("Karleun", "LOC"),
("Karlion", "LOC"),
("Karliün", "LOC"),
("Karlon", "CHI"),
("Kartagene", "LOC"),
("Kes", "CHI"),
("Keu", "CHI"),
("Keulx", "CHI"),
("Kex", "CHI"),
("Kex d’Estrax", "CHI"),
("La Blanche Lande", "LOC"),
("la Coldre", "LOC"),
("la Croiz", "LOC"),
("la Croiz Roge", "LOC"),
("la Tors as Puceles", "LOC"),
("labbe diverneaux", "REL"),
("laignelet", "VIL"),
("Lalice", "LOC"),
("Lancelot", "CHI"),
("Lanceloz", "CHI"),
("Lanceloz del Lac", "CHI"),
("Lancïen", "LOC"),
("Lanval", "CHI"),
("Latanie", "LOC"),
("Latin", "NAT"),
("Laurence", "VIL"),
("Lavine", "CLAS"),
("Lazare", "REL"),
("Lazaron", "REL"),
("Le Fraisne", "CHI"),
("Leda", "CLAS"),
("Lenfer", "LOC"),
("Licoris", "CHI"),
("Lidan", "LOC"),
("Liün", "LOC"),
("Loengre", "LOC"),
("Loengres", "LOC"),
("Loenoi", "LOC"),
("Loenois", "LOC"),
("Loewis", "CHI"),
("Logres", "LOC"),
("Loheregne", "LOC"),
("Lohereigne", "LOC"),
("Loherencs", "LOC"),
("Loherengs", "LOC"),
("Lombardie", "LOC"),
("Londres", "LOC"),
("Looÿs", "CHI"),
("Lorant", "CHI"),
("lorine", "LOC"),
("Lorraine", "LOC"),
("lorraine", "LOC"),
("Loüm", "LOC"),
("Lumbardie", "LOC"),
("Lymoges", "LOC"),
("Lÿon", "LOC"),
("Machiner", "CHI"),
("Macrobe", "AUT"),
("Maelgut", "LOC"),
("magdelene", "REL"),
("Maheu", "REL"),
("Mahum", "REL"),
("Mahumet", "REL"),
("Maine", "LOC"),
("Pierre pathelin", "VIL"),
("Robert", "VIL"),
("Mal Pas", "LOC"),
("Malbien", "CHI"),
("Malcud", "CHI"),
("Malduit", "CHI"),
("Malpalin de Nerbone", "CHI"),
("Malpertuis", "CHI"),
("Malpramis", "CHI"),
("Malpreis", "LOC"),
("Malprimis de Brigal", "CHI"),
("Malprimis de Brigant", "CHI"),
("Malprose", "LOC"),
("Malquiant", "CHI"),
("Maltet", "CHI"),
("Maltraïen", "CHI"),
("Malun", "CHI"),
("Malvais", "LOC"),
("Marbrise", "LOC"),
("Marbrose", "LOC"),
("Marc", "CHI"),
("Marcilie", "CHI"),
("Marcules", "CHI"),
("Marganices", "CHI"),
("Margariz", "CHI"),
("Margariz de Sibilie", "CHI"),
("Marie", "AUT"),
("marie", "REL"),
("Maries", "REL"),
("Marisliuns", "CHI"),
("Marmorie", "ANI"),
("Mars", "CHI"),
("Marsile", "CHI"),
("Marsilie", "CHI"),
("Marsilies", "CHI"),
("Marsiliun", "CHI"),
("Marsune", "LOC"),
("Martin", "REL"),
("martin garant", "VIL"),
("Maruse", "LOC"),
("Maseüz", "CHI"),
("mathelin", "REL"),
("mathurin", "REL"),
("Mau Pensé", "LOC"),
("Meleagant", "CHI"),
("Meleaganz", "CHI"),
("Meliagant", "CHI"),
("Meliaganz", "CHI"),
("Melitaine", "LOC"),
("Meriadu", "CHI"),
("Meriadus", "CHI"),
("Merlin", "CHI"),
("Micenes", "CHI"),
("Michel", "REL"),
("Michel del Peril", "CHI"),
("Militaine", "LOC"),
("Milun", "CHI"),
("Minor", "CLAS"),
("Mirebeuf", "VIL"),
("Monfelis", "LOC"),
("Monpellier", "LOC"),
("Montigny", "LOC"),
("Montoire", "LOC"),
("Morhot", "CHI"),
("Morhout", "CHI"),
("Moriane", "LOC"),
("Morrois", "LOC"),
("Mors", "CHI"),
("Moutonnier", "VIL"),
("Moyses", "REL"),
("Muldumarec", "CHI"),
("Munjoie", "OTHER"),
("Munt Seint Michiel", "LOC"),
("Murgleis", "SW"),
("Murglies", "SW"),
("Naimes", "CHI"),
("Naimon", "CHI"),
("Nans", "LOC"),
("Nantes", "LOC"),
("Naples", "LOC"),
("Narcisus", "CLAS"),
("Neimes", "LOC"),
("Nerbone", "LOC"),
("Neüstrie", "LOC"),
("Nevelun", "CHI"),
("Nicette", "VIL"),
("Nicolas de Louviers", "CHI"),
("Nicole", "LOC"),
("Nigres", "LOC"),
("Niniven", "LOC"),
("Niques", "LOC"),
("Noauz", "REL"),
("Noe", "REL"),
("Noël", "F"),
("Nöex", "REL"),
("Noirs de la Montaigne", "CHI"),
("Noples", "LOC"),
("Norhumbre", "LOC"),
("Norman", "NAT"),
("Normandie", "LOC"),
("Normans", "NAT"),
("Normendie", "LOC"),
("Norweie", "LOC"),
("Nostre Dame", "REL"),
("Nubie", "LOC"),
("Nubles", "LOC"),
("Nygon", "ANI"),
("Occian", "CHI"),
("Occident", "LOC"),
("Ociant", "CHI"),
("Oger", "CHI"),
("Oger de Deenemarche", "CHI"),
("Oger de Denemarche", "CHI"),
("Oger li Daneis", "CHI"),
("Ogers", "CHI"),
("Ogrin", "CHI"),
("Ogrins", "CHI"),
("Oliver", "CHI"),
("Omer", "AUT"),
("Onorie", "LOC"),
("Orange", "LOC"),
("Orient", "LOC"),
("Orïent", "LOC"),
("Orléans", "LOC"),
("Orliens", "LOC"),
("Ormaleis", "LOC"),
("Ormaleus", "LOC"),
("Orri", "VIL"),
("Otes", "CHI"),
("Otovian", "CLAS"),
("Otun", "CHI"),
("Ovide", "AUT"),
("Oyseuse", "!"),
("Pallas", "CLAS"),
("Panpelune", "LOC"),
("Pantecoste", "F"),
("Paradis", "LOC"),
("Parelement", "!"),
("pargigon", "REL"),
("Paris", "LOC"),
("Parys", "LOC"),
("Parthonopeus", "CLAS"),
("Paske Flourie", "F"),
("Passecerf", "LOC"),
("Passelande", "ANI"),
("Pater noster", "REL"),
("Pathelin", "VIL"),
("Peitevins", "NAT"),
("Peitiers", "LOC"),
("Peitou", "LOC"),
("Pentecoste", "F"),
("Penthecouste", "F"),
("Perrenet Merchant", "VIL"),
("Pere", "REL"),
("Perinis", "VIL"),
("Perre", "REL"),
("Persis", "CHI"),
("Persaunz", "NAT"),
("Perse", "LOC"),
("Petitevins", "!"),
("picardie", "LOC"),
("Piere", "REL"),
("pierre", "VIL"),
("Pierre Basannier", "VIL"),
("Pierre de Rousseville", "VIL"),
("pierre pathelin", "VIL"),
("Piladés", "CHI"),
("Pinabel", "CHI"),
("Pinabels", "CHI"),
("Pinceneis", "LOC"),
("Pine", "LOC"),
("Piramus", "CLAS"),
("Pirra", "CLAS"),
("Pis", "LOC"),
("Pistre", "LOC"),
("Pistreis", "LOC"),
("Platon", "CLAS"),
("Pomelegoi", "LOC"),
("Pomelesglai", "LOC"),
("Popin", "LOC"),
("Preciëns", "AUT"),
("Preciuse", "S"),
("Priamun", "CLAS"),
("Primes", "LOC"),
("Provence", "LOC"),
("Puillan", "LOC"),
("Puillanie", "LOC"),
("Puille", "LOC"),
("Pymalion", "CLAS"),
("Qeu", "CHI"),
("Quatre Doels", "LOC"),
("Ques", "CHI"),
("Rabel", "CHI"),
("Rabels", "CHI"),
("Rache", "REL"),
("Rains", "LOC"),
("Regnier de Montigny", "CHI"),
("Reiner", "CHI"),
("Rembalt", "CHI"),
("Rencesval", "LOC"),
("Rencesvals", "LOC"),
("Rencevals", "LOC"),
("Renebors", "LOC"),
("Richard", "CHI"),
("Robert Valee", "VIL"),
("Roche del Guitume", "CHI"),
("Rodomadus", "CLAS"),
("Rolland", "CHI"),
("Rollant", "CHI"),
("Romain", "NAT"),
("Romaine", "NAT"),
("Romanie", "LOC"),
("Romanz", "LAN"),
("Rome", "LOC"),
("Rommain", "NAT"),
("romme", "LOC"),
("Rosne", "LOC"),
("rue Saint Anthoine", "LOC"),
("Rume", "LOC"),
("Runers", "LOC"),
("Sainct Amant", "REL"),
("Sainct Jacques", "REL"),
("sainct Mor", "REL"),
("saincte marie", "REL"),
("Saincte Paternostre", "REL"),
("sains Jorge", "REL"),
("Saint André", "REL"),
("saint Anthoine", "REL"),
("Saint Denis", "REL"),
("Saint Esperit", "REL"),
("saint Esperite", "REL"),
("Saint Estienne", "REL"),
("saint gille", "REL"),
("saint iacques", "REL"),
("saint iean", "REL"),
("saint Jake", "REL"),
("saint Jorge", "REL"),
("Saint Lubin", "REL"),
("saint pierre", "REL"),
("saint pierre lapostre", "REL"),
("Saint Richier", "REL"),
("Saint Sanson", "REL"),
("Saint Tresmor de Carahès", "REL"),
("Saint Valentin", "REL"),
("Saint-Esprit", "REL"),
("Sainte Marie", "REL"),
("sainte Marie", "REL"),
("sainte marie", "REL"),
("Sainte Terre", "REL"),
("Sainz Alexis", "REL"),
("Sainz Boneface", "REL"),
("Sainz Esperiz", "REL"),
("Sainz Innocenz", "REL"),
("Saisne", "NAT"),
("Saisnes", "NAT"),
("Saisonie", "LOC"),
("Salemon", "REL"),
("Salerne", "LOC"),
("Salmon", "REL"),
("Salomon", "REL"),
("Samuel", "REL"),
("Sansun", "REL"),
("Sarazin", "NAT"),
("Sarazins", "NAT"),
("Sarraguce", "LOC"),
("Sarrasins", "NAT"),
("Sarrazin", "NAT"),
("Sarrazins", "NAT"),
("Scipion", "CLAS"),
("Sebile", "CHI"),
("Sebre", "LOC"),
("Segoçon", "LOC"),
("seigneur de Grigny", "CHI"),
("Seignor de Rome", "CHI"),
("Seine", "LOC"),
("seint Aaron", "REL"),
("Seint Antonie", "REL"),
("seint Clement", "REL"),
("Seint Denis", "REL"),
("Seint Johan", "REL"),
("Seint Malo", "REL"),
("seint Nicholas", "REL"),
("seinte Marie", "REL"),
("Seinz", "REL"),
("Seisne", "NAT"),
("Semiramis", "CHI"),
("Senz Per", "CHI"),
("Serbonne", "LOC"),
("Sesne", "NAT"),
("Sevrin", "REL"),
("Sezilie", "LOC"),
("Simeon", "REL"),
("Sirie", "LOC"),
("Sizer", "LOC"),
("Solteras", "LOC"),
("Sorbres", "LOC"),
("Sorel", "ANI"),
("Sorence", "LOC"),
("Sorz", "LOC"),
("Suatilie", "LOC"),
("Suhthamptune", "LOC"),
("Suhtwales", "LOC"),
("Sulians", "CHI"),
("Table Reonde", "LOC"),
("Tachebrun", "A"),
("Tarson", "LOC"),
("Taulas de la Deserte", "CHI"),
("Tedbalt", "CHI"),
("Tedbalt de Reins", "CHI"),
("Tencendor", "CHI"),
("Tencendur", "CHI"),
("Tervagan", "REL"),
("Tervagant", "REL"),
("Tessaile", "LOC"),
("Thessaile", "LOC"),
("Thibault", "CHI"),
("Thibault de Vittry", "CHI"),
("thibaut", "VIL"),
("Thoas", "LOC"),
("Thomas", "VIL"),
("Those", "!"),
("Tiedeis", "NAT"),
("Tierri", "CHI"),
("Tierris", "CHI"),
("Timozel", "CHI"),
("Tintagel", "LOC"),
("Tintaguel", "LOC"),
("Tintajol", "LOC"),
("Tolas", "CHI"),
("Tolose", "LOC"),
("Torleu", "CHI"),
("Torleus", "CHI"),
("Toteneis", "LOC"),
("Trace", "LOC"),
("Tristram", "CHI"),
("Tristran", "CHI"),
("Tristrans", "CHI"),
("Tristrant", "CHI"),
("Troies", "LOC"),
("Troyes", "LOC"),
("Trumillieres", "LOC"),
("Tudele", "LOC"),
("Tuele", "CHI"),
("Tulette", "CHI"),
("Turcs", "NAT"),
("Turgis de Turteluse", "CHI"),
("Turoldus", "CHI"),
("Turpin", "CHI"),
("Turpins", "CHI"),
("Turpins de Reins", "CHI"),
("Urïen", "CHI"),
("Val Fuit", "LOC"),
("Val Marchis", "LOC"),
("Val Sevree", "LOC"),
("Valdabrun", "CHI"),
("Valdabruns", "CHI"),
("Valence", "LOC"),
("Vales", "LOC"),
("Valterne", "LOC"),
("Vauvain", "CHI"),
("Vegece", "CLA"),
("Veillantif", "A"),
("Venus", "CLA"),
("Vénus", "CLA"),
("Villon", "AUT"),
("Virgilie", "CLA"),
("Vivien", "CLA"),
("Vulcans", "CLA"),
("Wales", "LOC"),
("Walwains", "CHI"),
("Willalme de Blaive", "CHI"),
("Willeme", "CHI"),
("Willemes de Orenge", "CHI"),
("Yders", "CHI"),
("Ylaire", "REL"),
("Yliers", "LOC"),
("Yonec", "CHI"),
("Yrlande", "LOC"),
("Yseut", "CHI"),
("Ysmaine", "CLAS"),
("Ytier Merchant", "VIL"),
("Yvain", "CHI"),
("Yvains", "CHI"),
("Yvoeries", "CHI"),
("Ywains", "CHI")]

