forms_and_lemmas = {"AAISEMENT":["aeisemant"],
"AANCRER":["aencré"],
"ÄATINE":["ahatine"],
"AAISIER":["aeisier", "aeisié", "aeisiee", "aeisiez", "aeise", "aeisent"],
"ABAIIER":["abaient"],
"ABAISSIER":["abeissié", "abeissiez", "abessié", "abessiee", "abessiez", "abeisse", "abesse", "abeissent", "abessent", "abeissa", "abeissera"],
"ABANDONER":["abandoné", "abandonee", "abandonees", "abandon", "abandone", "abandona"],
"ABATRE":["abatre", "abatu", "abatue", "abatuz", "abat", "abatent", "abati", "abatié", "abatront", "abate", "abatist"],
"ABÉ1":["abes", "abez"],
"ABET":["abet", "abez"],
"ABEVRER":["abevrer", "abevree", "aboivrent"],
"ABEIE":["abeïe", "abbaie", "abbatia", "abbaye", "abaïe", "abaïes"],
"ABEL":["Abel"],
"ABELIR":["abelir", "abellir", "abelist", "abelissent", "abeli", "abelisse"],
"ABRAHAN":["Abrahan"],
"ABREGIER":["abregier", "abreger", " abréger", "abréger"],
"ABRIVER":["abrivé", "abriver"],
"ACCIDENT":["accidant", "accident", "accidens"],
"ABISME":["abisme", "abyssus", "abîme"],
"ABITER":["habiter", "abiter", "abite"],
"ABONDER":["abonder", "abunder", "abonde"],
"ABORRER":["anborrer", "aborrer", "aborré"],
"ACEINDRE":["açaindre", "aceindre", "aceint", "aceignent", "aceingnoit", "aceindrons"],
"ACENSION":["Asçansion", "acension", "ascenciun", "ascension", "Acenssion"],
"ACHATER":["acheter", "achater", "achate", "achatent"],
"ACHEMINER":["acheminer", "achemine", "acheminerent"],
"ACIER":["acier"],
"ACERER":["aceré", "acérer", "acerer", "aceree"],
"ACESMER":["acesmer", "acesmee", "acesmez"],
"ACLINER":["acliner", "acline"],
"ACOARDIR":["acoardir", "acouardir", "accouardir", "acuardir", "acoardi", "acoardie", "acoardiz"],
"ACOILLIR":["acoillir", "acueillier", "acueillir", "acueudre", "accueillir", "acoillie", "aquiaus", "aquialt", "aquiaut", "acuellent", "acuelle"],
"ACOINTABLE":["acointable", "accointable"],
"ACOINTANCE":["acointance", "acuintance", "accointance", "acointances", "acontance"],
"ACOINTE1":["acointe", "acuinte", "accointe", "acointes"],
"ACOINTIER":["acointier", "acuinter", "acointié", "acoint", "acointe", "acointoient", "acointa", "acointierent", "acointasse"],
"ACOISIER":["aqueisier", "acoisier", "accoiser", "acoise"],
"ACOMPAGNIER":["aconpaignier", "acompagnier", "acompaignier", "acumpainer ", "aconpaigne", "aconpaignent", "accompagner"],
"ACOLER":["acoler", "accoler", "acoler", "acole", "acolent", "acola"],
"ACOMPLIR":["aconplir", "acomplir", "accomplir", "aconpliz"],
"ACONSIVRE":["aconsiure", "aconsivre", "aconcevoir", "aconsievir", "aconsivre", "acunsivre", "aconsuivre", "aconsivre", "aconseü", "aconseüe"],
"AÇOPER":["açoper", "achoper", "achopper", "açopa"],
"ACOPLER":["acopler", "acoupler", "accoupler", "acople"],
"ACOR":["acor", "acort", "acors"],
"ACORDANCE":["acordance", " accordance"],
"ACORDE1":["acorde", "acord"],
"ACORDE2":["Acorde"],
"ACORDER":["acorder", "accorder", "acordé", "acordee", "acordez", "acort", "acorde", "acordent", "acorderent", "acorderai", "acorde"],
"ACORER":["acorer", "acoré", "acoree", "acorees", "acorez"],
"ACORIONDE":["Acoridomés", "Acorionde", "Acoriundés"],
"ACORRE":["acorre", "acourir", "acurre", "accourir", "accourir", "acort", "acorent"],
"ACOSTER":["acoster", "accoster", "acostee", "acostez", "acoste"],
"ACOSTUMANCE":["acostumance", "accoutumance"],
"ACOSTUMEEMENT":["acostumeemant", "acustumeement", "accoutumément"],
"ACOSTUMER":["acostumer", "acoustumer", "accoutumer", "acustumer", "acostumé", "acostumez"],
"ACOTER":["acoter", "acuter", "accoter", "accouder", "acoder", "acotez"],
"ACREANTER":["acreanter", " acréanter", "acreanté", "acreant", "acreanz", "acreante", "acreantez", "acreant"],
"ACROIRE":["acroire", "acreire", "accroire", "acreü", "acroit", "acrurent", "acroie"],
"ACROISTRE":["acroistre", "acreistre", "accroître", "acrois", "accroist", "acroist", "acroissoit"],
"ADAN":["Adan", "Adanz"],
"ADESER":["adeser", "adoise", "adesa", "adoist", "adesast"],
"ADESTRER":["adestrer", "adextrer", "adestre"],
"ADEVANCIR":[" adevancir", "adevancirent"],
"ADOBER":["adober", "aduber", "dubban", "adouber", "adobé", "adobez", "adoba", "adoberoit"],
"ADOLER":["adolé", "adoler", " aduler", "adouler", "adolez"],
"ADRECIER":["adrecier", "adrescer", "adresser", "adrecié", "adreciee", "adreciez", "adrece", "adresce", "adreça"],
"ADONER":["adoner", "adonner", "adonee"],
"ADOSSER":["adosser", "adossez"],
"ADOUCIR":["adoucir", "aducer", "adolcir"],
"ADRECE":["adresce", "adrece", "adresse"],
"ADROIT":["adroit", "adreit", "adroit", "adroite", "adroiz"],
"ADURÉ":["aduré", "adurer", "adurez"],
"AÉ":["aé", "eé", "ahé"],
"AERDRE":["aerdre", "aers", "aert", "ahert", "aerdent"],
"AFAIRE":["afeire", "afaire", "affaire", "afaires", "afeires", "afere"],
"AESCHIER":["aeschier", "aeschoit"],
"AESMER":["aesmer", "asmer", "aesmez"],
"AFAITEMENT":["afeitemant", "afaitement"],
"AFAITIER":["afeitier", "afaitier", "afaiter", "affaiter", "afeitiee", "afeitiez", "afeitié", "afaite", "afeite"],
"AFAMER":["afamer", "affamer", "afamez"],
"AFEBLIIER":["afebloiier", "afebliier", "affaibloyer", "afebloier", "afebli", "afeblie", "afeblissent"],
"AFERIR":["aferir", "afferir", "afférir", "afiert", "afierent"],
"AFEBLIR":["afebloier", "afebloiez", "afeblir", "affaiblir", "afoiblir"],
"AFÏER":["afïer", "afier", "affier", "afiee", "afi", "afie", "afïent", "afia"],
"AFERMER":["afermer ", "affermer", "afermee"],
"AFICHIER":["afichier", "afficher", "afichiez", "afiche", "afichent"],
"AFIT2":["afit", "afiz", "afi"],
"AFITIER":["afiter", "afitier", "affité", "afeitant"],
"AFOLER1":["afoler", "afuler", "affoler", "afolé", "afolee", "afolez", "afole", "afolent", "afoloit", "afole", "afolt", "afost"],
"AFOLER2":["afoler", "afole", "afolent", "afolent"],
"AFONDER":["afonder", "enfundrer", "affonder", "afonde"],
"AGAIT":["aguet", "agait", "aguait "],
"AGAITIER":["agueitier", "agaitier", "aguaiter", "guetter", "agueitié", "agueitiee", "agueites", "agaite", "agueite", "agaitiez"],
"AFRENER":["afrener", "afreiner", "enfrener", "afreinne"],
"AFUBLER":["afubler", "affubler", "afublé", "afublee", "afublees", "afublez", "afuble", "afublerent", "afublez", "afubla"],
"AGENCIR":["ajancier", "ajancir", "agencir ", "agensir", "agencist"],
"AGENOILLIER":["agenoillier", "agenouillier", "agenoiler", "agenoilliee", "agenoilliees", "agenoilliez", "agenoille", "agenoillent", "agenoillierent"],
"AGNEL":["aignel", "agnel", "agneau", "aigniax"],
"AGNELET":["aignelet", "agnelet"],
"AGREER":["agreer", "agréer", "agree"],
"AGREVAIN":["Agravains", "Agrevains"],
"AGREVER":["agrever", "agrevee"],
"ANGUINGUERON":["Aguinguerrons", "Anguinguerron", "Anguinguerrons"],
"AGU":["aigu", "agu", "aguz"],
"AGUISEL":["Aguisel", "Aguiflez"],
"AGUILLE":["aguille", "aiguille"],
"AGUISIER":["aguisier", "aiguisier", "agucer", "aiguiser", "aguisent"],
"AHAN":["ahan"],
"AHANER":["ahaner", "ahane"],
"AIDIER":["eidier", "aidier", "aider", "haidier", "aïde", "aïe", "aidiez", "aiderai", "eideras", "aidera", "eidera", "eiderons", "aideroit", "eideroit", "eidons", "eidast", "aïst", "aït"],
"ÄIE1":["aïde", "äie", "aide", "aïdes"],
"AIGLE":["egle", "aigle"],
"AIGUE":["eve", "aigue", "eau"],
"ÄIR":["aïr"],
"AIR1":["er", "air", "airs"],
"ÄIRIER":["aïrer", "äirier", "airier", "aïré", "aïre", "aïrié"],
"AINZNÉ":["ainzné", "ainznee", "ainznez", "ainsné"],
"AIS":["ais", "eis", "es"],
"AISE":["aeise", "aise", "eise", "eises", "eisse"],
"AIGRE1":["aigre", "egre", "aigres"],
"AIL":["ail"],
"AISSELE2":["aisselle", "eissele", "essele"],
"AIUELE":["aiole", "aiuele", "aele", "aïeul"],
"AJORNER":["ajurner", "ajourner", "ajorner", "ajorné", "ajornez", "ajorne", "ajorna"],
"AJOSTER":["ajuster", "ajoter", "ajoster", "ajoste"],
"ALEGIER1":["alegier", "aleger", "alegié", "alegiee", "aliege"],
"ALEINE":["aleine", "haleine", "alainne", "alainnes", "aleinne"],
"ALAITIER":["alaiter", "alaitier", "allaiter", "aleitanz"],
"ALASCHIER":["alaschier", "alasche"],
"ALEE":["alee"],
"ALEGEMENT":["alegemant", "alegmement"],
"ALEMELE":["alemele", "alumelle"],
"ALENER":["alener", "aleiner", "alainne"],
"ALEMAINGNE":["Alemaine", "Alemaigne", "Alemaingne"],
"ALER":["aler", "alers", "alant", "alé", "alees", "alez", "alee", "vois", "vas", "va", "vait", "vet", "alomes", "alons", "alez", "vont", "aloie", "aloit", "alions", "aliens", "aleiez", "aloient", "alai", "alas", "ala", "alastes", "alerent", "irai", "iras", "ira", "irons", "eroiz", "irez", "iroiz", "iront", "iroie", "iroit", "iriens", "iriez", "iroient", "va", "alons", "alez", "aille", "voise", "ailles", "voises", "aille", "aut", "voise", "voist", "ailliez", "aillent", "voisent", "alasse", "alasses", "alast", "alessiens", "alesiez", "alassent", "alessient"],
"ALEMANT":["Alemant"],
"ALERÏON":["alerion", "alerïon", "alerions"],
"ALËURE":[" alëure", "alure"],
"ALEVER":["alever", "eslever", "alevee"],
"ALEXANDRIN":["alixandrin", "alisandrin"],
"ALIXANDRE1":["Alixandre", "Alixandres"],
"ALIXANDRE2":["Alixandre", "Alixandres"],
"ALIXANDRE3":["Alixandre", "Alixandres"],
"ALIXANDRE4":["Alixandre"],
"ALIE":["alie", "alue"],
"ALIER":["Alier", "Aliers"],
"ALIIER2":["aliier", "allier", "alïent"],
"ALIS":["Alis", "Alys"],
"ALÖE1":["aloue", "alöe", "aloe"],
"ALÖÉ":["alo", "alöé", "eloes", "aloès", "aloé"],
"ALÖER2":["aloiier", "alöer", "aloer", "alouer", "aluer", "allouer"],
"ALÖETE":["aloete", "alöete", "alouet", "alouette"],
"ALOIGNE":["aloigne", "alonge"],
"ALOIGNIER":["aloignier", "esloigner", "aloigniees"],
"ALOSER":["aloser", "alosez", "alose"],
"ALUE2":["alue", "alude"],
"ALUÈ":["alué", "aluè", "aluef", "alleu"],
"ALUMER":["allumer", "alumer", "alumé", "alumez", "alume", "alument", "aluma"],
"AMANT":["amant", "amanz"],
"AMASSER":["amasser", "amassé", "amassee", "amassees", "amassez", "amasse", "amassent", "amassa"],
"AMAUGIN":["Amaugin", "Amauguins"],
"AMBLER":["anbler", "ambler", "anblant", "anbloit", "anblast"],
"AMBLËURE":["anblëure", " ambleure", "amblure"],
"AME":["alme", "ame", "ames"],
"AMENDE1":["amande", "amende"],
"AMENDEMENT":["amandement", "amendement"],
"AMENDER":["amender", "amander", "amandé", "amandee", "amandez", "amant", "amande", "amanda", "amanderent", "amanderai", "amanderoie", "amandez", "amant", "amant"],
"AMEÇON":["ameçon", "esmeçon", "amesson", "hameçon"],
"AMEMBRER":["amanbrer", "amembrer", "amanbree"],
"AMENER":["amener", "amené", "amenee", "amenez", "amain", "amaing", "amainne", "amenomes", "amainnent", "amenoit", "amenoient", "amenai", "amena", "amanrai", "amanra", "amanroiz", "amanroie", "amanroit", "amainne", "amaint", "ameigniez", "amenassent"],
"AMENTEVOIR":["amentevoir", "amentiver", "amanteü", "amenteü", "amantui"],
"AMENUISIER":["amenuisier", "amenuser", "amenuisiee"],
"AMËOR":["ameor", "amëor", "amerres"],
"AMER1":["amer", "aimer", "amé", "amee", "amez", "aim", "ain", "aimme", "ainme", "amez", "aiment", "ainment", "amoie", "amoit", "ameiez", "amoient", "amai", "ama", "amerent", "amerai", "amera", "ameroie", "ameroit", "amez", "aint", "amoiz", "amasse", "amast", "amessiez"],
"AMER2":["amer", "amere", "amers"],
"AMERTUME":["amertume", "anertume"],
"AMETISTE":[" ametite", "ametiste", "améthyste", "ametistes"],
"AMETRE":["ametre", "amettre", "admettre", "amis", "amise", "ametez", "ametoient", "amist"],
"AMI":["ami", "amie", "amies", "amis"],
"AMÏABLE":["amïable", "amiable"],
"AMÏABLEMENT":["amïablement", "amiablemant"],
"AMIENS":[" Amiens"],
"AMISTIÉ":["amistié", "amistiee", "amistiez", "amitié"],
"AMONESTEMENT":["amonestemant", "amonestement", "admonestement"],
"AMONESTER":["amonester", "admonester", "amoneste", "amonesté"],
"AMOR":["amur", "amour", "amor", "amors"],
"AMOROIN":["amoronge", "amoroin"],
"AMOROS":["amoreus", "amoros", "amouros", "amerus"],
"AMORTER":["amorter", "amortir", "amortee"],
"AMPLE":["ample", "anple", "emple", "emples"],
"AMÜIR":["amuïr", "amuir", "amuiz"],
"AMUSER":["amuser", "amusé", "amusee"],
"AN":["an", "anz"],
"ANCELE":["ancelle", "ancele"],
"ANCESSERIE":["ancesserie"],
"ANCESSOR":["ancesur", "ancêtre", "ancessor", "ancessors"],
"ANEL1":["anneau", "anel", "enel", "eniax"],
"ANEL2":["annel", "annuel", "anel"],
"ANCIIEN":["anciien", "ancien", "anciene", "ancienes", "anciens"],
"ANCRE":["ancre", "encre"],
"ANE":["ane"],
"ANEE":["anee", "année", "annee"],
"ANELET":["annelet", "anelet"],
"ANET":["Anet", "Anez"],
"ANGARDE":["angarde", "engarde"],
"ANGEVIN":["angevin"],
"ANGLOIS":["Anglois", "engleis", "einglois", "Einglois"],
"ANGLE":["angle", "engle", "engles"],
"ANGLETERRE":["Angleterre", "Eingleterre", "Engleterre"],
"ANGELE":["angele", "ange", "anges", "enge", "enges"],
"ANJO":["Anjo"],
"ANGOISSE":["anguisse", "angoisse", "angoisses", "engoisse"],
"ANGOISSIER":["anguissier", "angoissier", "angoissiez", "angoisse", "engoisse", "angoissiez", "angoissent", "angoissoient", "angoissierent"],
"ANGOISSOS":["angoisseux", "angoissos", "angoisseus", "angoisseuse", "angoissos"],
"ANGRES":["Angres", "Angrés"],
"ANTIOCHE":["Antioiche", "Antioche"],
"ANTIPODES":["Antipodes", "Antipodés"],
"ANUITIER":["anuiter", "anuitier", "anuitié"],
"AORER2":["adorer", "aorer", "aorez", "aore", "aora", "aorerai"],
"AOST":["aust", "août", "aost", "aoust"],
"AOVRER":["aovrer", "aoevrent"],
"AOVRIR":["aovrir", "aoverte"],
"APAIIER":["apaiier", "apaier", "apaiez", "apaiez"],
"APAISIER":["apeisier", "apaisier", "apeser", "apeisiez", "apeise"],
"APANTOISIER":["apantoisier", "apantoisant"],
"APAREIL":["aparoil", "apareil"],
"APAREILLIER1":["apareillier", "aparellier", "apareillié", "apareilliee", "apareilliees", "apareillies", "apareilliez", "aparellié", "aparelliee", "aparelliees", "aparelliez", "aparoille", "aparelliez", "aparoillent", "apareilla", "aparellierent", "aparaut"],
"APAREILLIER2":["apareillier", "aparoille", "apareilloit"],
"APARLER":["aparler", "aparole", "aparolent", "aparloient", "aparla", "aparlast"],
"APAROIR":["aparoir", "aparanz", "aperent", "aparut", "aparurent", "aparra", "apeire", "apere"],
"APARTENIR":["apurtenir", "apartenir", "apartient", "apartenist"],
"APEL":["appel", "apel"],
"APELER":["apeler", "apelé", "apelee", "apelez", "apel", "apele", "apelez", "apelent", "apeloie", "apeloit", "apeloient", "apela", "apelastes", "apelerent", "apelerai", "apeleroie", "apelez", "apialt", "apiaut", "apelast"],
"APENDRE":["apandre", "apendre", "apant"],
"APENSER":["apenser", "apanser", "apansee", "apanssé", "apanse", "apansse", "apansoient", "apansa"],
"APERCEVOIR":["apercevoir", "aparcevoir", "aparcevant", "aparcevanz", "aparceü", "aparceüe", "aparceüz", "aparçoit", "aparçui", "aparçut", "aparcevront", "aparçoive", "aparceüssent", "aparceüst"],
"APERT1":["apert", "aperte"],
"APERT2":["apert", "aperte", "aperz"],
"APERTEMENT":["apertement", "apertemant"],
"APETICIER2":["apetiser", "apeticier", "apetisser", "apetise"],
"APLAIGNIER":[" apleignier", "aplaner", "aplanier", "aplaigner", "aplaignier", "aplaigne", "aplaignié"],
"APOIIER":["apuiier", " apoiier", "apuier", "apoier", "apoié", "apoiee", "apoiees", "apoiez", "apuie", "apoia"],
"APOINDRE":["apoindre", "apoint"],
"APOINTIER2":[" apointier", "apoindre", "apointe"],
"APONDRE":["apondre", "aponde"],
"APORTER":["aporter", "aporters", "aporté", "aportee", "aportees", "aportez", "aport", "aporte", "aportent", "aportoit", "aportoient", "aporta", "aporterent", "aportera", "aporteront", "aporteroit", "aporte", "aportez", "aport", "aportast", "aportassent"],
"APOSTLE":["apostre", "apostle", "apôtre", "apostre", "apostres"],
"APOVRIR":["apovrir", "empovrir", "apovri"],
"APRENDRE":["apprendre", "aprenez", "apraingne", "apreigne", "apreïsses", "apraigniez", "apreingnent", "apreïst", "apanre", "aprandre", "aprendre", "apris", "aprise", "apraing", "aprant", "apris", "aprist", "aprandra", "aprendra", "aprendront"],
"APRENTIZ":["aprantiz", "aprentiz", "aprentic", "aprentif", "apprentiz", "apprenti"],
"APRESTER":["aprester", "apprêter", "aprester", "apresté", "aprestez", "apreste", "aprestoit", "aprestoient", "aprestez"],
"APRESSER":["apresser", "appresser", "apressent"],
"APRISON":["aprison"],
"APROCHIER":["aprochier", "aproichier", "apruichier", "apruichant", "aprochié", "aprochiee", "aprochiez", "aproches", "aproche", "aproiche", "aprochent", "aprocheiez", "aprochoient", "aprocha", "aprocherent", "aprochierent", "aprocheras", "aprocheront", "aprochiez"],
"APROISMIER":["aprismier", "aproismier", "aprismer", "aprismant"],
"AQUERRE":["aquerir", "aquerre", "aquerra", "aquerroie"],
"AQUITER":["acquitter", "acquiter", "aquiter", "aquitee", "aquitez", "aquit", "aquite"],
"ARRABE":["arabe", "Arrabe"],
"ARABI":["arabi", "arrabi"],
"ARABÏOIS":["arabois", "arabeis", "arabïois", "arrabiois"],
"ARRAGON":["Aragon", "Arragon"],
"ARAIN":["airin", "arain"],
"ARAISNE":["araisne", "areisne", "aresne"],
"ARAISNIER":["aresnier", " araisnier", "arener", "araisner", "arraisonner", "aresniee", "aresne", "areisone", "aresne", "areisonez", "aresnoit", "areisonas", "areisnera"],
"ARBALESTE":[" arblaste", "arbalète", "arbaleste", "arbalestes"],
"ARBALESTEE":[" arbalétée", "arbalestee", "arbalestees"],
"ARAMIR":["arramir", "aramir", "arramie"],
"ARBALESTIER":["arbalestier", " arbalestier", "arbalestriers"],
"ARBRE":["arbre", "arbres", "aubre"],
"ARC":["arc", "ars"],
"ARCEVESQUE":["arceveske", "archevêque", "arcevesque", "arcevesques"],
"ARCHE2":["arke", "arche"],
"ARCHIEE":["archée", "archiee"],
"ARCHAL":["archal"],
"ARÇON":["arçun", "arçon", "arçons", "arçonz"],
"ARCHIER":["archier", "archiers"],
"ARÇONER":["arçoner", "arçonner", "arçone", "arçonent"],
"ARDOISE":["atoise", "adoise", "ardoise"],
"ARDRE":["ardoir", "ardre", "arder", "ardant", "ardanz", "ars", "arse", "art", "ardent", "ardoit", "ardoient", "arde", "ardent"],
"AREE":["aree", "arees"],
"AREEEMENT":["areer", "areement", "arrément", "arëaumant"],
"AREINE":["areine", "araine", "areinne"],
"ARER":["arer", "arees", "erent"],
"ARES":["Ares", "Arés"],
"ARESNER":[" aresner", "aresné"],
"AREST":["arest"],
"ARESTER":["arester", "aresté", "arestee", "arestez", "areste", "arestent", "arestoit", "arestas", "aresta", "arestut", "aresterent", "aresterons", "aresteroie", "arest", "arestast"],
"ARESTUEL":["arestoel", "arestuel"],
"ARGENT":["arjant", "argent", "argenz"],
"ARGONE":["Argone"],
"ARGÜER":["arguër", "arguer", "argüe"],
"ARISMETIQUE":["arimetique", "arismetique", "aritmetike", " arithmétique"],
"ARIVER1":["ariver", "arriver", "arivé", "arivez"],
"ARMAIRE":["aumeire", "armaire", "armoire", "aumaire"],
"ARMER":["armer", "armé", "armee", "armez", "arme", "arment", "armoient", "arma", "armerent", "armerai", "armeront", "armeroit", "armez", "armassent"],
"ARMËURE":["armëure", "armeure", "armeüres"],
"ARMONIE":["armonie", "armonies"],
"ARONDE":["arunde", "aronde", "arondres"],
"AROSER1":["aroser", "aruser", "arosé"],
"ARRACHIER":["arrachier", "aracer", "arracher", "arachier", "arachié", "arachiee", "arachiez", "araiches", "arache"],
"ART":["art", "arx", "arz"],
"AROTER2":["aroter", "aruter", "arote", "arouter", "aroterent"],
"ARPENT":["arpent", "arpant", "arpanz"],
"ARTETIQUE":["artetique", "arcetique"],
"ARTU":["Artu", "Artus"],
"ASNE":["asne"],
"ASPRE":["aspre", "âpre", "aspres"],
"ASPREMENT":["asprement", "aspremant"],
"ASPROIIER":["aspreiier", "asproiier", "asproier", "asproie"],
"ASSALIR":["assaillir", "assalir", "asaillir", "assaillir", "asailli", "asaillie", "asailliz", "assailli", "asauz", "asalt", "asaut", "assaut", "asaillent", "assaillent", "asailli", "assaillons", "asaille", "assaille"],
"ASSAUT":["assault", "asaut", "asauz", "assalt", "assaut", "assauz"],
"ASSEMBLEE":["assemblee", "asanblee", "assanblee"],
"ASSEMBLER":["assembler", "asembler", "asanbler", "assanbler", "asanblé", "asanblee", "asanblez", "assanblé", "assanblee", "assanblees", "assanblez", "asanble", "assanble", "asanblent", "assanblent", "asanblai", "asanbla", "assanbla", "asanblerai", "asanbleront", "assanbleroient", "assanblast"],
"ASSENER":["assener", "asener", "asené", "asenez", "assenee", "asane", "asanne", "asene", "asenent", "asena"],
"ASSËOIR":["aseoir", "asseoir", "asis", "asise", "asises", "assis", "assise", "assises", "asiet", "asieent", "asis", "asist", "assist", "asistrent", "asseez", "asieent", "aseïsse", "aseïst"],
"ASSERIR":[" asserir", "aserir", "aseri"],
"ASSËUR":["sëur", "asseur", "aseür", "asseür"],
"ASSËURER":[" asseurer", "aseurer", "aseürer", "asseürer", "aseüré", "aseüree", "asseüré", "asseürees", "asseürez", "asseür", "aseüres", "aseüre", "aseürent", "aseürerent", "asseürerons", "aseüreroiz"],
"ASSOAGIER":["assoagier", "assouagier", "asuager", " assouager", "asoage"],
"ASTELE":["astele", "astelle", "estele", "esteles"],
"ASTRENOMIE":["astrenomie", "astronomie"],
"ASSOMER1":["assomer", "assommer", "essomez"],
"ASSOMER2":["assomer", "asomer", "asome"],
"ASUR":["asur", "azur"],
"ATACHIER2":["atachier", "atacher", "atachiee", "atachiez", "atache"],
"ATAINDRE":["atteindre", "ataindre", "ateindre", "ateignant", "ataint", "atainte", "atainz", "ataing", "atainz", "ataint", "ateint", "ataignent", "ateignent", "ateingnent", "ateignoit", "atains", "ateindrai", "ateindroiz", "ateigne"],
"ATHENES":["Athenes"],
"ATÄINE":["anhatine", "atahine", "ataïne", "ateïne"],
"ATALENTER":["atalanter", "atalenter", "entalenter", "atalante", "atalant"],
"ATARDER":["attarder", "atarder", "atardant"],
"ATELER":["ateler", "atler", "atelez"],
"ATEMPRER":["atanprer", " atemprer", "atranprer", "atremprez"],
"ATENDRE":["atandre", "atandres", "atendre", "atendanz", "atandu", "atandue", "atendu", "atant", "atandent", "atendent", "atandoit", "atendoit", "atandoient", "atendi", "atandrai", "atendrai", "atandras", "atandra", "atendra", "atandrons", "atandroie", "atandez", "atande", "atende"],
"ATENDUE":["attendue", "atandue", "atendue"],
"ATENTE":["atante", "atente"],
"ATERRER":["aterrer", "atterrer", "aterré"],
"ATOCHIER":["atochier", "atucher", "atoichier", "atochié", "atoches", "atoche", "atocheroies", "atochiez", "atochast"],
"ATOR":["atour", "ator"],
"ATILLIER":["atillier", "atirer", "atillier", "atillent"],
"ATIRIER":["atirer", "atirier", "atirié", "atiriee", "atire"],
"ATISIER":["atisier", "atiser", "attiser", "atise"],
"ATORNEMENT":["atornement", "aturnement", "atournement", "atornemant"],
"ATORNER":["atourner", "aturner", "atorner", "atorné", "atornee", "atornees", "atornez", "ator", "atorne", "atornent", "atornoit", "atorna", "atornerent", "atornez", "atort", "atourt"],
"ATRAIRE":["atreire", "atraire", "atreite", "atrete", "atret", "atraient"],
"AUBAGU":["aubagu"],
"AUBE3":["albe", "aube"],
"AUCUBE":["aucube", "aucubes"],
"ATRAIT":["atrait", "attrait", "atret"],
"ATROPELER":[" atropeler", "attroupeler", "atropelerent"],
"AUDÏENCE":["audïence", "audiance", "audience"],
"ÄUNEE":["aunee", "aünee"],
"AUNER":["auner", "alner", "auné", "aunera"],
"AUFRIQUE":["Aufrique"],
"AUMARIE":[" Aumarie"],
"AUMOSNE":["almosne", "aumone", "aumosne"],
"AUMOSNIERE":["almosniere", "aumosnere", "aumosniere"],
"AUNE2":["aune", "aunes"],
"AUTEL2":["auter", "autel"],
"AUTREMENT":["autrement", "altremant", "autremant"],
"ÄUNER":["aüner", "auner", "aüné", "aünee", "aüne"],
"ASSALON":["Assalon", "Ausalon"],
"AUSSIMENT":[" aussiment", "alsiment", "ausimant"],
"AUTRESIMENT":["autresiment", "autresimant"],
"AVALEE":["avalée", "avalee"],
"AVALER":["avaler", "avalant", "avalé", "avalee", "avalez", "avale", "avaloit", "avaloient", "avala", "avalerent", "avalez"],
"AVALON":["Avalon", "Avalons"],
"AVANCIER":["avancer", "avancier", "avanciee", "avance", "avança", "avancerai"],
"AVANCIR":["avancir", "avencist"],
"AVANTAGE":["avantage", "aventage"],
"AVANTPIÉ":["avantpié", "avantpied", "avanpié"],
"AVARICE":["avarice"],
"AVEINE":[" aveine", "avoine", "avene", "avainne", "aveinne", "aveinnes", "avoinne"],
"AVENANMENT":["avenanment", "avenantment", "avenanmant"],
"AVENEMENT":["avenemant", "avenement"],
"AVENIR":["avenir", "avenant", "avenanz", "avenu", "avenue", "avenues", "avient", "avienent", "avenoit", "avenoient", "avint", "avindrent", "avandra", "avendra", "avenra", "avandront", "avandroit", "avaigne", "aveigne", "aveingne", "aviegne", "avaingnent", "avenist"],
"AVENTURE":["avanture", "avantures", "aventure", "aventures"],
"AVENTUROS":["avantureus", "aventuros", "aventurous", "avantureuse"],
"AVER":["avare", "aver", "avere"],
"AVERIR":["averir", "averer", "avérir", "averi"],
"AVERSAIRE":["averseire", "adversaire aversaire"],
"AVERSIER":["adverser", "aversier"],
"AVESPRER":["avesprer"],
"AVILENIR":["avilenir", "avileni"],
"AVILLIER":["aviler", "avillier", "avilliees", "aville", "avilla"],
"AVIRON2":["avirun", "aviron"],
"AVIRONER":["avironer", " enviruner", "avironner", "avirone"],
"AVIS":["avis"],
"AVISER":["aviser", "avise", "avisast"],
"AVÖÉ":["avöé", "avoet", "avoué", "avoé"],
"AVOGLER":["avuglé", "avogler", "aveugler", "avuglé", "avuglee", "avuglez"],
"AVOIIER":["aveiier", "avoiier", "avoyer", "aveier", "avoié", "avoiee", "avoiees", "avoiez", "avoie", "avea", "avoit"],
"AVOIR":["avoir", "avoirs", "eü", "eüe", "aüz", "eües", "eüz", "ai", "ei", "as", "a", "avomes", "avons", "avez", "ont", "avoie", "avoies", "avoit", "aveiez", "aviez", "avoient", "oi", "eüs", "ot", "out", "eüstes", "orent", "avrai", "avrei", "avras", "avra", "avromes", "avrons", "avrez", "avrez", "avroiz", "avront", "avroie", "avroies", "avroit", "avriens", "avreiez", "avriez", "avroient", "aies", "aiez", "aie", "aies", "ait", "eit", "aiens", "aiez", "aient", "eüsse", "aüsses", "eüsses", "aüst", "eüst", "aüssiez", "eüssiez", "eüssent"],
"AVOUTRE":["avuiltre", "avoutre", "Avoutre"],
"AVRIL":[" avril", "avrix"],
"AVUGLE":["aveugle", "avogle", "avugle", "avugles"],
"BÄAILLIER":["baaillier", "bäaillier", "baaillié"],
"BACON":["bacon", "bacons"],
"BADE":["Bade"],
"BADEMAGU":["Bademagu", "Bademaguz"],
"BADES":["bade", "bades"],
"BABILOINE":["Babiloine"],
"BACHELER":["bacheler", "bachelers"],
"BACIN":["bassin", "bacin", "bacins"],
"BAI":[" bai", "bai"],
"BAILE":["baille", "baile", "bailes"],
"BAILLIE":["baillie"],
"BAIGNIER":["beignier", "baignier", "baigne", "baignent", "baignoit", "baingnierent"],
"BAILLIER":["bailler", "baillier", "baillié", "bailliee", "bailliees", "bailliez", "bail", "bailles", "baille", "bailliez", "baillent", "bailloit", "bailla", "baillerai", "bailleroiz", "bailleront", "baille", "bailliez", "baillessiez"],
"BAIN":["bain", "baing", "bainz"],
"BAISIER":["baisier", "beisier", "beisiers", "beisant", "beisié", "beisiee", "beises", "beise", "beisent", "beisoit", "beisa", "beiserai", "beiseré", "best", "beise", "beisast"],
"BAISSIER":["beissier", "baisser", "beissié", "beissiee", "bessié", "beisse", "beise", "beissent", "baissoient"],
"BALANCIER":["balancier", "balancer", "balance"],
"BAN1":["ban", "banc"],
"BAN2":["Ban", "Bans"],
"BANC":["banc", "bans"],
"BANDON":["bandon", "bandun"],
"BANIERE":["baner", "bannière", "baniere", "banieres"],
"BANIR":["banir", "bani"],
"BATISTE":["Baptiste"],
"BARAT":["barat"],
"BARATE":["barate"],
"BARBACANE":["barbecan", "barbacane", "barbaquane"],
"BARBE":[" barbe", "barbes"],
"BARBÉ":["barbé", "barbez"],
"BARGE":["barge", "barges"],
"BARIL":["baril", "barel", "barrilz"],
"BARNAGE":["barnage", "barnages"],
"BARON":["baron", "barons", "ber"],
"BARBELÉ":["barbelé", "barbelees"],
"BARBÏOLETE":["barbiolete", "barbïolete", "berbioletes"],
"BARGAIGNIER":["barguignier", "bargaignier", "bargainer"],
"BARONAILLE":["baronaille"],
"BARONIE":["baronie"],
"BARRE":["barre", "barres"],
"BARRER":["barrer", "barré", "barrez"],
"BARUT":["Barut"],
"BAS":["bas", "basse", "basses"],
"BASME":["baume", "basme"],
"BASTIR":["bastir", "basti", "bastie"],
"BASTON":["baston", "bastons"],
"BASTONET":["bastonet"],
"BATAILLE":["bataille", "batailles"],
"BATAILLIER1":["bataillier", "bateillant"],
"BATEL2":["batel"],
"BATESME":[" batesme", "baptesme", "baptême"],
"BATISTERE":["baptestire", "batistere"],
"BATRE":["batre", "batant", "batanz", "batu", "batue", "batuz", "bat", "batent", "batoit", "bat"],
"BAUCENC":["bauçant", "bauçan", "baucenc", "baucent", "baucenz"],
"BAULE":["baule", "baules"],
"BAUT":["baut", "bald", "baud", "baude", "bauz"],
"BELREPEIRE":["Belrepeire", "Belrepaire", "Biaurepaire", "Biaurepere"],
"BEC":["bek", "bec"],
"BEDOIIER":["Bedoiier", "Bedoiers"],
"BEHORDER":["behorder"],
"BËER":["bëer", "beer", "béer", "baer", "bahé", "bee", "baoit", "baast"],
"BEL":["beau", "bel", "bele", "beles", "biau", "biaus", "biaux", "biax"],
"BELEMENT":["belement", "belemant"],
"BESLIC":["bellic", "beslic", "belif", "belinc", "bernic"],
"BENDE":["bende", "bande", "bandes"],
"BENDER":["bander", "bender", "bandee", "bandees"],
"BENËIR":["beneïr", "beneistre", "benedicere", "benëir", "bénir", "beneoit", "beneoite", "beneoiz", "beneïssoient", "beneï", "beneïe"],
"BERSER":["berser"],
"BERTE":["Berte", "Bertain"],
"BERTRAN":["Bertran", "Bertranz"],
"BESANT":["besan", "besant", "besanz"],
"BESCUIT":["besquit", "bescuit"],
"BESOIGNE":["besogne", "besoigne", "besoingne", "besoingnera"],
"BESOING":["besoin", "besoig", "besoing", "besoinz"],
"BESTE":["bête", "beste", "bestes"],
"BESTÏAL":["bestïal", "bestial", "bestiax"],
"BESTORNER":["bestorner", "bistourner", "bestornee"],
"BETER2":["beter", "béter2", "betee"],
"BETIR":["betir", "bétir", "betist"],
"BEVRAGE":["beverage", "breuvage", "bevrage"],
"BIAUTÉ":["biauté", "biautez"],
"BIAUVEZ":[" Biauvez"],
"BIEN":["bien", "biens"],
"BIENVENUE":["bienvenuz", "bienvenue"],
"BIERE":["bere", "biere", "bieres"],
"BIEVRE":["bevere", "bievre"],
"BILIS":["Bilis", "Bylis"],
"BILLE1":["bille"],
"BLANC":["blanc", "blanche", "blanches", "blans"],
"BLANCHEFLOR":["Belissant", "Blancheflor"],
"BIS":["bis", "bise", "bises"],
"BISSE":["bisse", "biche", "biches"],
"BLANDIR":["blandir", "blandist"],
"BLASME":["blasme", "blasmes"],
"BLASMER":["blasmer", "blasme"],
"BLASON":["blason", "blazon", "blazons"],
"BLÉ":["blet", "blé", "blez"],
"BLECËURE":["blecëure", "bleceure", "bleceüres"],
"BLECIER":["blecier", "blescer", "blesser", "blecié", "bleciee", "bleciez", "blece", "blesce", "bleça"],
"BRÏEN":["Brïen", "Bliant", "Blianz"],
"BLÏAUT":["blïaut", "bliaut", "bliauz", "bliax"],
"BLIOBLEHERIS":["Bliobleheris", "Blioberis"],
"BLO":["bleu", "blo", "bloe", "bloes"],
"BLONT":["blunt", "blonc", "blonde", "blondes", "blont"],
"BOCE1":["bosse", "boce"],
"BOCEL3":[" bocel"],
"BOCHE":["bouche", "boche", "boches", "boiche"],
"BOCHETE":["bouchete", "bouchette", "bochete"],
"BOCLE":["bocle", "bocles", "boucle"],
"BOCLÉ":["bouclé", "boclé"],
"BOCLETE":["bouclette", "boclete"],
"BOÇOIIER":["boceiier", "boçoiier", "bocier", "bocer", "bossoier", "bosser", "bossier", "boceier"],
"BOÇU":["bossu", "boçu", "boçue", "boçuz"],
"BÖELE":["böele", "boele"],
"BOFU":["bofu"],
"BOIS":["bois"],
"BOISE2":["boise"],
"BOISIER1":["boisier", "boiser", "boisent", "boisa"],
"BOISTE":["boîte", "boiste"],
"BOIVRE":["beivre", "boire", "boivre", "boivres", "beü", "beüe", "boit", "bevez", "bevoit", "bevoient", "bui", "but", "beüstes", "burent", "bevrai", "bevroiz", "boive"],
"BOLE2":["boule", "bole"],
"BOLIR":["boillir", "bolir", "bouillir", "buillir", "boillant", "bolt", "bout", "bolent"],
"BON":["ben", "boen", "boene", "boenes", "boens", "bon", "bone", "bones", "bons", "buen", "buens"],
"BONE":["bosne", "borne", "bone"],
"BONEMENT":["bonement", "bonnement", "boenemant", "bonemant"],
"BONET":["bonnet", "bonet"],
"BONTÉ":["bonté", "bontez"],
"BOQUERANT":["boquerant", "boqueranz"],
"BORC":["burc", "burg", "bourg", "borc", "bors"],
"BORDE1":["borde"],
"BORGNE":["borgne", "borne", "borgnes"],
"BORJOIS":["burgeis", "bourgeois", "borjois"],
"BORREL":["borrel", "bourel", "borriax"],
"BOSCHAGE":["boscage", "boschage", "boschaige"],
"BOT1":["bout", "bot", "bous"],
"BOT2":["bot", "butte", "boz"],
"BOT4":["bot", "boz"],
"BOTEILLIER":["boteillier", "botiller", "botellier", "botelliers"],
"BOTER1":["boter", "bouter", "boté", "botee", "botez", "bote", "botent", "bota", "botast"],
"BOTON":["boton"],
"BOUSER":["bouser", "bousoit"],
"BRACHET":["brachet", "brachez"],
"BRACIEE":["braciee"],
"BOUZON":["bouzon", "boujon", "bozun", "bozon"],
"BOVIER":["bover", "bouvier", "bovier", "boviers"],
"BRABANÇON":["Breibançon", "Brabançon", "Brabançun"],
"BRACIER2":["bracier", "bracer", "brasser", "brace"],
"BRAIDIF":["breidif", "braidif"],
"BRAIT":["bret"],
"BRAIE":["braies", "braie"],
"BRAIER":["braiier", "brael", "braier"],
"BRANDIGAN":["Brandigan", "Brandiganz"],
"BRANDON":["brandon"],
"BRAIRE":["braidis", "braire", "breire"],
"BRANCHE":["branche", "branches"],
"BRANGIENS":["Brangiens"],
"BRAZ":["bras", "braz"],
"BRANDES":["Branles"],
"BRANT1":["branc", "brant", "branz"],
"BRÄON":["braon", "bräon", "braun", "braons"],
"BRAVAÏN":["Bravaïn", "Bravaïns"],
"BRETAINGNE":["Bretaigne", "Bretaingne", "Breteingne"],
"BRETESCHE":["bretache", "bretesche", "bretesches"],
"BRESE":["breise", "brese"],
"BRESIL2":["brasil", "bresil"],
"BRET":["bret", "brete", "brez"],
"BRETON":["Breton", "bretun", "breton", "bretons"],
"BRICOIGNE":["bricoingne", "bricoigne"],
"BRIÉMENT":["briefment", "brefment", "briément", "briemant"],
"BRISIER":["briser", "brisier", "brisant", "brisié", "brisiee", "brisiez", "brise", "brisent", "brisa", "brisera", "brist", "brit"],
"BRICON1":["bricon"],
"BRIÉBRAZ":["Briebraz"],
"BRIEF":["bref", "brief", "briés"],
"BRIVE":["brive"],
"BROCE":["brouce", "brosse", "broce"],
"BROCELIANDE":["Broceliande"],
"BROCHE":["broche"],
"BROCHIER":["brochier", "brocher", "brochié", "broche", "broiche", "brochent", "broichent"],
"BROIGNE":["broingne", "broine", "broigne"],
"BROSDER":["brosder", "brouder", "brosdé", "brosdee"],
"BRUIL1":["bruil", "broil", "breuil", "bruel"],
"BRUIANZ":["Bruianz"],
"BRUN":["brun", "brune", "bruns"],
"BRUIRE":["bruire", "bruiant", "bruianz", "bruit"],
"BRUIT":["bruit", "bruiz"],
"BRUNET":["brunet", "brunete", "brunez"],
"BRUNETE":["brunete", "brunette", "brunetes"],
"BRUNIR":["brunir", "burnir", "brunie", "bruniz"],
"BU":["bu"],
"BUCIFAL":["Bucifal", "Bucifax"],
"BUEF":["boef", "boeuf", "buef", "bués"],
"BUER":["buer"],
"BUFE":["buffe", "bufe", "bufë"],
"BUIRE1":["buire"],
"BUIRON1":["buiron", "buron"],
"BUISINE":["buisine", "busine", "buisines"],
"BUISSONOS":["boissoneus", "buissonos", "buissonneux", "buissuneus", " boissoneus"],
"BUSCHE":["bûche", "busche"],
"CACHET":["quachet", "cachet", "quachez"],
"CACIER":["quacier", "cacier", "quace"],
"CADOALANT":["Cadoalant", "Cadiolanz", "Caroduanz"],
"CADOC":["Cadoc"],
"CALOGRENANT":["Calogrenant", "Calogrenanz", "Qualogrenant", "Qualogrenanz"],
"CANDIE":["Candie", "Quandie"],
"CADRET":["Cadret"],
"CAILLE":["caille", "quaille"],
"CANELE":["canele", "cannelle", "quenele"],
"CANIVET":["canivet", "cnivet", "quanivet"],
"CANTORBIRE":["Quantorbire"],
"CAPADOCE":["Capadoce"],
"CARADIGAN":["Caradigan", "Quaradigan"],
"CARDUEL":["Carduel", "Quaraduel"],
"CARLION":["Carlion"],
"CARREL":["carrel", "carreau", "quarrel", "quarriax"],
"CARNANT":["Carnant"],
"CAROLE":["carole", "queroles"],
"CAROLER":["caroler", "querolant", "querolent"],
"CARREFOR":["quarrefor", "carrefor", "carrefour", "quarefur"],
"CAS2":["quas", "cas", "quasse"],
"CASSER":["casser", "quasser", "quassé", "quassees", "quassez", "quasse", "cassent", "quast"],
"CARRER":["carrer", "quarré", "quarree", "quarrees", "quarrez"],
"CARSENEFIDE":["Carsenefide", "Tarsenesyde"],
"CARTAGE":["Cartage", "Cartaige"],
"CARTIER":["quartier", "cartier", "cartiers", "quartiers"],
"CEINTUIR":["ceintur", "ceintuir", "ceinturs"],
"CAUSE":["cause", "quauses"],
"CAVERON":["Caveron", "Caverons"],
"CEINDRE":["çaindre", "ceindre", "ceinte", "ceinz", "ceint", "ceingnent", "ceigniez", "ceingne"],
"CEINTURE":["ceinture", "ceintures"],
"CEINTURETE":["ceinturette", "ceinturete"],
"CELEE1":["celée", "celee"],
"CELER1":["celer", "celers", "celé", "celee", "celez", "cele", "çoile", "celoit", "celot", "cela", "celerai", "celera", "celeront", "cele", "celasse"],
"CELEEMENT":["celeement", "celeemant"],
"CELER2":["celé", "cielé", "celee", "cielee"],
"CENDAL":["çandal", "cendal", "cendax"],
"CENDRE":["çandre", "cendre"],
"CEMBEL":["çanbel", "cembel", "cenbel"],
"CEMBELER":["çanbeler", "cembeler", "cenbeler", "cenbelant"],
"CENELE":["cenele", "cenelle"],
"CENER1":["cignier", "cener", "cingne"],
"CERCELE":["cercele", "cerceles"],
"CENGLE":["çaingle", "cengle", "sangle", "ceingles", "cengle", "cengles"],
"CERCELET":["cercelet"],
"CERCHIER":["cerchier", "cercher", "chercher", "cerchant", "cerchié", "cerche", "cerchast"],
"CENGLER":["cengler", "ceinglent"],
"CEPTRE":["septre", "ceptre", "ceptres"],
"CERCLE":["cercle"],
"CERT":["cert", "certe", "cerz"],
"CERCLER":["cercler", "cerclers"],
"CERF":["cer", "cerf", "cers"],
"CERTAIN":["certein", "certain", "certainne", "certains", "certeins"],
"CERTEMENT":["certement", "certemant"],
"CERTAINEMENT":["certainement", "certeinement", "certainnemant ", "certeinnemant ", "certemant ", "certenemant"],
"CERVEL":["cervel"],
"CERVELE":["cervele", "cervelle"],
"CERVIZ":[" cerviz"],
"CERVOISE":["cerveise", " cervoise"],
"CESEIRE":["Ceseire", "Cesaire"],
"CESAR":["Cesaré", "Cesar"],
"CESSER":["cesser", "cesse", "cessent"],
"CHACE":[" chace"],
"CHACËOR":["chaceor", "chaceors"],
"CHACIER":["chacier", "chacent", "chacié", "chaciee", "chaciez", "chaz", "chaces", "chace", "chacent", "chaça", "chaceront", "chaçast"],
"CHÄEINE":["chaaine", "chaene", "chäeine", "chaîne", "chaainne"],
"CHAISNE":["chasne", "chesne", "chaisne", "chêne", "chasnes"],
"CHAILLO":["chaillo", "caillou", "chaillot", "chailloz"],
"CHAINSE":["chainse", "cheinse", "chainses"],
"CHAINSIL":["cheinsil", "chainsil"],
"CHAITIVETÉ":["cheitiveté", "chaitiveté", "chétiveté", "chestiveté"],
"CHALANT":["chalan", "chalant"],
"CHALEMELE":[" chalemele", "chalemelle", "chalemeles"],
"CHALEMELER":[" chalemeler", "chalemele"],
"CHAITIF":["chaitif", "chétif", "cheitif", "cheitis", "cheitive", "cheitives", "chestive"],
"CHALOIR":["chaloir", "chaler", "chalt", "chaut", "chaloit", "chalut", "chaille", "chausist", "chaussist"],
"CHALONGE":["chalenge", "chalonge"],
"CHALONGIER":["chalur", "chalor", "chalors"],
"CHAMBERIERE":["chamberiere", "chambriere", "chanberiere"],
"CHAMBERLENC":["chanbrelain", "chamberlenc", "chambellan", "chanberlains", "chamberlein"],
"CHAMBRETE":["chambrete", "chanbrete"],
"CHAMOIZ":["quamois", "chamois", "camois", "quamois"],
"CHAMBRE":["chambre", "chanbre", "chanbres"],
"CHAMPAGNE":["chanpaingne", "champagne", "campagne"],
"CHANPAINGNE":["Chanpaingne", "Chanpaigne"],
"CHAMOISSIER":["quamoissié", "chamoisier", "chamoiser", "quamoissiez"],
"CHAMP":["champ", "chanp", "chans"],
"CHAMPAINE":["canpane", "champaine", "quanpanes"],
"CHAMPCHËU":["champchëu", "champcheu", "chanpcheü", "chanpcheüz"],
"CHANPGUIN":["Chanpguin"],
"CHAMPÏON":["chanpion", "champïon", "champion", "champiun"],
"CHAMPIR":["chanpir", "champir", "chanpiront", "chanpisse"],
"CHANDELIER1":["chandeler", "chandelier", "chandeliers"],
"CHANDOILE":["chandoille", "chandele", "chandoile", "chandoiles"],
"CHANCEL":["chancel"],
"CHANCELER":["chanceler", "chancele", "chancelot"],
"CHANÇON":["chançon", "chançun", "chanson", "chançons"],
"CHANEVAZ":["chanevaz", " chanevas", "canevas", "chenevaz"],
"CHANGE":["change", "changes"],
"CHANGËOR":["changëor", "changeur", "changierres", "changeor"],
"CHANGIER":["changer", "changier", "changié", "changiee", "changiez", "change", "changiez", "chanjoit", "chanjoient", "chanja", "changerai", "changera", "chanjons", "changiez"],
"CHANOLE":["chanole", "chenole"],
"CHANT2":["chant", "chanz"],
"CHANTER":["chanter", "chantant", "chanté", "chantee", "chante", "chantent", "chantoit", "chantoient", "chanta", " chantassent"],
"CHAPE":["chape", "chapes"],
"CHANVRE":["chanve", "chanvre"],
"CHAPELAIN":["chapelain", "chapelains"],
"CHAPELE":["chapele", "chapelle"],
"CHAPEL2":["chapel", "chapeau", "chapele"],
"CHAPELIER1":["chapelier", "chapeler"],
"CHAPERON":["chaperon", "chaperons"],
"CHAPLE":["chaple", "chaples"],
"CHAPLER":["chapler", "chapeler", " chaple"],
"CHAPLËIZ":["capleiz", "chaplis", "chapleïz"],
"CHAR1":["char", "chars"],
"CHAR2":["char", "charz"],
"CHAPON":["chapon"],
"CHARAIE":["charoie", "charaie", "charaies"],
"CHARBON":["charbon", "charbons"],
"CHARGE":["charge"],
"CHARBONEE":["charbonnee", "charbonee", "charbonees"],
"CHARBONIER1":["charbonnier", "charboner", "charbonier"],
"CHARDENAL":["chardonal", "chardenal", "cardinal", "chardonax"],
"CHARGIER":["charger", "chargier", "chargié", "chargiee", "chargiees", "chargiez", "charge", "chargent"],
"CHARITABLE":["charitable", "charitables"],
"CHARITÉ":["charité", "charitez"],
"CHARJABLE":["chargeable", "charjable"],
"CHARME1":["charme", "charmes"],
"CHARME2":["charme", "charmes"],
"CHARMER":["charmer", "charmez"],
"CHARRE":["chare", "charre"],
"CHARRETE":["charette", "charrette", "charrete", "charretes"],
"CHARPENTER":["charpanter", "charpenter", "charpantez"],
"CHARPENTIER":["charpantier", "charpentier", "charpenter", "charpantiers"],
"CALCEDOR":["Calcedor", " Charquedon"],
"CHARRETER":["charreter", "chareter", "charetter", "charretez", "charretent"],
"CHARRETIER":["charretier", "charetier", "charretiers"],
"CHARRETON":["charreton", "chareton", "charetun", "charretons"],
"CHARRIERE":["charriere"],
"CHAS":["chas"],
"CHASSE":["chasse", "case", "châsse", "chasses"],
"CHASTE":["chaste"],
"CHASTEL":["chastel", "chastiax", "château"],
"CHASTELAIN":[" chastelain", "châtelain", "chastelains"],
"CHASTELET":["châtelet", "chastelet"],
"CHASTI":["chasti"],
"CHASTIIER":["chastïer", "chastiier", "chastier", "chastiant", "chasti", "chasties", "chastie", "chastïent", "chastoient", "chastia", "chastiez", "chastiez"],
"CHATEL":["cheptel", "chatel", "chetel"],
"CHASTRER":["chastrer", "châtrer", "chastrez"],
"CHASUBLE":["chasuble"],
"CHAT":["chat", "chaz"],
"CHAUCE":["chausses", "chauce", "chauces"],
"CHAUCËURE":["chaucëure", "chalceure", "chauçure", "chauceüre"],
"CHAUCIEE":["chaucie", "chalciee", "chaucee", "chaussée", "chauciee"],
"CHAUCIER1":["chalcier", "chaucer", "chausser", "chaucier", "chaucié", "chauciees", "chauciez", "chauce", "chauça", "chaucierent"],
"CHAUDE":["chaut", "chaude"],
"CHAUF":["chalf", "chauf", "chaus", "chauve", "chauz"],
"CHAUFER":["chaufer", "chauffer", "chaufast", "chaufé"],
"CHAUT":["chaut", "chaude", "chaudes", "chaut", "chauz", "chax"],
"CHAUZ1":["chals", "chaux", "chauz"],
"CHËANCE":["cheance", "chëance", "chance"],
"CHEMIN":["chemin", "chemins"],
"CHEMINEE1":["cheminée", "cheminee", "cheminees"],
"CHEMINEL":["cheminal", "cheminel"],
"CHEMINER":["cheminer", "cheminant", "chemine", "cheminent", "cheminoient", "cheminerent"],
"CHEMISE":["chemise", "chemises"],
"CHENU":["chanu", "chenu", "chenue", "chenuz"],
"CHËOIR":["chëoir", "chair", "cheoir", "cheoite", "cheoiz", "cheü", "cheüe", "cheües", "cheüz", "chiet", "chieent", "cheoit", "cheoient", "chaï", "cheï", "cheïrent", "cheez", "chiee", "cheïst", "cheïssent"],
"CHEVAL":["cheval", "chevax"],
"CHEVALEREZ":["chevaleresce", "chevalerez", "chevaleresse"],
"CHEVALERIE":["chevalerie", "chevaleries"],
"CHEVALIER":["chevaler", "chevalier", "chevaliers"],
"CHEVAUCHIEE":["chevauchiee", "chevalchee", "chevauchée", "chevalchiee"],
"CHEVAUCHIER":[" chevauchier", "chevalchier", "chevalcher", "chevaucher", "chevalchant", "chevauchant", "chevalchié", "chevauchié", "chevalche", "chevauche", "chevalchent", "chevauchent", "chevalchoit", "chevauchoit", "chevalchoient", "chevalcha", "chevalchierent", "chevalchiez", "chevauchiez"],
"CHEVECINE":["chevecine"],
"CHEVEL":["chevol", "cheveil", "chevel", "cheveu", "chevols", "chevos", "chevox"],
"CHEVEÇAILLE":["cheveçaille"],
"CHEVECE":["chevesce", "chevèce", "chevece"],
"CHEVELET":[" chevelet", "chevolet"],
"CHEVELU":["chevelu", "chevelue"],
"CHEVESTRE":["chevestre", "chevêtre", "chevoistre"],
"CHEVIR":["chevir"],
"CHEVRUEIL":["chevrueil", "cheverel", "chevrel", "chevriax"],
"CHICHE1":["chiche", "chiches"],
"CHIEF1":["chef", "chief", "chié", "chiés"],
"CHIEN":["chen", "chien", "chiens"],
"CHIENES":["chienes", "chanes", "chenes", "chienes"],
"CHIENET":["chiené", "chienet", "chenet", "chiennez"],
"CHIER":["cher", "chier", "chiere", "chieres", "chier", "chiers"],
"CHIERE":[" chere", "chère", "chiere"],
"CHIEREMENT":["cherement", "chierement", "chèrement", "chieremant"],
"CHIERIR":["cherir", "chierir", "chérir"],
"CHIERTÉ":["cherté", "chierté"],
"CHIEVRE":["chevre", "chèvre", "chievre"],
"CHÖE":["chöe", "choe", "choue"],
"CHÖETE":["çüete", "chöete", "choete", "chouette", "çuete"],
"CHOIS":["choix", "chois"],
"CHOSE":["chose", "choses"],
"CHOISIR":["choisir", "choisi", "choisissiez"],
"CHOSER":["choser", "chose", "chosent"],
"CIEL":["ciax", "ciel"],
"CIERGE":["cirge", "cierge", "cierges"],
"CIME":["cime"],
"CIMETIERE":["cemetire", "cimetiere", "cemetires"],
"CIRE":["cire"],
"CISEMUS":["cisemus"],
"CINGLER":["cinglant", "ceingle", "cengler", "cingler"],
"CITÉ":["cité", "citez"],
"CIVE":["cive"],
"CLAMADEU":["Clamadeu", "Clamadex"],
"CLAMER":["clamer", "clamee", "clamez", "claim", "clain", "clainmes", "claimme", "clainme", "claiment", "clainment", "clamoit", "clamoient", "clama", "clamerai", "clameroit", "clainme", "clamez", "claint", "clamasse", "clamast"],
"CLARISSANT":["Clarissant", "Clarissanz"],
"CLAMOR":["clamur", "clameur", "clamor"],
"CLARTÉ":["clarté", "clartez"],
"CLEF":["clé", "clef"],
"CLER":["clair", "cler", "clere", "cleres", "clers"],
"CLERC":["clerc", "clers"],
"CLEREMENT":["clairement", "clerement", "cleremant"],
"CLIGES":["Cligés", "Clygés"],
"CLERGIE":["clergie"],
"CLERJON":["clerçon", "clerjon", "clergeon", "clerdon"],
"CLICE1":["clisse", "clice", "clices"],
"CLINER":["cliner"],
"CLO":["clo", "clou", "clos"],
"CLOCHE":["clokke", "cloche", "cloches"],
"CÖARDIE":["cöardie", "couardie", "coardie"],
"CLOCHIER":["clochier", "clocher", "cloiche", "clochoient"],
"CLOFICHIER":["clofichier", "clouficher", "closfichiee"],
"CLORE":["clore", "clos", "close", "closes", "clost", "clot"],
"CÖART1":["couard", "cöart", "coarde", "coart", "coarz"],
"CÖARDISE":["coardise", "cöardise", "couardise"],
"CÖART2":["Coarz"],
"COCHE1":["coche"],
"COCODRIL":["corcatrille", "cocodril", "crocodile", "corquatrilles"],
"CÖE":["cöe", "queue", "cowe", "coe"],
"COFRE":["coffre", "cofre", "cofres"],
"COGUILLANZ":["Coguillanz "],
"COI1":["coi", "coie", "coiz", "quoi", "quoie"],
"COIFE":["coife", "coiffe"],
"COI3":["Cuoi", "Coi", "Quoi"],
"COIGNIEE":["coigniee", "coigné", "cognée", "coigniees"],
"COILLIR":["cueillir", "coillir", "coillie", "quialt", "quiaut"],
"COINTE":["cointe", "cointes"],
"COINTEMENT":["cointement", "cointemant"],
"COINTISE":["cointise"],
"COISIER":["coisier", "coiser", "coise"],
"COITE":["cuite", "coite"],
"COL":["cou", "col", "cos"],
"COLEE":["colée", "colee", "colees"],
"COLËIZ":["coleïz", "couleis", "coulis", "coleïces"],
"COLER1":["coler", "couler", "colant", "colanz", "colé", "colee", "colez", "cole", "colent", "coloit", "coloient"],
"COLOM":["colom", "colum", "colon", "colons"],
"COLOMBE2":["colome", "colombe", "columpne", "colonne", "colomes"],
"COLOINGNE":["Coloigne"],
"COLER3":["coler", "collier"],
"COLOR":["colur", "couleur", "color", "colors"],
"COLORER":["colorer", "colurer", "coloré", "coloree", "colorez"],
"COMANDEMENT":["commandement", "comandemant", "comandemanz"],
"COMANDËOR":["comandeor", "commandeur", "comanderre", "commandeur", "comanderres"],
"COMANDER":["commander", "comander", "comandé", "comandee", "comandees", "comandez", "comant", "comande", "comandez", "comandent", "comandoit", "comandai", "comanda", "comandera", "comandez", "comant"],
"COMANT":["comand", "comant", "command"],
"COMBATËOR":[" conbateor", "combatëor", "combateor", "combatur"],
"COMBATRE":["combatre", "combattre", "conbatre", "conbatant", "conbatanz", "conbatu", "conbatuz", "conbat", "conbatent", "conbatoit", "conbatrai", "conbatra", "conbatrons", "conbatront", "conbatroie", "conbate", "conbatent", "conbatessiez"],
"COMBLE1":["conble", "comble"],
"COMBLER":["conblé", "combler", "conblez"],
"COMÉ":["comé"],
"COMENCIER":["comencier", "comencer", "comancier", "comancié", "comanciee", "comance", "comancent", "comançoit", "comançoient", "comança", "comancierent", "comancerai", "comancera", "comanceront", "comanciez"],
"COMFAITEMENT":["cumfaitement", "confaitemant", "confeitemant", "confeitement"],
"COMPAGNE":["compagne", "compaigne", "conpaigne", "conpaignes", "conpaingne"],
"COMPAGNIE":["compaignie", "compagnie", "conpaignie", "conpaingnie", "conpeignie"],
"COMPAGNON":["compagnon", "compaignon", "conpaignon", "conpaignons", "conpaingnons", "conpainz", "conpeignons"],
"COMPARER2":["comparer", "comperer", "comprer", "conparer", "conparé", "conparee", "conper", "conpere", "conperent", "conparra", "conparroiz", "conparriez", "conpert"],
"COMPAS":["compas", "conpas"],
"COMPASSER":[" compasser", "conpasser", "conpassees", "conpassez"],
"COMPLAINDRE":["conplaindre", "complaindre", "compleindre", "conplaint"],
"COMUNAUMENT":["comunaument", "communalment", "communalement", "comunalmant"],
"COMUNE":["commune", "comune"],
"COMPLAINTE":["complainte", "compleint", "conplainte", "conplaintes"],
"COMPLIE":["conplies", "complie", "complie", "complies", "conplie"],
"COMUN":["commun", "comun", "comune"],
"COMUNEMENT":["communement", "comunemant", "communément"],
"COMUNIIER":["comeniier", "comuniier", "communier", "communier", "communer", "comeniez"],
"COMUNÏON":["comunïon", "communion", "communiun", "comenion"],
"CONCEVOIR":["concevoir", "conceivre", "conçut"],
"CONDUIRE":["conduire", "conduit", "condui", "conduirai", "conduie", "conduist", "conduit", "conduient", "conduisoie", "conduisoit", "conduiroient", "conduient"],
"CONCORDANCE":["concordance"],
"CONDUIT":["conduit", "conduiz"],
"CONESTABLE":["connestable", "connétable", "conestable", "conestables"],
"CONFÈS":["confés"],
"CONFESSE":["confesse"],
"CONFESSER":["confesser", "confesse"],
"CONFESSÏON":["confessïon", "confession"],
"CONFIRE2":["confire", "confite"],
"CONFONDEMENT":["confondement", "confondemant"],
"CONFONDRE":["confondre", "confondu ", "confondue", "confonduz", "confont", "confondent", "confonde "],
"CONFORT":["confort", "conforz "],
"CONFORTER":["conforter", "conforté", "conforte", "conforte", "confortez", "confort", "confortant", "confortent"],
"CONFUS1":["confus"],
"CONGIÉ":["congé", "congié", "congiez"],
"CONIN":["conin", "connin", "conins"],
"CONJOINTURE":["conjoncture", "conjointure"],
"CONJÖIR":["conjöir", "conjoir", "conjouir", "conjoïr", "conjoï", "conjoïz", "conjot", "conjoent", "conjoient", "conjoïssent", "conjoïssoit", "conjoï", "conjoie"],
"CONOISSANCE":[" connaissance", "conoissance", "conuissance", "conuissances"],
"CONOISTRE":["connaître", "conoistre", "conuistre", "coneü", "coneüe", "coneüz", "conois", "conuis", "quenuis", "conoist", "conuist", "conuissiez", "conoissent", "conuissent", "conuissoit", "conoissoiez", "conoissoient", "conuissoient", "conui", "quenui", "conut", "quenut", "coneüstes", "queneüstes", "conurent", "conoistroie", "conuistroit", "conuis", "conoisse", "conuisse", "conoisse", "conuisse", "coneüsse", "coneüst", "coneüssent"],
"CONJUREMENT":["conjuremant", "conjurement", "conjuremanz"],
"CONJURER":["conjurer", "conjuré", "conjur", "conjure"],
"CONQUERRE":["conquerir", "conquere", "conquérir", "conquerre", "conquis", "conquise", "conquier", "conquiert", "conquist", "conquerra", "conquerroie", "conqueïsse", "conqueïst"],
"CONQUESTER":["conquester"],
"CONROI":["conrai", "conroi"],
"CONSCÏENCE":["conscïence", "conscience", "conciance"],
"CONRËER":[" conrëer", "conreier", "conréer", "conreer", "conreez", "conroie", "conreez"],
"CONSEIL":["conseil", "consauz", "consoil"],
"CONSEILLIER1":["conseiller", "conseillier", "consellier", "conseilliez", "conseillié", "consellié", "consoil", "consoilles", "consoille", "consoillent", "conselloit", "conseilla", "conseillierent", "conseilleroie", "consoille", "consoilles", "Conseilliez", "conselliez", "conselliez", "conseillasse"],
"CONSEILLIER2":[" conseiller1", "conseillier"],
"CONSENT":["consance", "consent", "consant"],
"CONSENTIR":["consantir", "consentir", "consantir", "consant", "consantiromes", "consante"],
"CONSIREE":["consirree", "consiree", "consirée", "consirre"],
"CONSIRER":[" consirrer", "consirer"],
"CONTE1":["comte", "conte", "contes", "cuens"],
"CONTE2":["conte", "contes"],
"CONSIVRE":["consiure", "consivre", "consuivre", "consivant", "consilt", "consiust"],
"CONTENANCE":[" contenance", "contenances"],
"CONTENÇON":["contençon", "contention", "contançon"],
"CONTENEMENT":["contenemant", "contenement"],
"CONTENIR":["contenir", "contandra", "contendroiz", "contanroie", "contien", "contenez", "contenist", "contiens", "contient", "contenez", "contint", "contenuz"],
"CONTER":["conter", "contant", "conté", "contee", "contees", "contez", "cont", "conte", "content", "contoie", "contoit", "conta", "conterai", "conteron", "conteroiz", "conteroie", "conteroit", "contez", "cont", "contasse"],
"CONTRAIT":["contrait", "contret"],
"CONTRARIIER":["contraliier", "contrariier", "contraliant"],
"CONTESSE":["comtesse", "contesse", "contesses"],
"CONTRAIRE":["contreire", "contraire", "contraires"],
"CONTRARÏOS":["contraliieus", "contrarïos", "contrarios", "contrarious", "contralieus", "contrarieux"],
"CONTRATENDRE":["contr'atandre", "contratendre", "contrattendre", "contratendons", "contreatendissent"],
"CONTREDIRE":["contredire", "contredit", "contredite", "contredi", "contredïent", "contredisoit", "contredis", "contredist", "contredeïstes", "contredira", "contrediroie", "contrediroit", "contreïst", "contredeïssent "],
"CONTREDIT":["contredit", "contrediz"],
"CONTRESTER":["contrester"],
"CONTRETENIR":["contretenir", "contretenuz", "contretient", "contretint"],
"CONTREE":["contrée", "contree", "contrees"],
"CONTREFAIRE":["contrefaire", "contrefeire", "contrefere", "contrefetes", "contrefez"],
"CONTRUEVE":["controve", "contrueve"],
"CONVOIIER":["conveiier", "convoiier", "conveer", "convoyer", "convoier", "convoiant", "convoié", "convoiee", "convoiez", "convoie", "convoient", "convea", "convoia", "convoierent", "convoiera", "convoit"],
"CONVERS2":["convers"],
"CONVERSER":["converser", "converse", "conversa", "conversé"],
"COPE1":["cope", "coupe"],
"COPEL2":["pecol", "copel", "quepol", "pecul", "pécol", "quepouz"],
"ÇOPER":["çoper", "choper", "chopper", "çope", "çopa"],
"COR2":["corn", "cor", "corz"],
"CORAGE":["courage", "corage", "corages", "coraige"],
"COPER":["couper", "coper", "colpé", "colpee", "colpees"],
"CORAILLE":["coral", "coraille"],
"CORAJOS":["corajos", "corajus", "corageus", "corageuse"],
"CORBEL":["corbel", "corbeau"],
"CORIR":["corir", "courir", "coure", "corre", "corant", "corrant", "corranz", "coreü", "cort", "corent", "coroient", "corrut", "corroie", "cor", "coroit", "corut", "corrurent"],
"CORDE":["cord", "corde", "cordes"],
"CORDELE":["cordele", "cordelle"],
"CORËOR":["coreor", "corëor", "coureour", "coureur", "coreors"],
"CORGIEE":["corgie", "curgee", "courgée", "corgiee", "corgiees"],
"CORJON":["corion", "corjon"],
"CORNEILLE1":["cornoille", "corneille", "cornoilles"],
"CORNOALOIS":["Cornoalois"],
"CORNU":["cornu"],
"CORNEILLIER":["corneillier", "cornouiller", "cornelier"],
"CORNER":["corner", "cornee", "cornent"],
"CORNIX":["Corniex", "Cornix"],
"CORNOAILLE":["Cornoaille"],
"COROIE":["coroie", "coreie", "courroie", "corroie", "corroies"],
"CORONE":["couronne", "corone", "corones", "querone"],
"CORONEMENT":["coronemant", "coronemen", "couronnement"],
"CORQUE":["Corques"],
"CORONER":["couronner", "coroner", "coroné", "coronee", "coronent", "corona", "coronast"],
"CORROCIER":["corrocier", "couroucier", "corucer", "courroucer", "correcier", "correciez", "corroz", "corroces", "corroce", "correça", "correceroie"],
"CORROMPRE":["corrompre", "corrumpre", "corronpre"],
"CORROZ":["corroz", "corus", "courroux"],
"CORS1":["corps", "cors"],
"CORS2":["cours", "cors"],
"CORSAGE":["corsage", "corssage"],
"CORT1":["cour", "cor", "cort", "corz"],
"CORT2":["court", "cort", "corte", "cortes", "cortes", "corz"],
"CORTINE":["cortine", "courtine1", "cortines"],
"CORTOIS":["cortois", "corteis", "courtois", "cortoise"],
"CORTOISEMENT":["cortoisement", "courtoisement", "cortoisemant"],
"CORTOISIE":["corteisie", "cortoisie", "courtoisie"],
"COSDRE":["cosdre", "coustre", "coudre", "queudre", "cosue", "cousue", "cost", "queust"],
"COSIN":["cousin", "cosin", "cosine", "cosins", "cousin", "cousine"],
"COST2":["cost", "coût", "coust"],
"COSTANTIN":["Costantin"],
"COSTANTINOBLE":["Costantinoble"],
"COSTE2":["côte", "coste"],
"COSTÉ":["costé", "costez"],
"COSTER1":["coster", "coûter", "couster", "costé", "coste", "costa", "cost"],
"COSTOIIER":["costoiier", "costoier", "costeier1", "côtoyer", "costoiant", "costoie"],
"COSTUME":["coustume", "custume", "costume", "costumes"],
"COSTUMIER":["custumer", "coutumier", "costumier", "costumiere", "costumiers"],
"COSTURE":["cousture", "costure", "costures"],
"COTELE":["cottelle", "cotele"],
"COTOATRE":["Cotouatre"],
"COUCHE":["colche", "couche"],
"COTE1":["coute", "code", "codes", "cote", "cotes"],
"COTE2":["cotte", "cote", "cotes"],
"COUCHIER":["coucher", "colchier", "couchier", "colchiez", "couchié", "couchiee", "couchiez", "couche", "colchent", "couchent", "colchierent", "couchast", "couchierent", "Couchié", "colcherez", "coucheroiz", "colchassent"],
"COUP1":["coup", "colp", "cop", "cos"],
"COUPABLE":["coupable", "corpable"],
"COUPE":["coupe", "coulpe", "colpe", "corpe", "corpes"],
"COUTE":["coute", "coilte", "coulte", "coste", "costes", "coute", "coutes"],
"COUTEL":["cotel", "couteau", "costel", "coutel"],
"COVENABLE":["convenable", "covenable"],
"COVENANCE":["covenance", "convenance"],
"COVENIR":["convenir", "covenir", "covient", "covenoit", "covint", "convenra", "covandra", "covanra", "covendra", "covenra", "covandroit", "covanroit", "covendroit", "covaigne ", "covaingne ", "coveigne ", "coveingne", "covenist"],
"COVENANT":["covenant", "covenanz"],
"COVENT1":["covent", "convent", "covant", "covanz"],
"COVENT2":["covant", "covent", "couvent"],
"COVER":["cover", "couver", "cove", "covast"],
"COVERTEMENT":["covertement", "covertemant"],
"COVERTURE":["couverture", "coverture", "covertor", "covertors"],
"COVIR":["covir", "covi", "3 :[ covi"],
"COVOITIÉ":["coveité", "covoité", "covoitié"],
"COVINE":["covine"],
"COVOITIER":["coveitier", "convoiter", "covoitier", "covoitié", "covoitiez", "covoit", "covoite", "covoitiez", "covoitent", "coveita"],
"COVOITOS":["coveiteus", "covoitos", "covoitos", "coveitus", "convoiteux", "covoiteuse"],
"COVOITISE":["coveitise", "covoitise"],
"COVRIR":["covrir", "coverir", "couvrir", "covert", "coverte", "covertes", "coverz", "coevre", "cuevre", "cuevrent", "covroient", "covri", "covrez"],
"CRAISSE":["greisse", "craisse", "graisse", "gresse"],
"CRAPOS":["crapeus", "crapos", "crapeux", "grapeus"],
"CRAS":["gras", "cras"],
"CRËANCE":["creance", "crëance", "créance"],
"CRËANT":["crëant", "créant1", "creant", "creanz"],
"CRËANTE":["crëante", "creante"],
"CRËANTER":["crëanter", "granter", "créanter", "creanter", "creanté", "creant", "creante", "creantai", "creanta", "creantez"],
"CRENU":["crenu"],
"CRENEL":["crenel", "créneau", "creniax"],
"CRESME":["cresme", "cresm", "chrisma", "chrême", "chresme"],
"CRESTER":["crester", "crêter", "cresté", "creste"],
"CRESTIIEN1":["Crestiien", "Crestien", "Crestiens"],
"CRESTÏENTÉ":["crestïenté", "chrestienté", "cristienté", "crestianté", "crestiantez"],
"CRESTIIEN2":["crestiien", "cristien", "crestien", "crestiene", "crestiens"],
"CRI":["cri", "criz"],
"CREVER":["crever", "crevé", "crevee", "crevez", "crieve", "crievent", "creva", "creverent"],
"CRÏATOR":["crïator", "creator", "creatur", "créateur", "Criator"],
"CRÏATURE":["creature", "crïature", "créature", "criature"],
"CRIEMBRE":["craindre", "criembre", "criendre", "crienbre", "cremu", "cremuz", "criem", "crien", "criens", "crient", "criement", "cremoit", "crienbroie"],
"CRIEME":["creme", "crieme", "criemme"],
"CRÏER1":["crïer", "creer", "créer", "cria"],
"CRÏER2":["crïer", "crier", "criers", "criant", "criee", "criez", "crie", "crïent", "crioit", "crioient", "criai", "cria", "crierent", "crieroit", "criast"],
"CRIN":["crine", "crin", "crins"],
"CRISOLITE":["crisolite", "chrysolithe", "crisolites"],
"CRIST":["Crist", "Criz"],
"CRISTAL":["crestal", "cristal", "cristauz", "cristax"],
"CROC2":["croce", "croc", "cros"],
"CROCE":["crosse", "croce", "croces"],
"CROIE":["creie", "craie", "croie"],
"CROIRE":["creire", "croire", "croirre", "creü", "creüe", "creüz", "croi", "croiz", "croit", "creez", "croient", "creoie", "creoit", "creiez", "crui", "crut", "creümes", "crurent", "cresrai", "crerra", "cresra", "cresroiz", "crerroit", "croi", "creez", "croies", "croie", "creüsse"],
"CROISETE":["croisete", "croisette", "croisetes"],
"CROISIER":["croisié", "croizer"],
"CROISILLIÉ":["croisillié", "croisilliee"],
"CROIZ":["crois", "croix", "croiz"],
"CROISSIR":["croissir", "croissent"],
"CROISTRE":["croistre", "creistre", "creü", "creüe", "creüz", "croist", "crut", "crurent", "crestrai", "crestra", "crestroit", "creüst"],
"CROLER":["croller", "crouler", "croler", "crosé", "croslé", "crosle", "croslent"],
"CROT":["crot", "croit"],
"CRU":["cru", "crue", "crues"],
"CRÜAUTÉ":["cruelté", "crüauté", "cruauté", "crualté"],
"CRUCEFIIER":["crocefiier", "crucefiier", "crucefier", "crucifier", "crocefiez"],
"CROPE":["croupe", "crope", "cropes"],
"CROSER":["croser", "creuser"],
"ÇUCRE":["sucre", "çucre"],
"CUER2":["coer", "coeur", "cuer", "cuers"],
"CRUCEFIS":["crocefis", "crucefis", "crucifix", "Crocefis"],
"CRÜEL":["crüel", "cruel", "cruex"],
"CRÜELMENT":["cruelment", "cruelement", "cruellement", "cruelmant"],
"CUERPOUS":["cuerpous"],
"CUIDIER":["cuider", "cuidier", "cuit", "cuides", "cuide", "cuidiez", "cuident", "cuidoie", "cuidoit", "cuidoient", "cuidai", "cuida", "cuiderent", "cuiderai", "cuidera", "cuideront", "cuideroie", "cuideroit", "cuidasse", "cuidast", "cuidereiez"],
"CUIR":["cuir", "cuirs"],
"CUIRE":["cuire", "cuit", "cuites", "cuiz", "cuist"],
"CUIRIEE2":["curée", "cuiriee"],
"CUISINE":["cuisine", "cuisines"],
"CUISENCENOS":["cuisencenos", "cusençunnous", "cuisançonneux", "cusançoneus"],
"CUISENÇON":["cusencion", "cusançon "],
"CUISSE":["cuisse"],
"CUIVRE1":["cuivre", "cuevre", "coivre"],
"CUIVRE2":["cuivre"],
"CUVE":["cuve", "cuves"],
"CULVERT":["cuivert", "culvert", "cuiverz"],
"CURE":["cure"],
"DÄERRAIN":["derriien", "däerrain", "dereiner", "derrain", "darriens", "dasreainne", "derriens", "desreien", "desrien"],
"DAIM":["daim", "dains"],
"DAMAGE":["damage", "dommage", "domage", "domages", "domaige", "domaiges"],
"DAMAGIER":["damagier", "damager", "dommager", "domagier", "domagié", "domageroient"],
"DAME":["dame", "dames"],
"DAMOISELE":["dameisele", "damoisele", "dameisele", "dameiseles"],
"DAMOISEL":["damoisel", "dameisel", "dameisiax"],
"DAN2":["dant", "Damedeu", "Damedex", "dan", "danz"],
"DANCE":["danse", "dance", "dances"],
"DANCIER":["dancer", "danser", "dancier", "dancent"],
"DANGIER":["danger", "dangier", "dongier"],
"DANOIS":["denois", "daneis", "danisk", "danois", "denoises"],
"DART":["dard", "dart", "darz"],
"DATE2":["date", "dade", "datte", "dates"],
"DAVI1":["Davi"],
"DAVI2":["Daviz"],
"DÉ1":["de", "dé", "dez"],
"DEBATRE":["débattre", "debatre", "debatant", "debatuz", "debat", "debatent"],
"DEBOISSIER":["deboissier", "deboissiees", "deboissent", "deboisse"],
"DEBONAIREMENT":["debonairement", "débonnairement", "deboneiremant", "deboneremant", "debonerement"],
"DEBONAIRE":["débonnaire", "debonaire", "deboneire", "debonere", "deboneres"],
"DEBONAIRETÉ":["deboneireté", "debonaireté", "débonnaireté", "debonereté"],
"DEBOTER":["deboter", "debuter", "débouter", "debote"],
"DEBRISIER":["debrisier", "debriser", "debrise"],
"DECEVOIR":["deceivre", "décevoir", "decevoir", "deçoivre", "decevant", "deceü", "deceüe", "deceüz", "deçoit", "deçoivent", "deçut", "deçurent", "deçoive", "deceüst"],
"DECHËOIR":["decheoir", "decheeir", "dechair", "déchoir", "decheoir", "decheü", "decheües", "decheez"],
"DECLIN":["déclin", "declin"],
"DECLINER":["decliner", "décliner", "declinant"],
"DECOLER1":[" décoller", "decoler", "decolez"],
"DECORIR":["decorre", "decorir", "decure", "décourir", "decoroient"],
"DEDUIRE":["déduire", "deduire", "desduire", "deduit", "deduit", "deduiez", "deduient", "deduisoient", "dedui", "deduiez"],
"DEFENDRE":["deffandre", "defendre", "défendre", "desfandre", "desfandu", "desfandue", "desfanduz", "desfant", "desfandent", "desfandoit", "desfandeiez", "desfandi", "desfandrai", "desfandra", "desfandroiz", "desfende", "desfande", "desfandent"],
"DEDUIT":["déduit", "deduit", "deduiz"],
"DEFINAILLE":["definaille"],
"DEFENS":["deffans", "defense", "desfans"],
"DEFENSE":["deffanse", "defense", "défense", "desfanse", "desfanses", "desfansse", "desfansses"],
"DEFINER1":["definer", "définer"],
"DEGRÉ":["degré", "degrez"],
"DEGROCIER":["degrocier", "dégrocier", "degroces"],
"DEFINER2":["definer", "define"],
"DEFOLËIZ":["defoleis", "defoleïz"],
"DEFOLER":["defoler", "defuler", "défouler", "defolee"],
"DEGOTER":["degoter", "degotez", "degote", "dégoutter"],
"DEGUENCHIR":["deganchir", "deguenchir", "deguanchir", "deganchi"],
"DEIGNIER":["deignier", "digner", "degnier", "daigner", "daing", "daigne", "daingne", "deingne", "daigniez", "daingniez", "deigniez", "daignent", "deignent", "deingnoit", "deignai", "daignas", "deigna", "deignames", "deignastes", "deignierent", "daingnera", "daigneroie", "daigneroit", "deigneroit", "daignierent", "deigneriez", "daigneroie", "daigneroit", "deigneroit", "daingnast", "deignast", "deingnast"],
"DEHACHIER":["dehachier", "dehacher", "déhacher", "dehachiee", "dehachiez"],
"DEHÉ":["dehé", "deshait", "dahait", "dahé", "dahez"],
"DEINTIÉ":["deintié", "daintié"],
"DËITÉ":["deité", "déité", "deïté", "deïtez"],
"DEJANGLER":["dejangler", "degengler", "degenglent"],
"DEJETER":["degeter", "dejeter", "déjeter", "degiete"],
"DELAI":["délai", "delai", "delais"],
"DELAIE":["délaie", "delaie"],
"DELAIEMENT":["délaiement", "delaiemant"],
"DELAIIER1":["delaier", "delaiier", "deleer", "délayer", "delaiant", "delaie", "delaiez", "delaient", "deloient", "delaiez", "delait"],
"DELICE":["délice", "delice"],
"DELIIÉ":["delïé", "deliié", "délié", "delié", "deliee", "deliees", "deliez"],
"DELIT2":["délit", "delit", "deliz"],
"DELITABLE":["delitable", "delitables"],
"DELITIER":["deliter", "delitier", "delit", "delite", "delitoit", "delit"],
"DELIVRANCE":["délivrance", "delivrance"],
"DELIVRE":["délivre", "delivre", "delivres"],
"DELIVREMENT":["delivrement", "delivremant"],
"DELIVRER":["deliverer", "délivrer", "delivrer", "delivré", "delivree", "delivrees", "delivrez", "delivre", "delivra", "deliverras", "deliverra", "delivrera", "delivre", "delivrez"],
"DELUGE":["deluvie", "déluge", "deluge"],
"DEMAINE":["demaine", "demeine", "domaine", "demainne"],
"DEMAINEMENT":["demeinement", "demainnemant"],
"DEMANDE":["demande"],
"DEMANDER":["demander", "demender", "demandé", "demandee", "demande", "demandez", "demandoit", "demandent", "demandai", "demanda", "demandames", "demandees", "demandez", "demant", "demandes", "demandas", "demandastes", "demanderent", "demanderai", "demandera", "demanderoiz", "demanderoit", "demandez", "demant", "demandiez", "demandasse", "demandast", "demandesiez"],
"DEMENER":["démener", "demener", "demenant", "demené", "demenee", "demenez", "demain", "demainne", "demenez", "demainnent", "demenoit", "demenoient", "demena", "demenerent", "demaint"],
"DEMENTER":["dementer", "demantee", "demanter", "demante", "demantent", "demantoient", "demantast"],
"DEMI":[" demi", "demie", "demis"],
"DEMINCIER":["demincier", "demincer", "démincer", "demince"],
"DEMORANCE":["demurance", "demeurance", "demorance"],
"DEMORE":["demure", "demeure", "demore"],
"DEMOREE":["demuree", "demoree", "demeurée", "demoree"],
"DEMORER":["demorer", "demeurer", "demurer", "demorant", "demoré", "demoree", "demor", "demore", "demorez", "demorent", "demorerent", "demorasse", "demorast", "demora", "demort", "demorastes"],
"DEMOSTRANCE":["demostrance", "demonstrance", "demustrance", "démontrance"],
"DENREE":["danree", "denree", "denrée"],
"DENT":["dent", "dant", "danz"],
"DEPARTIR":["départir", "departir", "departirs", "departi", "departie", "departies", "departiz", "depart", "departez", "departent", "departoit", "departoient", "departi", "departi", "departirent", "departirai", "departira", "departiroiz", "departiront", "departe"],
"DEMOSTRER":["demostrer", "demustrer", "démontrer"],
"DENIER":["denier", "deniers"],
"DEPECIER":["despecier", "depescer", "dépecer", "depecier", "depecié", "depeciee", "depeciez", "depiece", "depiecent"],
"DEPENDRE":["depandre", "dependre", "dépendre", "depandent"],
"DEPLAINDRE":["deplaindre", "depleindre", "déplaindre", "deplaignent"],
"DEPORT":["desport", "déport", "deport", "deporz"],
"DEPORTER":["desporter", "déporter", "deporter", "deporté", "deport", "deporte", "deportent", "deportoient", "deport", "deport"],
"DEPRIIER":["deproier", "depriier", "déprier", "deprier"],
"DEPUTAIRE":["deputaire", "députaire", "députère", "deputaire"],
"DERAISNE":["desresne", "dereine", "déraisne"],
"DERAISNIER":["desresnier", "deraisnier", "dereiner", "desreniee", "desresnié", "desresniee", "desresne", "desresneroit", "desraist"]}