forms_and_lemmas = {"aaisement":["aeisemant"],
"aancrer":["aencré"],
"äatine":["ahatine"],
"aaisier":["aeisier", "aeisié", "aeisiee", "aeisiez", "aeise", "aeisent"],
"abaiier":["abaient"],
"abaissier":["abeissié", "abeissiez", "abessié", "abessiee", "abessiez", "abeisse", "abesse", "abeissent", "abessent", "abeissa", "abeissera"],
"abandoner":["abandoné", "abandonee", "abandonees", "abandon", "abandone", "abandona"],
"abatre":["abatre", "abatu", "abatue", "abatuz", "abat", "abatent", "abati", "abatié", "abatront", "abate", "abatist"],
"abé1":["abes", "abez"],
"abet":["abet", "abez"],
"abevrer":["abevrer", "abevree", "aboivrent"],
"abeie":["abeïe", "abbaie", "abbatia", "abbaye", "abaïe", "abaïes"],
"abel":["abel"],
"abelir":["abelir", "abellir", "abelist", "abelissent", "abeli", "abelisse"],
"abrahan":["abrahan"],
"abregier":["abregier", "abreger", " abréger", "abréger"],
"abriver":["abrivé", "abriver"],
"accident":["accidant", "accident", "accidens"],
"abisme":["abisme", "abyssus", "abîme"],
"abiter":["habiter", "abiter", "abite"],
"abonder":["abonder", "abunder", "abonde"],
"aborrer":["anborrer", "aborrer", "aborré"],
"aceindre":["açaindre", "aceindre", "aceint", "aceignent", "aceingnoit", "aceindrons"],
"acension":["asçansion", "acension", "ascenciun", "ascension", "acenssion"],
"achater":["acheter", "achater", "achate", "achatent"],
"acheminer":["acheminer", "achemine", "acheminerent"],
"acier":["acier"],
"acerer":["aceré", "acérer", "acerer", "aceree"],
"acesmer":["acesmer", "acesmee", "acesmez"],
"acliner":["acliner", "acline"],
"acoardir":["acoardir", "acouardir", "accouardir", "acuardir", "acoardi", "acoardie", "acoardiz"],
"acoillir":["acoillir", "acueillier", "acueillir", "acueudre", "accueillir", "acoillie", "aquiaus", "aquialt", "aquiaut", "acuellent", "acuelle"],
"acointable":["acointable", "accointable"],
"acointance":["acointance", "acuintance", "accointance", "acointances", "acontance"],
"acointe1":["acointe", "acuinte", "accointe", "acointes"],
"acointier":["acointier", "acuinter", "acointié", "acoint", "acointe", "acointoient", "acointa", "acointierent", "acointasse"],
"acoisier":["aqueisier", "acoisier", "accoiser", "acoise"],
"acompagnier":["aconpaignier", "acompagnier", "acompaignier", "acumpainer ", "aconpaigne", "aconpaignent", "accompagner"],
"acoler":["acoler", "accoler", "acoler", "acole", "acolent", "acola"],
"acomplir":["aconplir", "acomplir", "accomplir", "aconpliz"],
"aconsivre":["aconsiure", "aconsivre", "aconcevoir", "aconsievir", "aconsivre", "acunsivre", "aconsuivre", "aconsivre", "aconseü", "aconseüe"],
"açoper":["açoper", "achoper", "achopper", "açopa"],
"acopler":["acopler", "acoupler", "accoupler", "acople"],
"acor":["acor", "acort", "acors"],
"acordance":["acordance", " accordance"],
"acorde1":["acorde", "acord"],
"acorde2":["acorde"],
"acorder":["acorder", "accorder", "acordé", "acordee", "acordez", "acort", "acorde", "acordent", "acorderent", "acorderai", "acorde"],
"acorer":["acorer", "acoré", "acoree", "acorees", "acorez"],
"acorionde":["acoridomés", "acorionde", "acoriundés"],
"acorre":["acorre", "acourir", "acurre", "accourir", "accourir", "acort", "acorent"],
"acoster":["acoster", "accoster", "acostee", "acostez", "acoste"],
"acostumance":["acostumance", "accoutumance"],
"acostumeement":["acostumeemant", "acustumeement", "accoutumément"],
"acostumer":["acostumer", "acoustumer", "accoutumer", "acustumer", "acostumé", "acostumez"],
"acoter":["acoter", "acuter", "accoter", "accouder", "acoder", "acotez"],
"acreanter":["acreanter", " acréanter", "acreanté", "acreant", "acreanz", "acreante", "acreantez", "acreant"],
"acroire":["acroire", "acreire", "accroire", "acreü", "acroit", "acrurent", "acroie"],
"acroistre":["acroistre", "acreistre", "accroître", "acrois", "accroist", "acroist", "acroissoit"],
"adan":["adan", "adanz"],
"adeser":["adeser", "adoise", "adesa", "adoist", "adesast"],
"adestrer":["adestrer", "adextrer", "adestre"],
"adevancir":[" adevancir", "adevancirent"],
"adober":["adober", "aduber", "dubban", "adouber", "adobé", "adobez", "adoba", "adoberoit"],
"adoler":["adolé", "adoler", " aduler", "adouler", "adolez"],
"adrecier":["adrecier", "adrescer", "adresser", "adrecié", "adreciee", "adreciez", "adrece", "adresce", "adreça"],
"adoner":["adoner", "adonner", "adonee"],
"adosser":["adosser", "adossez"],
"adoucir":["adoucir", "aducer", "adolcir"],
"adrece":["adresce", "adrece", "adresse"],
"adroit":["adroit", "adreit", "adroit", "adroite", "adroiz"],
"aduré":["aduré", "adurer", "adurez"],
"aé":["aé", "eé", "ahé"],
"aerdre":["aerdre", "aers", "aert", "ahert", "aerdent"],
"afaire":["afeire", "afaire", "affaire", "afaires", "afeires", "afere"],
"aeschier":["aeschier", "aeschoit"],
"aesmer":["aesmer", "asmer", "aesmez"],
"afaitement":["afeitemant", "afaitement"],
"afaitier":["afeitier", "afaitier", "afaiter", "affaiter", "afeitiee", "afeitiez", "afeitié", "afaite", "afeite"],
"afamer":["afamer", "affamer", "afamez"],
"afebliier":["afebloiier", "afebliier", "affaibloyer", "afebloier", "afebli", "afeblie", "afeblissent"],
"aferir":["aferir", "afferir", "afférir", "afiert", "afierent"],
"afeblir":["afebloier", "afebloiez", "afeblir", "affaiblir", "afoiblir"],
"afïer":["afïer", "afier", "affier", "afiee", "afi", "afie", "afïent", "afia"],
"afermer":["afermer ", "affermer", "afermee"],
"afichier":["afichier", "afficher", "afichiez", "afiche", "afichent"],
"afit2":["afit", "afiz", "afi"],
"afitier":["afiter", "afitier", "affité", "afeitant"],
"afoler1":["afoler", "afuler", "affoler", "afolé", "afolee", "afolez", "afole", "afolent", "afoloit", "afole", "afolt", "afost"],
"afoler2":["afoler", "afole", "afolent", "afolent"],
"afonder":["afonder", "enfundrer", "affonder", "afonde"],
"agait":["aguet", "agait", "aguait "],
"agaitier":["agueitier", "agaitier", "aguaiter", "guetter", "agueitié", "agueitiee", "agueites", "agaite", "agueite", "agaitiez"],
"afrener":["afrener", "afreiner", "enfrener", "afreinne"],
"afubler":["afubler", "affubler", "afublé", "afublee", "afublees", "afublez", "afuble", "afublerent", "afublez", "afubla"],
"agencir":["ajancier", "ajancir", "agencir ", "agensir", "agencist"],
"agenoillier":["agenoillier", "agenouillier", "agenoiler", "agenoilliee", "agenoilliees", "agenoilliez", "agenoille", "agenoillent", "agenoillierent"],
"agnel":["aignel", "agnel", "agneau", "aigniax"],
"agnelet":["aignelet", "agnelet"],
"agreer":["agreer", "agréer", "agree"],
"agrevain":["agravains", "agrevains"],
"agrever":["agrever", "agrevee"],
"anguingueron":["aguinguerrons", "anguinguerron", "anguinguerrons"],
"agu":["aigu", "agu", "aguz"],
"aguisel":["aguisel", "aguiflez"],
"aguille":["aguille", "aiguille"],
"aguisier":["aguisier", "aiguisier", "agucer", "aiguiser", "aguisent"],
"ahan":["ahan"],
"ahaner":["ahaner", "ahane"],
"aidier":["eidier", "aidier", "aider", "haidier", "aïde", "aïe", "aidiez", "aiderai", "eideras", "aidera", "eidera", "eiderons", "aideroit", "eideroit", "eidons", "eidast", "aïst", "aït"],
"äie1":["aïde", "äie", "aide", "aïdes"],
"aigle":["egle", "aigle"],
"aigue":["eve", "aigue", "eau"],
"äir":["aïr"],
"air1":["er", "air", "airs"],
"äirier":["aïrer", "äirier", "airier", "aïré", "aïre", "aïrié"],
"ainzné":["ainzné", "ainznee", "ainznez", "ainsné"],
"ais":["ais", "eis", "es"],
"aise":["aeise", "aise", "eise", "eises", "eisse"],
"aigre1":["aigre", "egre", "aigres"],
"ail":["ail"],
"aissele2":["aisselle", "eissele", "essele"],
"aiuele":["aiole", "aiuele", "aele", "aïeul"],
"ajorner":["ajurner", "ajourner", "ajorner", "ajorné", "ajornez", "ajorne", "ajorna"],
"ajoster":["ajuster", "ajoter", "ajoster", "ajoste"],
"alegier1":["alegier", "aleger", "alegié", "alegiee", "aliege"],
"aleine":["aleine", "haleine", "alainne", "alainnes", "aleinne"],
"alaitier":["alaiter", "alaitier", "allaiter", "aleitanz"],
"alaschier":["alaschier", "alasche"],
"alee":["alee"],
"alegement":["alegemant", "alegmement"],
"alemele":["alemele", "alumelle"],
"alener":["alener", "aleiner", "alainne"],
"alemaingne":["alemaine", "alemaigne", "alemaingne"],
"aler":["aler", "alers", "alant", "alé", "alees", "alez", "alee", "vois", "vas", "va", "vait", "vet", "alomes", "alons", "alez", "vont", "aloie", "aloit", "alions", "aliens", "aleiez", "aloient", "alai", "alas", "ala", "alastes", "alerent", "irai", "iras", "ira", "irons", "eroiz", "irez", "iroiz", "iront", "iroie", "iroit", "iriens", "iriez", "iroient", "va", "alons", "alez", "aille", "voise", "ailles", "voises", "aille", "aut", "voise", "voist", "ailliez", "aillent", "voisent", "alasse", "alasses", "alast", "alessiens", "alesiez", "alassent", "alessient"],
"alemant":["alemant"],
"alerïon":["alerion", "alerïon", "alerions"],
"alëure":[" alëure", "alure"],
"alever":["alever", "eslever", "alevee"],
"alexandrin":["alixandrin", "alisandrin"],
"alixandre1":["alixandre", "alixandres"],
"alixandre2":["alixandre", "alixandres"],
"alixandre3":["alixandre", "alixandres"],
"alixandre4":["alixandre"],
"alie":["alie", "alue"],
"alier":["alier", "aliers"],
"aliier2":["aliier", "allier", "alïent"],
"alis":["alis", "alys"],
"alöe1":["aloue", "alöe", "aloe"],
"alöé":["alo", "alöé", "eloes", "aloès", "aloé"],
"alöer2":["aloiier", "alöer", "aloer", "alouer", "aluer", "allouer"],
"alöete":["aloete", "alöete", "alouet", "alouette"],
"aloigne":["aloigne", "alonge"],
"aloignier":["aloignier", "esloigner", "aloigniees"],
"aloser":["aloser", "alosez", "alose"],
"alue2":["alue", "alude"],
"aluè":["alué", "aluè", "aluef", "alleu"],
"alumer":["allumer", "alumer", "alumé", "alumez", "alume", "alument", "aluma"],
"amant":["amant", "amanz"],
"amasser":["amasser", "amassé", "amassee", "amassees", "amassez", "amasse", "amassent", "amassa"],
"amaugin":["amaugin", "amauguins"],
"ambler":["anbler", "ambler", "anblant", "anbloit", "anblast"],
"amblëure":["anblëure", " ambleure", "amblure"],
"ame":["alme", "ame", "ames"],
"amende1":["amande", "amende"],
"amendement":["amandement", "amendement"],
"amender":["amender", "amander", "amandé", "amandee", "amandez", "amant", "amande", "amanda", "amanderent", "amanderai", "amanderoie", "amandez", "amant", "amant"],
"ameçon":["ameçon", "esmeçon", "amesson", "hameçon"],
"amembrer":["amanbrer", "amembrer", "amanbree"],
"amener":["amener", "amené", "amenee", "amenez", "amain", "amaing", "amainne", "amenomes", "amainnent", "amenoit", "amenoient", "amenai", "amena", "amanrai", "amanra", "amanroiz", "amanroie", "amanroit", "amainne", "amaint", "ameigniez", "amenassent"],
"amentevoir":["amentevoir", "amentiver", "amanteü", "amenteü", "amantui"],
"amenuisier":["amenuisier", "amenuser", "amenuisiee"],
"amëor":["ameor", "amëor", "amerres"],
"amer1":["amer", "aimer", "amé", "amee", "amez", "aim", "ain", "aimme", "ainme", "amez", "aiment", "ainment", "amoie", "amoit", "ameiez", "amoient", "amai", "ama", "amerent", "amerai", "amera", "ameroie", "ameroit", "amez", "aint", "amoiz", "amasse", "amast", "amessiez"],
"amer2":["amer", "amere", "amers"],
"amertume":["amertume", "anertume"],
"ametiste":[" ametite", "ametiste", "améthyste", "ametistes"],
"ametre":["ametre", "amettre", "admettre", "amis", "amise", "ametez", "ametoient", "amist"],
"ami":["ami", "amie", "amies", "amis"],
"amïable":["amïable", "amiable"],
"amïablement":["amïablement", "amiablemant"],
"amiens":[" amiens"],
"amistié":["amistié", "amistiee", "amistiez", "amitié"],
"amonestement":["amonestemant", "amonestement", "admonestement"],
"amonester":["amonester", "admonester", "amoneste", "amonesté"],
"amor":["amur", "amour", "amor", "amors"],
"amoroin":["amoronge", "amoroin"],
"amoros":["amoreus", "amoros", "amouros", "amerus"],
"amorter":["amorter", "amortir", "amortee"],
"ample":["ample", "anple", "emple", "emples"],
"amüir":["amuïr", "amuir", "amuiz"],
"amuser":["amuser", "amusé", "amusee"],
"an":["an", "anz"],
"ancele":["ancelle", "ancele"],
"ancesserie":["ancesserie"],
"ancessor":["ancesur", "ancêtre", "ancessor", "ancessors"],
"anel1":["anneau", "anel", "enel", "eniax"],
"anel2":["annel", "annuel", "anel"],
"anciien":["anciien", "ancien", "anciene", "ancienes", "anciens"],
"ancre":["ancre", "encre"],
"ane":["ane"],
"anee":["anee", "année", "annee"],
"anelet":["annelet", "anelet"],
"anet":["anet", "anez"],
"angarde":["angarde", "engarde"],
"angevin":["angevin"],
"anglois":["anglois", "engleis", "einglois", "einglois"],
"angle":["angle", "engle", "engles"],
"angleterre":["angleterre", "eingleterre", "engleterre"],
"angele":["angele", "ange", "anges", "enge", "enges"],
"anjo":["anjo"],
"angoisse":["anguisse", "angoisse", "angoisses", "engoisse"],
"angoissier":["anguissier", "angoissier", "angoissiez", "angoisse", "engoisse", "angoissiez", "angoissent", "angoissoient", "angoissierent"],
"angoissos":["angoisseux", "angoissos", "angoisseus", "angoisseuse", "angoissos"],
"angres":["angres", "angrés"],
"antioche":["antioiche", "antioche"],
"antipodes":["antipodes", "antipodés"],
"anuitier":["anuiter", "anuitier", "anuitié"],
"aorer2":["adorer", "aorer", "aorez", "aore", "aora", "aorerai"],
"aost":["aust", "août", "aost", "aoust"],
"aovrer":["aovrer", "aoevrent"],
"aovrir":["aovrir", "aoverte"],
"apaiier":["apaiier", "apaier", "apaiez", "apaiez"],
"apaisier":["apeisier", "apaisier", "apeser", "apeisiez", "apeise"],
"apantoisier":["apantoisier", "apantoisant"],
"apareil":["aparoil", "apareil"],
"apareillier1":["apareillier", "aparellier", "apareillié", "apareilliee", "apareilliees", "apareillies", "apareilliez", "aparellié", "aparelliee", "aparelliees", "aparelliez", "aparoille", "aparelliez", "aparoillent", "apareilla", "aparellierent", "aparaut"],
"apareillier2":["apareillier", "aparoille", "apareilloit"],
"aparler":["aparler", "aparole", "aparolent", "aparloient", "aparla", "aparlast"],
"aparoir":["aparoir", "aparanz", "aperent", "aparut", "aparurent", "aparra", "apeire", "apere"],
"apartenir":["apurtenir", "apartenir", "apartient", "apartenist"],
"apel":["appel", "apel"],
"apeler":["apeler", "apelé", "apelee", "apelez", "apel", "apele", "apelez", "apelent", "apeloie", "apeloit", "apeloient", "apela", "apelastes", "apelerent", "apelerai", "apeleroie", "apelez", "apialt", "apiaut", "apelast"],
"apendre":["apandre", "apendre", "apant"],
"apenser":["apenser", "apanser", "apansee", "apanssé", "apanse", "apansse", "apansoient", "apansa"],
"apercevoir":["apercevoir", "aparcevoir", "aparcevant", "aparcevanz", "aparceü", "aparceüe", "aparceüz", "aparçoit", "aparçui", "aparçut", "aparcevront", "aparçoive", "aparceüssent", "aparceüst"],
"apert1":["apert", "aperte"],
"apert2":["apert", "aperte", "aperz"],
"apertement":["apertement", "apertemant"],
"apeticier2":["apetiser", "apeticier", "apetisser", "apetise"],
"aplaignier":[" apleignier", "aplaner", "aplanier", "aplaigner", "aplaignier", "aplaigne", "aplaignié"],
"apoiier":["apuiier", " apoiier", "apuier", "apoier", "apoié", "apoiee", "apoiees", "apoiez", "apuie", "apoia"],
"apoindre":["apoindre", "apoint"],
"apointier2":[" apointier", "apoindre", "apointe"],
"apondre":["apondre", "aponde"],
"aporter":["aporter", "aporters", "aporté", "aportee", "aportees", "aportez", "aport", "aporte", "aportent", "aportoit", "aportoient", "aporta", "aporterent", "aportera", "aporteront", "aporteroit", "aporte", "aportez", "aport", "aportast", "aportassent"],
"apostle":["apostre", "apostle", "apôtre", "apostre", "apostres"],
"apovrir":["apovrir", "empovrir", "apovri"],
"aprendre":["apprendre", "aprenez", "apraingne", "apreigne", "apreïsses", "apraigniez", "apreingnent", "apreïst", "apanre", "aprandre", "aprendre", "apris", "aprise", "apraing", "aprant", "apris", "aprist", "aprandra", "aprendra", "aprendront"],
"aprentiz":["aprantiz", "aprentiz", "aprentic", "aprentif", "apprentiz", "apprenti"],
"aprester":["aprester", "apprêter", "aprester", "apresté", "aprestez", "apreste", "aprestoit", "aprestoient", "aprestez"],
"apresser":["apresser", "appresser", "apressent"],
"aprison":["aprison"],
"aprochier":["aprochier", "aproichier", "apruichier", "apruichant", "aprochié", "aprochiee", "aprochiez", "aproches", "aproche", "aproiche", "aprochent", "aprocheiez", "aprochoient", "aprocha", "aprocherent", "aprochierent", "aprocheras", "aprocheront", "aprochiez"],
"aproismier":["aprismier", "aproismier", "aprismer", "aprismant"],
"aquerre":["aquerir", "aquerre", "aquerra", "aquerroie"],
"aquiter":["acquitter", "acquiter", "aquiter", "aquitee", "aquitez", "aquit", "aquite"],
"arrabe":["arabe", "arrabe"],
"arabi":["arabi", "arrabi"],
"arabïois":["arabois", "arabeis", "arabïois", "arrabiois"],
"arragon":["aragon", "arragon"],
"arain":["airin", "arain"],
"araisne":["araisne", "areisne", "aresne"],
"araisnier":["aresnier", " araisnier", "arener", "araisner", "arraisonner", "aresniee", "aresne", "areisone", "aresne", "areisonez", "aresnoit", "areisonas", "areisnera"],
"arbaleste":[" arblaste", "arbalète", "arbaleste", "arbalestes"],
"arbalestee":[" arbalétée", "arbalestee", "arbalestees"],
"aramir":["arramir", "aramir", "arramie"],
"arbalestier":["arbalestier", " arbalestier", "arbalestriers"],
"arbre":["arbre", "arbres", "aubre"],
"arc":["arc", "ars"],
"arcevesque":["arceveske", "archevêque", "arcevesque", "arcevesques"],
"arche2":["arke", "arche"],
"archiee":["archée", "archiee"],
"archal":["archal"],
"arçon":["arçun", "arçon", "arçons", "arçonz"],
"archier":["archier", "archiers"],
"arçoner":["arçoner", "arçonner", "arçone", "arçonent"],
"ardoise":["atoise", "adoise", "ardoise"],
"ardre":["ardoir", "ardre", "arder", "ardant", "ardanz", "ars", "arse", "art", "ardent", "ardoit", "ardoient", "arde", "ardent"],
"aree":["aree", "arees"],
"areeement":["areer", "areement", "arrément", "arëaumant"],
"areine":["areine", "araine", "areinne"],
"arer":["arer", "arees", "erent"],
"ares":["ares", "arés"],
"aresner":[" aresner", "aresné"],
"arest":["arest"],
"arester":["arester", "aresté", "arestee", "arestez", "areste", "arestent", "arestoit", "arestas", "aresta", "arestut", "aresterent", "aresterons", "aresteroie", "arest", "arestast"],
"arestuel":["arestoel", "arestuel"],
"argent":["arjant", "argent", "argenz"],
"argone":["argone"],
"argüer":["arguër", "arguer", "argüe"],
"arismetique":["arimetique", "arismetique", "aritmetike", " arithmétique"],
"ariver1":["ariver", "arriver", "arivé", "arivez"],
"armaire":["aumeire", "armaire", "armoire", "aumaire"],
"armer":["armer", "armé", "armee", "armez", "arme", "arment", "armoient", "arma", "armerent", "armerai", "armeront", "armeroit", "armez", "armassent"],
"armëure":["armëure", "armeure", "armeüres"],
"armonie":["armonie", "armonies"],
"aronde":["arunde", "aronde", "arondres"],
"aroser1":["aroser", "aruser", "arosé"],
"arrachier":["arrachier", "aracer", "arracher", "arachier", "arachié", "arachiee", "arachiez", "araiches", "arache"],
"art":["art", "arx", "arz"],
"aroter2":["aroter", "aruter", "arote", "arouter", "aroterent"],
"arpent":["arpent", "arpant", "arpanz"],
"artetique":["artetique", "arcetique"],
"artu":["artu", "artus"],
"asne":["asne"],
"aspre":["aspre", "âpre", "aspres"],
"asprement":["asprement", "aspremant"],
"asproiier":["aspreiier", "asproiier", "asproier", "asproie"],
"assalir":["assaillir", "assalir", "asaillir", "assaillir", "asailli", "asaillie", "asailliz", "assailli", "asauz", "asalt", "asaut", "assaut", "asaillent", "assaillent", "asailli", "assaillons", "asaille", "assaille"],
"assaut":["assault", "asaut", "asauz", "assalt", "assaut", "assauz"],
"assemblee":["assemblee", "asanblee", "assanblee"],
"assembler":["assembler", "asembler", "asanbler", "assanbler", "asanblé", "asanblee", "asanblez", "assanblé", "assanblee", "assanblees", "assanblez", "asanble", "assanble", "asanblent", "assanblent", "asanblai", "asanbla", "assanbla", "asanblerai", "asanbleront", "assanbleroient", "assanblast"],
"assener":["assener", "asener", "asené", "asenez", "assenee", "asane", "asanne", "asene", "asenent", "asena"],
"assëoir":["aseoir", "asseoir", "asis", "asise", "asises", "assis", "assise", "assises", "asiet", "asieent", "asis", "asist", "assist", "asistrent", "asseez", "asieent", "aseïsse", "aseïst"],
"asserir":[" asserir", "aserir", "aseri"],
"assëur":["sëur", "asseur", "aseür", "asseür"],
"assëurer":[" asseurer", "aseurer", "aseürer", "asseürer", "aseüré", "aseüree", "asseüré", "asseürees", "asseürez", "asseür", "aseüres", "aseüre", "aseürent", "aseürerent", "asseürerons", "aseüreroiz"],
"assoagier":["assoagier", "assouagier", "asuager", " assouager", "asoage"],
"astele":["astele", "astelle", "estele", "esteles"],
"astrenomie":["astrenomie", "astronomie"],
"assomer1":["assomer", "assommer", "essomez"],
"assomer2":["assomer", "asomer", "asome"],
"asur":["asur", "azur"],
"atachier2":["atachier", "atacher", "atachiee", "atachiez", "atache"],
"ataindre":["atteindre", "ataindre", "ateindre", "ateignant", "ataint", "atainte", "atainz", "ataing", "atainz", "ataint", "ateint", "ataignent", "ateignent", "ateingnent", "ateignoit", "atains", "ateindrai", "ateindroiz", "ateigne"],
"athenes":["athenes"],
"atäine":["anhatine", "atahine", "ataïne", "ateïne"],
"atalenter":["atalanter", "atalenter", "entalenter", "atalante", "atalant"],
"atarder":["attarder", "atarder", "atardant"],
"ateler":["ateler", "atler", "atelez"],
"atemprer":["atanprer", " atemprer", "atranprer", "atremprez"],
"atendre":["atandre", "atandres", "atendre", "atendanz", "atandu", "atandue", "atendu", "atant", "atandent", "atendent", "atandoit", "atendoit", "atandoient", "atendi", "atandrai", "atendrai", "atandras", "atandra", "atendra", "atandrons", "atandroie", "atandez", "atande", "atende"],
"atendue":["attendue", "atandue", "atendue"],
"atente":["atante", "atente"],
"aterrer":["aterrer", "atterrer", "aterré"],
"atochier":["atochier", "atucher", "atoichier", "atochié", "atoches", "atoche", "atocheroies", "atochiez", "atochast"],
"ator":["atour", "ator"],
"atillier":["atillier", "atirer", "atillier", "atillent"],
"atirier":["atirer", "atirier", "atirié", "atiriee", "atire"],
"atisier":["atisier", "atiser", "attiser", "atise"],
"atornement":["atornement", "aturnement", "atournement", "atornemant"],
"atorner":["atourner", "aturner", "atorner", "atorné", "atornee", "atornees", "atornez", "ator", "atorne", "atornent", "atornoit", "atorna", "atornerent", "atornez", "atort", "atourt"],
"atraire":["atreire", "atraire", "atreite", "atrete", "atret", "atraient"],
"aubagu":["aubagu"],
"aube3":["albe", "aube"],
"aucube":["aucube", "aucubes"],
"atrait":["atrait", "attrait", "atret"],
"atropeler":[" atropeler", "attroupeler", "atropelerent"],
"audïence":["audïence", "audiance", "audience"],
"äunee":["aunee", "aünee"],
"auner":["auner", "alner", "auné", "aunera"],
"aufrique":["aufrique"],
"aumarie":[" aumarie"],
"aumosne":["almosne", "aumone", "aumosne"],
"aumosniere":["almosniere", "aumosnere", "aumosniere"],
"aune2":["aune", "aunes"],
"autel2":["auter", "autel"],
"autrement":["autrement", "altremant", "autremant"],
"äuner":["aüner", "auner", "aüné", "aünee", "aüne"],
"assalon":["assalon", "ausalon"],
"aussiment":[" aussiment", "alsiment", "ausimant"],
"autresiment":["autresiment", "autresimant"],
"avalee":["avalée", "avalee"],
"avaler":["avaler", "avalant", "avalé", "avalee", "avalez", "avale", "avaloit", "avaloient", "avala", "avalerent", "avalez"],
"avalon":["avalon", "avalons"],
"avancier":["avancer", "avancier", "avanciee", "avance", "avança", "avancerai"],
"avancir":["avancir", "avencist"],
"avantage":["avantage", "aventage"],
"avantpié":["avantpié", "avantpied", "avanpié"],
"avarice":["avarice"],
"aveine":[" aveine", "avoine", "avene", "avainne", "aveinne", "aveinnes", "avoinne"],
"avenanment":["avenanment", "avenantment", "avenanmant"],
"avenement":["avenemant", "avenement"],
"avenir":["avenir", "avenant", "avenanz", "avenu", "avenue", "avenues", "avient", "avienent", "avenoit", "avenoient", "avint", "avindrent", "avandra", "avendra", "avenra", "avandront", "avandroit", "avaigne", "aveigne", "aveingne", "aviegne", "avaingnent", "avenist"],
"aventure":["avanture", "avantures", "aventure", "aventures"],
"aventuros":["avantureus", "aventuros", "aventurous", "avantureuse"],
"aver":["avare", "aver", "avere"],
"averir":["averir", "averer", "avérir", "averi"],
"aversaire":["averseire", "adversaire aversaire"],
"aversier":["adverser", "aversier"],
"avesprer":["avesprer"],
"avilenir":["avilenir", "avileni"],
"avillier":["aviler", "avillier", "avilliees", "aville", "avilla"],
"aviron2":["avirun", "aviron"],
"avironer":["avironer", " enviruner", "avironner", "avirone"],
"avis":["avis"],
"aviser":["aviser", "avise", "avisast"],
"avöé":["avöé", "avoet", "avoué", "avoé"],
"avogler":["avuglé", "avogler", "aveugler", "avuglé", "avuglee", "avuglez"],
"avoiier":["aveiier", "avoiier", "avoyer", "aveier", "avoié", "avoiee", "avoiees", "avoiez", "avoie", "avea", "avoit"],
"avoir":["avoir", "avoirs", "eü", "eüe", "aüz", "eües", "eüz", "ai", "ei", "as", "a", "avomes", "avons", "avez", "ont", "avoie", "avoies", "avoit", "aveiez", "aviez", "avoient", "oi", "eüs", "ot", "out", "eüstes", "orent", "avrai", "avrei", "avras", "avra", "avromes", "avrons", "avrez", "avrez", "avroiz", "avront", "avroie", "avroies", "avroit", "avriens", "avreiez", "avriez", "avroient", "aies", "aiez", "aie", "aies", "ait", "eit", "aiens", "aiez", "aient", "eüsse", "aüsses", "eüsses", "aüst", "eüst", "aüssiez", "eüssiez", "eüssent"],
"avoutre":["avuiltre", "avoutre", "avoutre"],
"avril":[" avril", "avrix"],
"avugle":["aveugle", "avogle", "avugle", "avugles"],
"bäaillier":["baaillier", "bäaillier", "baaillié"],
"bacon":["bacon", "bacons"],
"bade":["bade"],
"bademagu":["bademagu", "bademaguz"],
"bades":["bade", "bades"],
"babiloine":["babiloine"],
"bacheler":["bacheler", "bachelers"],
"bacin":["bassin", "bacin", "bacins"],
"bai":[" bai", "bai"],
"baile":["baille", "baile", "bailes"],
"baillie":["baillie"],
"baignier":["beignier", "baignier", "baigne", "baignent", "baignoit", "baingnierent"],
"baillier":["bailler", "baillier", "baillié", "bailliee", "bailliees", "bailliez", "bail", "bailles", "baille", "bailliez", "baillent", "bailloit", "bailla", "baillerai", "bailleroiz", "bailleront", "baille", "bailliez", "baillessiez"],
"bain":["bain", "baing", "bainz"],
"baisier":["baisier", "beisier", "beisiers", "beisant", "beisié", "beisiee", "beises", "beise", "beisent", "beisoit", "beisa", "beiserai", "beiseré", "best", "beise", "beisast"],
"baissier":["beissier", "baisser", "beissié", "beissiee", "bessié", "beisse", "beise", "beissent", "baissoient"],
"balancier":["balancier", "balancer", "balance"],
"ban1":["ban", "banc"],
"ban2":["ban", "bans"],
"banc":["banc", "bans"],
"bandon":["bandon", "bandun"],
"baniere":["baner", "bannière", "baniere", "banieres"],
"banir":["banir", "bani"],
"batiste":["baptiste"],
"barat":["barat"],
"barate":["barate"],
"barbacane":["barbecan", "barbacane", "barbaquane"],
"barbe":[" barbe", "barbes"],
"barbé":["barbé", "barbez"],
"barge":["barge", "barges"],
"baril":["baril", "barel", "barrilz"],
"barnage":["barnage", "barnages"],
"baron":["baron", "barons", "ber"],
"barbelé":["barbelé", "barbelees"],
"barbïolete":["barbiolete", "barbïolete", "berbioletes"],
"bargaignier":["barguignier", "bargaignier", "bargainer"],
"baronaille":["baronaille"],
"baronie":["baronie"],
"barre":["barre", "barres"],
"barrer":["barrer", "barré", "barrez"],
"barut":["barut"],
"bas":["bas", "basse", "basses"],
"basme":["baume", "basme"],
"bastir":["bastir", "basti", "bastie"],
"baston":["baston", "bastons"],
"bastonet":["bastonet"],
"bataille":["bataille", "batailles"],
"bataillier1":["bataillier", "bateillant"],
"batel2":["batel"],
"batesme":[" batesme", "baptesme", "baptême"],
"batistere":["baptestire", "batistere"],
"batre":["batre", "batant", "batanz", "batu", "batue", "batuz", "bat", "batent", "batoit", "bat"],
"baucenc":["bauçant", "bauçan", "baucenc", "baucent", "baucenz"],
"baule":["baule", "baules"],
"baut":["baut", "bald", "baud", "baude", "bauz"],
"belrepeire":["belrepeire", "belrepaire", "biaurepaire", "biaurepere"],
"bec":["bek", "bec"],
"bedoiier":["bedoiier", "bedoiers"],
"behorder":["behorder"],
"bëer":["bëer", "beer", "béer", "baer", "bahé", "bee", "baoit", "baast"],
"bel":["beau", "bel", "bele", "beles", "biau", "biaus", "biaux", "biax"],
"belement":["belement", "belemant"],
"beslic":["bellic", "beslic", "belif", "belinc", "bernic"],
"bende":["bende", "bande", "bandes"],
"bender":["bander", "bender", "bandee", "bandees"],
"benëir":["beneïr", "beneistre", "benedicere", "benëir", "bénir", "beneoit", "beneoite", "beneoiz", "beneïssoient", "beneï", "beneïe"],
"berser":["berser"],
"berte":["berte", "bertain"],
"bertran":["bertran", "bertranz"],
"besant":["besan", "besant", "besanz"],
"bescuit":["besquit", "bescuit"],
"besoigne":["besogne", "besoigne", "besoingne", "besoingnera"],
"besoing":["besoin", "besoig", "besoing", "besoinz"],
"beste":["bête", "beste", "bestes"],
"bestïal":["bestïal", "bestial", "bestiax"],
"bestorner":["bestorner", "bistourner", "bestornee"],
"beter2":["beter", "béter2", "betee"],
"betir":["betir", "bétir", "betist"],
"bevrage":["beverage", "breuvage", "bevrage"],
"biauté":["biauté", "biautez"],
"biauvez":[" biauvez"],
"bien":["bien", "biens"],
"bienvenue":["bienvenuz", "bienvenue"],
"biere":["bere", "biere", "bieres"],
"bievre":["bevere", "bievre"],
"bilis":["bilis", "bylis"],
"bille1":["bille"],
"blanc":["blanc", "blanche", "blanches", "blans"],
"blancheflor":["belissant", "blancheflor"],
"bis":["bis", "bise", "bises"],
"bisse":["bisse", "biche", "biches"],
"blandir":["blandir", "blandist"],
"blasme":["blasme", "blasmes"],
"blasmer":["blasmer", "blasme"],
"blason":["blason", "blazon", "blazons"],
"blé":["blet", "blé", "blez"],
"blecëure":["blecëure", "bleceure", "bleceüres"],
"blecier":["blecier", "blescer", "blesser", "blecié", "bleciee", "bleciez", "blece", "blesce", "bleça"],
"brïen":["brïen", "bliant", "blianz"],
"blïaut":["blïaut", "bliaut", "bliauz", "bliax"],
"bliobleheris":["bliobleheris", "blioberis"],
"blo":["bleu", "blo", "bloe", "bloes"],
"blont":["blunt", "blonc", "blonde", "blondes", "blont"],
"boce1":["bosse", "boce"],
"bocel3":[" bocel"],
"boche":["bouche", "boche", "boches", "boiche"],
"bochete":["bouchete", "bouchette", "bochete"],
"bocle":["bocle", "bocles", "boucle"],
"boclé":["bouclé", "boclé"],
"boclete":["bouclette", "boclete"],
"boçoiier":["boceiier", "boçoiier", "bocier", "bocer", "bossoier", "bosser", "bossier", "boceier"],
"boçu":["bossu", "boçu", "boçue", "boçuz"],
"böele":["böele", "boele"],
"bofu":["bofu"],
"bois":["bois"],
"boise2":["boise"],
"boisier1":["boisier", "boiser", "boisent", "boisa"],
"boiste":["boîte", "boiste"],
"boivre":["beivre", "boire", "boivre", "boivres", "beü", "beüe", "boit", "bevez", "bevoit", "bevoient", "bui", "but", "beüstes", "burent", "bevrai", "bevroiz", "boive"],
"bole2":["boule", "bole"],
"bolir":["boillir", "bolir", "bouillir", "buillir", "boillant", "bolt", "bout", "bolent"],
"bon":["ben", "boen", "boene", "boenes", "boens", "bon", "bone", "bones", "bons", "buen", "buens"],
"bone":["bosne", "borne", "bone"],
"bonement":["bonement", "bonnement", "boenemant", "bonemant"],
"bonet":["bonnet", "bonet"],
"bonté":["bonté", "bontez"],
"boquerant":["boquerant", "boqueranz"],
"borc":["burc", "burg", "bourg", "borc", "bors"],
"borde1":["borde"],
"borgne":["borgne", "borne", "borgnes"],
"borjois":["burgeis", "bourgeois", "borjois"],
"borrel":["borrel", "bourel", "borriax"],
"boschage":["boscage", "boschage", "boschaige"],
"bot1":["bout", "bot", "bous"],
"bot2":["bot", "butte", "boz"],
"bot4":["bot", "boz"],
"boteillier":["boteillier", "botiller", "botellier", "botelliers"],
"boter1":["boter", "bouter", "boté", "botee", "botez", "bote", "botent", "bota", "botast"],
"boton":["boton"],
"bouser":["bouser", "bousoit"],
"brachet":["brachet", "brachez"],
"braciee":["braciee"],
"bouzon":["bouzon", "boujon", "bozun", "bozon"],
"bovier":["bover", "bouvier", "bovier", "boviers"],
"brabançon":["breibançon", "brabançon", "brabançun"],
"bracier2":["bracier", "bracer", "brasser", "brace"],
"braidif":["breidif", "braidif"],
"brait":["bret"],
"braie":["braies", "braie"],
"braier":["braiier", "brael", "braier"],
"brandigan":["brandigan", "brandiganz"],
"brandon":["brandon"],
"braire":["braidis", "braire", "breire"],
"branche":["branche", "branches"],
"brangiens":["brangiens"],
"braz":["bras", "braz"],
"brandes":["branles"],
"brant1":["branc", "brant", "branz"],
"bräon":["braon", "bräon", "braun", "braons"],
"bravaïn":["bravaïn", "bravaïns"],
"bretaingne":["bretaigne", "bretaingne", "breteingne"],
"bretesche":["bretache", "bretesche", "bretesches"],
"brese":["breise", "brese"],
"bresil2":["brasil", "bresil"],
"bret":["bret", "brete", "brez"],
"breton":["breton", "bretun", "breton", "bretons"],
"bricoigne":["bricoingne", "bricoigne"],
"briément":["briefment", "brefment", "briément", "briemant"],
"brisier":["briser", "brisier", "brisant", "brisié", "brisiee", "brisiez", "brise", "brisent", "brisa", "brisera", "brist", "brit"],
"bricon1":["bricon"],
"briébraz":["briebraz"],
"brief":["bref", "brief", "briés"],
"brive":["brive"],
"broce":["brouce", "brosse", "broce"],
"broceliande":["broceliande"],
"broche":["broche"],
"brochier":["brochier", "brocher", "brochié", "broche", "broiche", "brochent", "broichent"],
"broigne":["broingne", "broine", "broigne"],
"brosder":["brosder", "brouder", "brosdé", "brosdee"],
"bruil1":["bruil", "broil", "breuil", "bruel"],
"bruianz":["bruianz"],
"brun":["brun", "brune", "bruns"],
"bruire":["bruire", "bruiant", "bruianz", "bruit"],
"bruit":["bruit", "bruiz"],
"brunet":["brunet", "brunete", "brunez"],
"brunete":["brunete", "brunette", "brunetes"],
"brunir":["brunir", "burnir", "brunie", "bruniz"],
"bu":["bu"],
"bucifal":["bucifal", "bucifax"],
"buef":["boef", "boeuf", "buef", "bués"],
"buer":["buer"],
"bufe":["buffe", "bufe", "bufë"],
"buire1":["buire"],
"buiron1":["buiron", "buron"],
"buisine":["buisine", "busine", "buisines"],
"buissonos":["boissoneus", "buissonos", "buissonneux", "buissuneus", " boissoneus"],
"busche":["bûche", "busche"],
"cachet":["quachet", "cachet", "quachez"],
"cacier":["quacier", "cacier", "quace"],
"cadoalant":["cadoalant", "cadiolanz", "caroduanz"],
"cadoc":["cadoc"],
"calogrenant":["calogrenant", "calogrenanz", "qualogrenant", "qualogrenanz"],
"candie":["candie", "quandie"],
"cadret":["cadret"],
"caille":["caille", "quaille"],
"canele":["canele", "cannelle", "quenele"],
"canivet":["canivet", "cnivet", "quanivet"],
"cantorbire":["quantorbire"],
"capadoce":["capadoce"],
"caradigan":["caradigan", "quaradigan"],
"carduel":["carduel", "quaraduel"],
"carlion":["carlion"],
"carrel":["carrel", "carreau", "quarrel", "quarriax"],
"carnant":["carnant"],
"carole":["carole", "queroles"],
"caroler":["caroler", "querolant", "querolent"],
"carrefor":["quarrefor", "carrefor", "carrefour", "quarefur"],
"cas2":["quas", "cas", "quasse"],
"casser":["casser", "quasser", "quassé", "quassees", "quassez", "quasse", "cassent", "quast"],
"carrer":["carrer", "quarré", "quarree", "quarrees", "quarrez"],
"carsenefide":["carsenefide", "tarsenesyde"],
"cartage":["cartage", "cartaige"],
"cartier":["quartier", "cartier", "cartiers", "quartiers"],
"ceintuir":["ceintur", "ceintuir", "ceinturs"],
"cause":["cause", "quauses"],
"caveron":["caveron", "caverons"],
"ceindre":["çaindre", "ceindre", "ceinte", "ceinz", "ceint", "ceingnent", "ceigniez", "ceingne"],
"ceinture":["ceinture", "ceintures"],
"ceinturete":["ceinturette", "ceinturete"],
"celee1":["celée", "celee"],
"celer1":["celer", "celers", "celé", "celee", "celez", "cele", "çoile", "celoit", "celot", "cela", "celerai", "celera", "celeront", "cele", "celasse"],
"celeement":["celeement", "celeemant"],
"celer2":["celé", "cielé", "celee", "cielee"],
"cendal":["çandal", "cendal", "cendax"],
"cendre":["çandre", "cendre"],
"cembel":["çanbel", "cembel", "cenbel"],
"cembeler":["çanbeler", "cembeler", "cenbeler", "cenbelant"],
"cenele":["cenele", "cenelle"],
"cener1":["cignier", "cener", "cingne"],
"cercele":["cercele", "cerceles"],
"cengle":["çaingle", "cengle", "sangle", "ceingles", "cengle", "cengles"],
"cercelet":["cercelet"],
"cerchier":["cerchier", "cercher", "chercher", "cerchant", "cerchié", "cerche", "cerchast"],
"cengler":["cengler", "ceinglent"],
"ceptre":["septre", "ceptre", "ceptres"],
"cercle":["cercle"],
"cert":["cert", "certe", "cerz"],
"cercler":["cercler", "cerclers"],
"cerf":["cer", "cerf", "cers"],
"certain":["certein", "certain", "certainne", "certains", "certeins"],
"certement":["certement", "certemant"],
"certainement":["certainement", "certeinement", "certainnemant ", "certeinnemant ", "certemant ", "certenemant"],
"cervel":["cervel"],
"cervele":["cervele", "cervelle"],
"cerviz":[" cerviz"],
"cervoise":["cerveise", " cervoise"],
"ceseire":["ceseire", "cesaire"],
"cesar":["cesaré", "cesar"],
"cesser":["cesser", "cesse", "cessent"],
"chace":[" chace"],
"chacëor":["chaceor", "chaceors"],
"chacier":["chacier", "chacent", "chacié", "chaciee", "chaciez", "chaz", "chaces", "chace", "chacent", "chaça", "chaceront", "chaçast"],
"chäeine":["chaaine", "chaene", "chäeine", "chaîne", "chaainne"],
"chaisne":["chasne", "chesne", "chaisne", "chêne", "chasnes"],
"chaillo":["chaillo", "caillou", "chaillot", "chailloz"],
"chainse":["chainse", "cheinse", "chainses"],
"chainsil":["cheinsil", "chainsil"],
"chaitiveté":["cheitiveté", "chaitiveté", "chétiveté", "chestiveté"],
"chalant":["chalan", "chalant"],
"chalemele":[" chalemele", "chalemelle", "chalemeles"],
"chalemeler":[" chalemeler", "chalemele"],
"chaitif":["chaitif", "chétif", "cheitif", "cheitis", "cheitive", "cheitives", "chestive"],
"chaloir":["chaloir", "chaler", "chalt", "chaut", "chaloit", "chalut", "chaille", "chausist", "chaussist"],
"chalonge":["chalenge", "chalonge"],
"chalongier":["chalur", "chalor", "chalors"],
"chamberiere":["chamberiere", "chambriere", "chanberiere"],
"chamberlenc":["chanbrelain", "chamberlenc", "chambellan", "chanberlains", "chamberlein"],
"chambrete":["chambrete", "chanbrete"],
"chamoiz":["quamois", "chamois", "camois", "quamois"],
"chambre":["chambre", "chanbre", "chanbres"],
"champagne":["chanpaingne", "champagne", "campagne"],
"chanpaingne":["chanpaingne", "chanpaigne"],
"chamoissier":["quamoissié", "chamoisier", "chamoiser", "quamoissiez"],
"champ":["champ", "chanp", "chans"],
"champaine":["canpane", "champaine", "quanpanes"],
"champchëu":["champchëu", "champcheu", "chanpcheü", "chanpcheüz"],
"chanpguin":["chanpguin"],
"champïon":["chanpion", "champïon", "champion", "champiun"],
"champir":["chanpir", "champir", "chanpiront", "chanpisse"],
"chandelier1":["chandeler", "chandelier", "chandeliers"],
"chandoile":["chandoille", "chandele", "chandoile", "chandoiles"],
"chancel":["chancel"],
"chanceler":["chanceler", "chancele", "chancelot"],
"chançon":["chançon", "chançun", "chanson", "chançons"],
"chanevaz":["chanevaz", " chanevas", "canevas", "chenevaz"],
"change":["change", "changes"],
"changëor":["changëor", "changeur", "changierres", "changeor"],
"changier":["changer", "changier", "changié", "changiee", "changiez", "change", "changiez", "chanjoit", "chanjoient", "chanja", "changerai", "changera", "chanjons", "changiez"],
"chanole":["chanole", "chenole"],
"chant2":["chant", "chanz"],
"chanter":["chanter", "chantant", "chanté", "chantee", "chante", "chantent", "chantoit", "chantoient", "chanta", " chantassent"],
"chape":["chape", "chapes"],
"chanvre":["chanve", "chanvre"],
"chapelain":["chapelain", "chapelains"],
"chapele":["chapele", "chapelle"],
"chapel2":["chapel", "chapeau", "chapele"],
"chapelier1":["chapelier", "chapeler"],
"chaperon":["chaperon", "chaperons"],
"chaple":["chaple", "chaples"],
"chapler":["chapler", "chapeler", " chaple"],
"chaplëiz":["capleiz", "chaplis", "chapleïz"],
"char1":["char", "chars"],
"char2":["char", "charz"],
"chapon":["chapon"],
"charaie":["charoie", "charaie", "charaies"],
"charbon":["charbon", "charbons"],
"charge":["charge"],
"charbonee":["charbonnee", "charbonee", "charbonees"],
"charbonier1":["charbonnier", "charboner", "charbonier"],
"chardenal":["chardonal", "chardenal", "cardinal", "chardonax"],
"chargier":["charger", "chargier", "chargié", "chargiee", "chargiees", "chargiez", "charge", "chargent"],
"charitable":["charitable", "charitables"],
"charité":["charité", "charitez"],
"charjable":["chargeable", "charjable"],
"charme1":["charme", "charmes"],
"charme2":["charme", "charmes"],
"charmer":["charmer", "charmez"],
"charre":["chare", "charre"],
"charrete":["charette", "charrette", "charrete", "charretes"],
"charpenter":["charpanter", "charpenter", "charpantez"],
"charpentier":["charpantier", "charpentier", "charpenter", "charpantiers"],
"calcedor":["calcedor", " charquedon"],
"charreter":["charreter", "chareter", "charetter", "charretez", "charretent"],
"charretier":["charretier", "charetier", "charretiers"],
"charreton":["charreton", "chareton", "charetun", "charretons"],
"charriere":["charriere"],
"chas":["chas"],
"chasse":["chasse", "case", "châsse", "chasses"],
"chaste":["chaste"],
"chastel":["chastel", "chastiax", "château"],
"chastelain":[" chastelain", "châtelain", "chastelains"],
"chastelet":["châtelet", "chastelet"],
"chasti":["chasti"],
"chastiier":["chastïer", "chastiier", "chastier", "chastiant", "chasti", "chasties", "chastie", "chastïent", "chastoient", "chastia", "chastiez", "chastiez"],
"chatel":["cheptel", "chatel", "chetel"],
"chastrer":["chastrer", "châtrer", "chastrez"],
"chasuble":["chasuble"],
"chat":["chat", "chaz"],
"chauce":["chausses", "chauce", "chauces"],
"chaucëure":["chaucëure", "chalceure", "chauçure", "chauceüre"],
"chauciee":["chaucie", "chalciee", "chaucee", "chaussée", "chauciee"],
"chaucier1":["chalcier", "chaucer", "chausser", "chaucier", "chaucié", "chauciees", "chauciez", "chauce", "chauça", "chaucierent"],
"chaude":["chaut", "chaude"],
"chauf":["chalf", "chauf", "chaus", "chauve", "chauz"],
"chaufer":["chaufer", "chauffer", "chaufast", "chaufé"],
"chaut":["chaut", "chaude", "chaudes", "chaut", "chauz", "chax"],
"chauz1":["chals", "chaux", "chauz"],
"chëance":["cheance", "chëance", "chance"],
"chemin":["chemin", "chemins"],
"cheminee1":["cheminée", "cheminee", "cheminees"],
"cheminel":["cheminal", "cheminel"],
"cheminer":["cheminer", "cheminant", "chemine", "cheminent", "cheminoient", "cheminerent"],
"chemise":["chemise", "chemises"],
"chenu":["chanu", "chenu", "chenue", "chenuz"],
"chëoir":["chëoir", "chair", "cheoir", "cheoite", "cheoiz", "cheü", "cheüe", "cheües", "cheüz", "chiet", "chieent", "cheoit", "cheoient", "chaï", "cheï", "cheïrent", "cheez", "chiee", "cheïst", "cheïssent"],
"cheval":["cheval", "chevax"],
"chevalerez":["chevaleresce", "chevalerez", "chevaleresse"],
"chevalerie":["chevalerie", "chevaleries"],
"chevalier":["chevaler", "chevalier", "chevaliers"],
"chevauchiee":["chevauchiee", "chevalchee", "chevauchée", "chevalchiee"],
"chevauchier":[" chevauchier", "chevalchier", "chevalcher", "chevaucher", "chevalchant", "chevauchant", "chevalchié", "chevauchié", "chevalche", "chevauche", "chevalchent", "chevauchent", "chevalchoit", "chevauchoit", "chevalchoient", "chevalcha", "chevalchierent", "chevalchiez", "chevauchiez"],
"chevecine":["chevecine"],
"chevel":["chevol", "cheveil", "chevel", "cheveu", "chevols", "chevos", "chevox"],
"cheveçaille":["cheveçaille"],
"chevece":["chevesce", "chevèce", "chevece"],
"chevelet":[" chevelet", "chevolet"],
"chevelu":["chevelu", "chevelue"],
"chevestre":["chevestre", "chevêtre", "chevoistre"],
"chevir":["chevir"],
"chevrueil":["chevrueil", "cheverel", "chevrel", "chevriax"],
"chiche1":["chiche", "chiches"],
"chief1":["chef", "chief", "chié", "chiés"],
"chien":["chen", "chien", "chiens"],
"chienes":["chienes", "chanes", "chenes", "chienes"],
"chienet":["chiené", "chienet", "chenet", "chiennez"],
"chier":["cher", "chier", "chiere", "chieres", "chier", "chiers"],
"chiere":[" chere", "chère", "chiere"],
"chierement":["cherement", "chierement", "chèrement", "chieremant"],
"chierir":["cherir", "chierir", "chérir"],
"chierté":["cherté", "chierté"],
"chievre":["chevre", "chèvre", "chievre"],
"chöe":["chöe", "choe", "choue"],
"chöete":["çüete", "chöete", "choete", "chouette", "çuete"],
"chois":["choix", "chois"],
"chose":["chose", "choses"],
"choisir":["choisir", "choisi", "choisissiez"],
"choser":["choser", "chose", "chosent"],
"ciel":["ciax", "ciel"],
"cierge":["cirge", "cierge", "cierges"],
"cime":["cime"],
"cimetiere":["cemetire", "cimetiere", "cemetires"],
"cire":["cire"],
"cisemus":["cisemus"],
"cingler":["cinglant", "ceingle", "cengler", "cingler"],
"cité":["cité", "citez"],
"cive":["cive"],
"clamadeu":["clamadeu", "clamadex"],
"clamer":["clamer", "clamee", "clamez", "claim", "clain", "clainmes", "claimme", "clainme", "claiment", "clainment", "clamoit", "clamoient", "clama", "clamerai", "clameroit", "clainme", "clamez", "claint", "clamasse", "clamast"],
"clarissant":["clarissant", "clarissanz"],
"clamor":["clamur", "clameur", "clamor"],
"clarté":["clarté", "clartez"],
"clef":["clé", "clef"],
"cler":["clair", "cler", "clere", "cleres", "clers"],
"clerc":["clerc", "clers"],
"clerement":["clairement", "clerement", "cleremant"],
"cliges":["cligés", "clygés"],
"clergie":["clergie"],
"clerjon":["clerçon", "clerjon", "clergeon", "clerdon"],
"clice1":["clisse", "clice", "clices"],
"cliner":["cliner"],
"clo":["clo", "clou", "clos"],
"cloche":["clokke", "cloche", "cloches"],
"cöardie":["cöardie", "couardie", "coardie"],
"clochier":["clochier", "clocher", "cloiche", "clochoient"],
"clofichier":["clofichier", "clouficher", "closfichiee"],
"clore":["clore", "clos", "close", "closes", "clost", "clot"],
"cöart1":["couard", "cöart", "coarde", "coart", "coarz"],
"cöardise":["coardise", "cöardise", "couardise"],
"cöart2":["coarz"],
"coche1":["coche"],
"cocodril":["corcatrille", "cocodril", "crocodile", "corquatrilles"],
"cöe":["cöe", "queue", "cowe", "coe"],
"cofre":["coffre", "cofre", "cofres"],
"coguillanz":["coguillanz "],
"coi1":["coi", "coie", "coiz", "quoi", "quoie"],
"coife":["coife", "coiffe"],
"coi3":["cuoi", "coi", "quoi"],
"coigniee":["coigniee", "coigné", "cognée", "coigniees"],
"coillir":["cueillir", "coillir", "coillie", "quialt", "quiaut"],
"cointe":["cointe", "cointes"],
"cointement":["cointement", "cointemant"],
"cointise":["cointise"],
"coisier":["coisier", "coiser", "coise"],
"coite":["cuite", "coite"],
"col":["cou", "col", "cos"],
"colee":["colée", "colee", "colees"],
"colëiz":["coleïz", "couleis", "coulis", "coleïces"],
"coler1":["coler", "couler", "colant", "colanz", "colé", "colee", "colez", "cole", "colent", "coloit", "coloient"],
"colom":["colom", "colum", "colon", "colons"],
"colombe2":["colome", "colombe", "columpne", "colonne", "colomes"],
"coloingne":["coloigne"],
"coler3":["coler", "collier"],
"color":["colur", "couleur", "color", "colors"],
"colorer":["colorer", "colurer", "coloré", "coloree", "colorez"],
"comandement":["commandement", "comandemant", "comandemanz"],
"comandëor":["comandeor", "commandeur", "comanderre", "commandeur", "comanderres"],
"comander":["commander", "comander", "comandé", "comandee", "comandees", "comandez", "comant", "comande", "comandez", "comandent", "comandoit", "comandai", "comanda", "comandera", "comandez", "comant"],
"comant":["comand", "comant", "command"],
"combatëor":[" conbateor", "combatëor", "combateor", "combatur"],
"combatre":["combatre", "combattre", "conbatre", "conbatant", "conbatanz", "conbatu", "conbatuz", "conbat", "conbatent", "conbatoit", "conbatrai", "conbatra", "conbatrons", "conbatront", "conbatroie", "conbate", "conbatent", "conbatessiez"],
"comble1":["conble", "comble"],
"combler":["conblé", "combler", "conblez"],
"comé":["comé"],
"comencier":["comencier", "comencer", "comancier", "comancié", "comanciee", "comance", "comancent", "comançoit", "comançoient", "comança", "comancierent", "comancerai", "comancera", "comanceront", "comanciez"],
"comfaitement":["cumfaitement", "confaitemant", "confeitemant", "confeitement"],
"compagne":["compagne", "compaigne", "conpaigne", "conpaignes", "conpaingne"],
"compagnie":["compaignie", "compagnie", "conpaignie", "conpaingnie", "conpeignie"],
"compagnon":["compagnon", "compaignon", "conpaignon", "conpaignons", "conpaingnons", "conpainz", "conpeignons"],
"comparer2":["comparer", "comperer", "comprer", "conparer", "conparé", "conparee", "conper", "conpere", "conperent", "conparra", "conparroiz", "conparriez", "conpert"],
"compas":["compas", "conpas"],
"compasser":[" compasser", "conpasser", "conpassees", "conpassez"],
"complaindre":["conplaindre", "complaindre", "compleindre", "conplaint"],
"comunaument":["comunaument", "communalment", "communalement", "comunalmant"],
"comune":["commune", "comune"],
"complainte":["complainte", "compleint", "conplainte", "conplaintes"],
"complie":["conplies", "complie", "complie", "complies", "conplie"],
"comun":["commun", "comun", "comune"],
"comunement":["communement", "comunemant", "communément"],
"comuniier":["comeniier", "comuniier", "communier", "communier", "communer", "comeniez"],
"comunïon":["comunïon", "communion", "communiun", "comenion"],
"concevoir":["concevoir", "conceivre", "conçut"],
"conduire":["conduire", "conduit", "condui", "conduirai", "conduie", "conduist", "conduit", "conduient", "conduisoie", "conduisoit", "conduiroient", "conduient"],
"concordance":["concordance"],
"conduit":["conduit", "conduiz"],
"conestable":["connestable", "connétable", "conestable", "conestables"],
"confès":["confés"],
"confesse":["confesse"],
"confesser":["confesser", "confesse"],
"confessïon":["confessïon", "confession"],
"confire2":["confire", "confite"],
"confondement":["confondement", "confondemant"],
"confondre":["confondre", "confondu ", "confondue", "confonduz", "confont", "confondent", "confonde "],
"confort":["confort", "conforz "],
"conforter":["conforter", "conforté", "conforte", "conforte", "confortez", "confort", "confortant", "confortent"],
"confus1":["confus"],
"congié":["congé", "congié", "congiez"],
"conin":["conin", "connin", "conins"],
"conjointure":["conjoncture", "conjointure"],
"conjöir":["conjöir", "conjoir", "conjouir", "conjoïr", "conjoï", "conjoïz", "conjot", "conjoent", "conjoient", "conjoïssent", "conjoïssoit", "conjoï", "conjoie"],
"conoissance":[" connaissance", "conoissance", "conuissance", "conuissances"],
"conoistre":["connaître", "conoistre", "conuistre", "coneü", "coneüe", "coneüz", "conois", "conuis", "quenuis", "conoist", "conuist", "conuissiez", "conoissent", "conuissent", "conuissoit", "conoissoiez", "conoissoient", "conuissoient", "conui", "quenui", "conut", "quenut", "coneüstes", "queneüstes", "conurent", "conoistroie", "conuistroit", "conuis", "conoisse", "conuisse", "conoisse", "conuisse", "coneüsse", "coneüst", "coneüssent"],
"conjurement":["conjuremant", "conjurement", "conjuremanz"],
"conjurer":["conjurer", "conjuré", "conjur", "conjure"],
"conquerre":["conquerir", "conquere", "conquérir", "conquerre", "conquis", "conquise", "conquier", "conquiert", "conquist", "conquerra", "conquerroie", "conqueïsse", "conqueïst"],
"conquester":["conquester"],
"conroi":["conrai", "conroi"],
"conscïence":["conscïence", "conscience", "conciance"],
"conrëer":[" conrëer", "conreier", "conréer", "conreer", "conreez", "conroie", "conreez"],
"conseil":["conseil", "consauz", "consoil"],
"conseillier1":["conseiller", "conseillier", "consellier", "conseilliez", "conseillié", "consellié", "consoil", "consoilles", "consoille", "consoillent", "conselloit", "conseilla", "conseillierent", "conseilleroie", "consoille", "consoilles", "conseilliez", "conselliez", "conselliez", "conseillasse"],
"conseillier2":[" conseiller1", "conseillier"],
"consent":["consance", "consent", "consant"],
"consentir":["consantir", "consentir", "consantir", "consant", "consantiromes", "consante"],
"consiree":["consirree", "consiree", "consirée", "consirre"],
"consirer":[" consirrer", "consirer"],
"conte1":["comte", "conte", "contes", "cuens"],
"conte2":["conte", "contes"],
"consivre":["consiure", "consivre", "consuivre", "consivant", "consilt", "consiust"],
"contenance":[" contenance", "contenances"],
"contençon":["contençon", "contention", "contançon"],
"contenement":["contenemant", "contenement"],
"contenir":["contenir", "contandra", "contendroiz", "contanroie", "contien", "contenez", "contenist", "contiens", "contient", "contenez", "contint", "contenuz"],
"conter":["conter", "contant", "conté", "contee", "contees", "contez", "cont", "conte", "content", "contoie", "contoit", "conta", "conterai", "conteron", "conteroiz", "conteroie", "conteroit", "contez", "cont", "contasse"],
"contrait":["contrait", "contret"],
"contrariier":["contraliier", "contrariier", "contraliant"],
"contesse":["comtesse", "contesse", "contesses"],
"contraire":["contreire", "contraire", "contraires"],
"contrarïos":["contraliieus", "contrarïos", "contrarios", "contrarious", "contralieus", "contrarieux"],
"contratendre":["contr'atandre", "contratendre", "contrattendre", "contratendons", "contreatendissent"],
"contredire":["contredire", "contredit", "contredite", "contredi", "contredïent", "contredisoit", "contredis", "contredist", "contredeïstes", "contredira", "contrediroie", "contrediroit", "contreïst", "contredeïssent "],
"contredit":["contredit", "contrediz"],
"contrester":["contrester"],
"contretenir":["contretenir", "contretenuz", "contretient", "contretint"],
"contree":["contrée", "contree", "contrees"],
"contrefaire":["contrefaire", "contrefeire", "contrefere", "contrefetes", "contrefez"],
"contrueve":["controve", "contrueve"],
"convoiier":["conveiier", "convoiier", "conveer", "convoyer", "convoier", "convoiant", "convoié", "convoiee", "convoiez", "convoie", "convoient", "convea", "convoia", "convoierent", "convoiera", "convoit"],
"convers2":["convers"],
"converser":["converser", "converse", "conversa", "conversé"],
"cope1":["cope", "coupe"],
"copel2":["pecol", "copel", "quepol", "pecul", "pécol", "quepouz"],
"çoper":["çoper", "choper", "chopper", "çope", "çopa"],
"cor2":["corn", "cor", "corz"],
"corage":["courage", "corage", "corages", "coraige"],
"coper":["couper", "coper", "colpé", "colpee", "colpees"],
"coraille":["coral", "coraille"],
"corajos":["corajos", "corajus", "corageus", "corageuse"],
"corbel":["corbel", "corbeau"],
"corir":["corir", "courir", "coure", "corre", "corant", "corrant", "corranz", "coreü", "cort", "corent", "coroient", "corrut", "corroie", "cor", "coroit", "corut", "corrurent"],
"corde":["cord", "corde", "cordes"],
"cordele":["cordele", "cordelle"],
"corëor":["coreor", "corëor", "coureour", "coureur", "coreors"],
"corgiee":["corgie", "curgee", "courgée", "corgiee", "corgiees"],
"corjon":["corion", "corjon"],
"corneille1":["cornoille", "corneille", "cornoilles"],
"cornoalois":["cornoalois"],
"cornu":["cornu"],
"corneillier":["corneillier", "cornouiller", "cornelier"],
"corner":["corner", "cornee", "cornent"],
"cornix":["corniex", "cornix"],
"cornoaille":["cornoaille"],
"coroie":["coroie", "coreie", "courroie", "corroie", "corroies"],
"corone":["couronne", "corone", "corones", "querone"],
"coronement":["coronemant", "coronemen", "couronnement"],
"corque":["corques"],
"coroner":["couronner", "coroner", "coroné", "coronee", "coronent", "corona", "coronast"],
"corrocier":["corrocier", "couroucier", "corucer", "courroucer", "correcier", "correciez", "corroz", "corroces", "corroce", "correça", "correceroie"],
"corrompre":["corrompre", "corrumpre", "corronpre"],
"corroz":["corroz", "corus", "courroux"],
"cors1":["corps", "cors"],
"cors2":["cours", "cors"],
"corsage":["corsage", "corssage"],
"cort1":["cour", "cor", "cort", "corz"],
"cort2":["court", "cort", "corte", "cortes", "cortes", "corz"],
"cortine":["cortine", "courtine1", "cortines"],
"cortois":["cortois", "corteis", "courtois", "cortoise"],
"cortoisement":["cortoisement", "courtoisement", "cortoisemant"],
"cortoisie":["corteisie", "cortoisie", "courtoisie"],
"cosdre":["cosdre", "coustre", "coudre", "queudre", "cosue", "cousue", "cost", "queust"],
"cosin":["cousin", "cosin", "cosine", "cosins", "cousin", "cousine"],
"cost2":["cost", "coût", "coust"],
"costantin":["costantin"],
"costantinoble":["costantinoble"],
"coste2":["côte", "coste"],
"costé":["costé", "costez"],
"coster1":["coster", "coûter", "couster", "costé", "coste", "costa", "cost"],
"costoiier":["costoiier", "costoier", "costeier1", "côtoyer", "costoiant", "costoie"],
"costume":["coustume", "custume", "costume", "costumes"],
"costumier":["custumer", "coutumier", "costumier", "costumiere", "costumiers"],
"costure":["cousture", "costure", "costures"],
"cotele":["cottelle", "cotele"],
"cotoatre":["cotouatre"],
"couche":["colche", "couche"],
"cote1":["coute", "code", "codes", "cote", "cotes"],
"cote2":["cotte", "cote", "cotes"],
"couchier":["coucher", "colchier", "couchier", "colchiez", "couchié", "couchiee", "couchiez", "couche", "colchent", "couchent", "colchierent", "couchast", "couchierent", "couchié", "colcherez", "coucheroiz", "colchassent"],
"coup1":["coup", "colp", "cop", "cos"],
"coupable":["coupable", "corpable"],
"coupe":["coupe", "coulpe", "colpe", "corpe", "corpes"],
"coute":["coute", "coilte", "coulte", "coste", "costes", "coute", "coutes"],
"coutel":["cotel", "couteau", "costel", "coutel"],
"covenable":["convenable", "covenable"],
"covenance":["covenance", "convenance"],
"covenir":["convenir", "covenir", "covient", "covenoit", "covint", "convenra", "covandra", "covanra", "covendra", "covenra", "covandroit", "covanroit", "covendroit", "covaigne ", "covaingne ", "coveigne ", "coveingne", "covenist"],
"covenant":["covenant", "covenanz"],
"covent1":["covent", "convent", "covant", "covanz"],
"covent2":["covant", "covent", "couvent"],
"cover":["cover", "couver", "cove", "covast"],
"covertement":["covertement", "covertemant"],
"coverture":["couverture", "coverture", "covertor", "covertors"],
"covir":["covir", "covi", "3 :[ covi"],
"covoitié":["coveité", "covoité", "covoitié"],
"covine":["covine"],
"covoitier":["coveitier", "convoiter", "covoitier", "covoitié", "covoitiez", "covoit", "covoite", "covoitiez", "covoitent", "coveita"],
"covoitos":["coveiteus", "covoitos", "covoitos", "coveitus", "convoiteux", "covoiteuse"],
"covoitise":["coveitise", "covoitise"],
"covrir":["covrir", "coverir", "couvrir", "covert", "coverte", "covertes", "coverz", "coevre", "cuevre", "cuevrent", "covroient", "covri", "covrez"],
"craisse":["greisse", "craisse", "graisse", "gresse"],
"crapos":["crapeus", "crapos", "crapeux", "grapeus"],
"cras":["gras", "cras"],
"crëance":["creance", "crëance", "créance"],
"crëant":["crëant", "créant1", "creant", "creanz"],
"crëante":["crëante", "creante"],
"crëanter":["crëanter", "granter", "créanter", "creanter", "creanté", "creant", "creante", "creantai", "creanta", "creantez"],
"crenu":["crenu"],
"crenel":["crenel", "créneau", "creniax"],
"cresme":["cresme", "cresm", "chrisma", "chrême", "chresme"],
"crester":["crester", "crêter", "cresté", "creste"],
"crestiien1":["crestiien", "crestien", "crestiens"],
"crestïenté":["crestïenté", "chrestienté", "cristienté", "crestianté", "crestiantez"],
"crestiien2":["crestiien", "cristien", "crestien", "crestiene", "crestiens"],
"cri":["cri", "criz"],
"crever":["crever", "crevé", "crevee", "crevez", "crieve", "crievent", "creva", "creverent"],
"crïator":["crïator", "creator", "creatur", "créateur", "criator"],
"crïature":["creature", "crïature", "créature", "criature"],
"criembre":["craindre", "criembre", "criendre", "crienbre", "cremu", "cremuz", "criem", "crien", "criens", "crient", "criement", "cremoit", "crienbroie"],
"crieme":["creme", "crieme", "criemme"],
"crïer1":["crïer", "creer", "créer", "cria"],
"crïer2":["crïer", "crier", "criers", "criant", "criee", "criez", "crie", "crïent", "crioit", "crioient", "criai", "cria", "crierent", "crieroit", "criast"],
"crin":["crine", "crin", "crins"],
"crisolite":["crisolite", "chrysolithe", "crisolites"],
"crist":["crist", "criz"],
"cristal":["crestal", "cristal", "cristauz", "cristax"],
"croc2":["croce", "croc", "cros"],
"croce":["crosse", "croce", "croces"],
"croie":["creie", "craie", "croie"],
"croire":["creire", "croire", "croirre", "creü", "creüe", "creüz", "croi", "croiz", "croit", "creez", "croient", "creoie", "creoit", "creiez", "crui", "crut", "creümes", "crurent", "cresrai", "crerra", "cresra", "cresroiz", "crerroit", "croi", "creez", "croies", "croie", "creüsse"],
"croisete":["croisete", "croisette", "croisetes"],
"croisier":["croisié", "croizer"],
"croisillié":["croisillié", "croisilliee"],
"croiz":["crois", "croix", "croiz"],
"croissir":["croissir", "croissent"],
"croistre":["croistre", "creistre", "creü", "creüe", "creüz", "croist", "crut", "crurent", "crestrai", "crestra", "crestroit", "creüst"],
"croler":["croller", "crouler", "croler", "crosé", "croslé", "crosle", "croslent"],
"crot":["crot", "croit"],
"cru":["cru", "crue", "crues"],
"crüauté":["cruelté", "crüauté", "cruauté", "crualté"],
"crucefiier":["crocefiier", "crucefiier", "crucefier", "crucifier", "crocefiez"],
"crope":["croupe", "crope", "cropes"],
"croser":["croser", "creuser"],
"çucre":["sucre", "çucre"],
"cuer2":["coer", "coeur", "cuer", "cuers"],
"crucefis":["crocefis", "crucefis", "crucifix", "crocefis"],
"crüel":["crüel", "cruel", "cruex"],
"crüelment":["cruelment", "cruelement", "cruellement", "cruelmant"],
"cuerpous":["cuerpous"],
"cuidier":["cuider", "cuidier", "cuit", "cuides", "cuide", "cuidiez", "cuident", "cuidoie", "cuidoit", "cuidoient", "cuidai", "cuida", "cuiderent", "cuiderai", "cuidera", "cuideront", "cuideroie", "cuideroit", "cuidasse", "cuidast", "cuidereiez"],
"cuir":["cuir", "cuirs"],
"cuire":["cuire", "cuit", "cuites", "cuiz", "cuist"],
"cuiriee2":["curée", "cuiriee"],
"cuisine":["cuisine", "cuisines"],
"cuisencenos":["cuisencenos", "cusençunnous", "cuisançonneux", "cusançoneus"],
"cuisençon":["cusencion", "cusançon "],
"cuisse":["cuisse"],
"cuivre1":["cuivre", "cuevre", "coivre"],
"cuivre2":["cuivre"],
"cuve":["cuve", "cuves"],
"culvert":["cuivert", "culvert", "cuiverz"],
"cure":["cure"],
"däerrain":["derriien", "däerrain", "dereiner", "derrain", "darriens", "dasreainne", "derriens", "desreien", "desrien"],
"daim":["daim", "dains"],
"damage":["damage", "dommage", "domage", "domages", "domaige", "domaiges"],
"damagier":["damagier", "damager", "dommager", "domagier", "domagié", "domageroient"],
"dame":["dame", "dames"],
"damoisele":["dameisele", "damoisele", "dameisele", "dameiseles"],
"damoisel":["damoisel", "dameisel", "dameisiax"],
"dan2":["dant", "damedeu", "damedex", "dan", "danz"],
"dance":["danse", "dance", "dances"],
"dancier":["dancer", "danser", "dancier", "dancent"],
"dangier":["danger", "dangier", "dongier"],
"danois":["denois", "daneis", "danisk", "danois", "denoises"],
"dart":["dard", "dart", "darz"],
"date2":["date", "dade", "datte", "dates"],
"davi1":["davi"],
"davi2":["daviz"],
"dé1":["de", "dé", "dez"],
"debatre":["débattre", "debatre", "debatant", "debatuz", "debat", "debatent"],
"deboissier":["deboissier", "deboissiees", "deboissent", "deboisse"],
"debonairement":["debonairement", "débonnairement", "deboneiremant", "deboneremant", "debonerement"],
"debonaire":["débonnaire", "debonaire", "deboneire", "debonere", "deboneres"],
"debonaireté":["deboneireté", "debonaireté", "débonnaireté", "debonereté"],
"deboter":["deboter", "debuter", "débouter", "debote"],
"debrisier":["debrisier", "debriser", "debrise"],
"decevoir":["deceivre", "décevoir", "decevoir", "deçoivre", "decevant", "deceü", "deceüe", "deceüz", "deçoit", "deçoivent", "deçut", "deçurent", "deçoive", "deceüst"],
"dechëoir":["decheoir", "decheeir", "dechair", "déchoir", "decheoir", "decheü", "decheües", "decheez"],
"declin":["déclin", "declin"],
"decliner":["decliner", "décliner", "declinant"],
"decoler1":[" décoller", "decoler", "decolez"],
"decorir":["decorre", "decorir", "decure", "décourir", "decoroient"],
"deduire":["déduire", "deduire", "desduire", "deduit", "deduit", "deduiez", "deduient", "deduisoient", "dedui", "deduiez"],
"defendre":["deffandre", "defendre", "défendre", "desfandre", "desfandu", "desfandue", "desfanduz", "desfant", "desfandent", "desfandoit", "desfandeiez", "desfandi", "desfandrai", "desfandra", "desfandroiz", "desfende", "desfande", "desfandent"],
"deduit":["déduit", "deduit", "deduiz"],
"definaille":["definaille"],
"defens":["deffans", "defense", "desfans"],
"defense":["deffanse", "defense", "défense", "desfanse", "desfanses", "desfansse", "desfansses"],
"definer1":["definer", "définer"],
"degré":["degré", "degrez"],
"degrocier":["degrocier", "dégrocier", "degroces"],
"definer2":["definer", "define"],
"defolëiz":["defoleis", "defoleïz"],
"defoler":["defoler", "defuler", "défouler", "defolee"],
"degoter":["degoter", "degotez", "degote", "dégoutter"],
"deguenchir":["deganchir", "deguenchir", "deguanchir", "deganchi"],
"deignier":["deignier", "digner", "degnier", "daigner", "daing", "daigne", "daingne", "deingne", "daigniez", "daingniez", "deigniez", "daignent", "deignent", "deingnoit", "deignai", "daignas", "deigna", "deignames", "deignastes", "deignierent", "daingnera", "daigneroie", "daigneroit", "deigneroit", "daignierent", "deigneriez", "daigneroie", "daigneroit", "deigneroit", "daingnast", "deignast", "deingnast"],
"dehachier":["dehachier", "dehacher", "déhacher", "dehachiee", "dehachiez"],
"dehé":["dehé", "deshait", "dahait", "dahé", "dahez"],
"deintié":["deintié", "daintié"],
"dëité":["deité", "déité", "deïté", "deïtez"],
"dejangler":["dejangler", "degengler", "degenglent"],
"dejeter":["degeter", "dejeter", "déjeter", "degiete"],
"delai":["délai", "delai", "delais"],
"delaie":["délaie", "delaie"],
"delaiement":["délaiement", "delaiemant"],
"delaiier1":["delaier", "delaiier", "deleer", "délayer", "delaiant", "delaie", "delaiez", "delaient", "deloient", "delaiez", "delait"],
"delice":["délice", "delice"],
"deliié":["delïé", "deliié", "délié", "delié", "deliee", "deliees", "deliez"],
"delit2":["délit", "delit", "deliz"],
"delitable":["delitable", "delitables"],
"delitier":["deliter", "delitier", "delit", "delite", "delitoit", "delit"],
"delivrance":["délivrance", "delivrance"],
"delivre":["délivre", "delivre", "delivres"],
"delivrement":["delivrement", "delivremant"],
"delivrer":["deliverer", "délivrer", "delivrer", "delivré", "delivree", "delivrees", "delivrez", "delivre", "delivra", "deliverras", "deliverra", "delivrera", "delivre", "delivrez"],
"deluge":["deluvie", "déluge", "deluge"],
"demaine":["demaine", "demeine", "domaine", "demainne"],
"demainement":["demeinement", "demainnemant"],
"demande":["demande"],
"demander":["demander", "demender", "demandé", "demandee", "demande", "demandez", "demandoit", "demandent", "demandai", "demanda", "demandames", "demandees", "demandez", "demant", "demandes", "demandas", "demandastes", "demanderent", "demanderai", "demandera", "demanderoiz", "demanderoit", "demandez", "demant", "demandiez", "demandasse", "demandast", "demandesiez"],
"demener":["démener", "demener", "demenant", "demené", "demenee", "demenez", "demain", "demainne", "demenez", "demainnent", "demenoit", "demenoient", "demena", "demenerent", "demaint"],
"dementer":["dementer", "demantee", "demanter", "demante", "demantent", "demantoient", "demantast"],
"demi":[" demi", "demie", "demis"],
"demincier":["demincier", "demincer", "démincer", "demince"],
"demorance":["demurance", "demeurance", "demorance"],
"demore":["demure", "demeure", "demore"],
"demoree":["demuree", "demoree", "demeurée", "demoree"],
"demorer":["demorer", "demeurer", "demurer", "demorant", "demoré", "demoree", "demor", "demore", "demorez", "demorent", "demorerent", "demorasse", "demorast", "demora", "demort", "demorastes"],
"demostrance":["demostrance", "demonstrance", "demustrance", "démontrance"],
"denree":["danree", "denree", "denrée"],
"dent":["dent", "dant", "danz"],
"departir":["départir", "departir", "departirs", "departi", "departie", "departies", "departiz", "depart", "departez", "departent", "departoit", "departoient", "departi", "departi", "departirent", "departirai", "departira", "departiroiz", "departiront", "departe"],
"demostrer":["demostrer", "demustrer", "démontrer"],
"denier":["denier", "deniers"],
"depecier":["despecier", "depescer", "dépecer", "depecier", "depecié", "depeciee", "depeciez", "depiece", "depiecent"],
"dependre":["depandre", "dependre", "dépendre", "depandent"],
"deplaindre":["deplaindre", "depleindre", "déplaindre", "deplaignent"],
"deport":["desport", "déport", "deport", "deporz"],
"deporter":["desporter", "déporter", "deporter", "deporté", "deport", "deporte", "deportent", "deportoient", "deport", "deport"],
"depriier":["deproier", "depriier", "déprier", "deprier"],
"deputaire":["deputaire", "députaire", "députère", "deputaire"],
"deraisne":["desresne", "dereine", "déraisne"],
"deraisnier":["desresnier", "deraisnier", "dereiner", "desreniee", "desresnié", "desresniee", "desresne", "desresneroit", "desraist"],
"faire": ["feire", "faire", "fere", "feisant", "fait", "faite", "faites", "feit", "feite", "feites", "fet", "fete", "fetes", "fette", "fez",
          "fais", "faz", "fez", "fait", "feit", "fet", "feisons", "faites", "feites", "fetes", "font","feisoie", "feisoies", "feisoit",
          "feisiez", "feisoient", "fis", "feïs", "fist", "feïmes", "feïsmes", "feïstes", "firent", "ferai", "feras", "fera",
          "ferons", "ferez", "feroiz", "feront", "feroie", "feroies", "feroit", "feriemes", "feriens", "fereiez", "feriez", "feroiez",
          "feroient", "fai", "fei", "feisons", "faites", "feites", "fetes", "face", "faces", "faciez", "façoiz", "facent",
          "feïsse", "feïsses", "feïst", "feïsiez", "feïssent", "feïssient"],
"vïande": ["vïande", "viande"],
"vice": ["vice", "vices"],
"victoire": ["victorie", "victoire"],
"vie": ["vie", "vies"],
"vieil": ["vieil", "vieux", "vialz", "viel", "vielle"],
"vieillece": ["veillesce", "vieillece", "viellesce", "vieillesse", "vellesce"],
"vïele": ["vïele", "vielle", "viele", "vieles"],
"vïeler": ["vïeler", "vieller", "vieler", "viele"],
"vieillart": ["vieillard", "viellard", "veillart", "veillarz"],
"vïenois": ["vïenois", "vienais", "vienois"],
"viez": ["vies", "viel2", "viez"],
"vif": ["vif", "vis", "vive", "vives"],
"vigile": ["vigile", "vigiles"],
"vigne1": ["vigne", "vingne", "vingnes"],
"vignoble": ["vignoble", "vignobles"],
"vigoros": ["viguereus", "vigoros", "vigrus"],
"vil1": ["vil", "vix"],
"vilain": ["vilein", "vilain", "vilainne", "vilains", "vileinne", "vileins"],
"vilainement": ["vilainement", "vilainnemant", "vileinnemant", "vilenemant"],
"vile": ["ville", "vile"],
"vilener": ["vilener", "vilena"],
"vilment": ["vilement", "vilemant", "vilmant"],
"vilenie": ["vileinie", "vilenie", "vilenies"],
"viltance": ["viltance", "viltence"],
"vïolete1": ["violete", "vïolete", "violette", "violet", "violetes"],
"vilté": ["vileté", "vilté"],
"vin": ["vin", "vins"],
"virge": ["virgine", "virge"],
"vis1": ["visavis", "vis"],
"vis2": ["vis"],
"visiter": ["visiter"],
"vistement": ["vistement", "vistemant"],
"vitaille": ["vitaille", "vitailles"],
"vivre1": ["vivre", "vivant", "vivanz", "vescu", "vif", "viz", "vit", "vivoit", "vesqui", "vivrai", "vivra", "vives",
           "vive"],
"viz": ["vis", "viz"],
"vo": ["vo", "vou", "voeu", "veu", "veuz", "vouz"],
"vöer1": ["voer", "vöer", "vouer", "voé", "veu"],
"voiage": ["voiage", "veage"],
"voie": ["veie", "voie", "voies"],
"voiier1": ["voiier", "voier"],
"voile1": ["veile", "voile"],
"voir": ["veir", "voir", "voire", "voires", "voirs"],
"voire1": ["veire", "voire"],
"voire2": ["voir", "veire", "voire"],
"voirement": ["veirement", "voirement", "voiremant"],
"voirre": ["verre", "veire", "voirre", "voirres"],
"voisdie": ["veisdie", "voisdie", "veidie", "voidie"],
"voisin": ["voisin", "veisin", "veisine", "veisins"],
"voiz": ["voix", "voiz"],
"vol": ["vol"],
"volage1": ["volage"],
"volenté": ["volanté", "volantez", "volenté", "volentez"],
"volentiers": ["volontiers", "volenters", "volantiers", "volentiers"],
"voler": ["voler", "volant", "volee", "volez", "vole", "volent", "voloit", "vola", "volerent", "volera", "volt",
          "volast"],
"voloir": ["voloir", "vouloir", "voloirs", "voel", "vuel", "vials", "viaus", "viax", "veaust", "vialt", "viaut",
           "volons", "volez", "voelent", "vuelent", "voloie", "voloies", "voloit", "voliens", "voleiez", "voliez",
           "voloient", "vos", "vox", "volsis", "volt", "vost", "vout", "vostrent", "voldrai", "voldras", "voldra",
           "voldrons", "voldrez", "voldroiz", "voldront", "volront", "voldroie", "vouroie", "voldroies", "voldroit",
           "voudriens", "voldriez", "voudriez", "voldroient", "voille", "vuelle", "voelle", "vuelle", "voilliez",
           "vuilliez", "volsisse", "vousisse", "volsist", "vossist", "vousist", "volsissiez", "volsissent"],
"vuidier": ["voider", "voidier", "vuidier", "voidié", "vuidiee", "vuidiez", "vuide", "voident", "vuident", "vuida"],
"voudre": ["voldre", "voudre", "vox"],
"vout": ["vult", "voult", "volt", "volz", "vout"],
"voutiz": ["voltiz", "voutiz", "voltis", "voûtis", "vostiz"],
"vuel": ["voil", "vueil", "voel", "vuel"],
"vuit": ["vuit", "void", "vuide", "vuiz"],
"waraingle": ["waraingle", "varaingle", "varengle"],
"yder1": ["yders", "ydiers"],
"yder2": ["yder", "yders", "ydiers"],
"yder3": ["yder", "ydiers"],
"ygerne": ["ygerne"],
"yonet": ["yonet", "ionez", "yonez", "yvonet", "yvonez"],
"ysoré": ["ysoré"],
"yvain1": ["yvain", "yvains"],
"yvain4": ["yvain", "yvains", "yvein", "yveins"],
"PUNK": [",", ".", r'"', "?", "!", "(", ")", "{", "}", ";"]
}