INDEX_LIST = {
    "Miscellaneous indices (works on CD)": {
        "AWNAMSCD.BIN": "Names of authors and works",
        "BIBINDCD.BIN": "Index to author/work entries in bibliographical form of Canon",
        "AUTHWKCD.BIN": "Comprehensive list of authors and works on CD",
        "DATINDCD.BIN": "Index to author/work entries in database form of Canon",
        "INDXWKCD.BIN": "Index of authors and works on CD",
    },
    "Miscellaneous indices (works in canon)": {
        "DATINDCN.BIN": "Index to author/work entries in database form of Canon",
        "AUTHWKCN.BIN": "Comprehensive list of authors and works in Canon",
        "BIBINDCN.BIN": "Index to author/work entries in bibliographical form of Canon",
        "AWNAMSCN.BIN": "Names of authors and works",
    },
    "Lists pertaining to all works in Canon (by TLG number)": {
        "LIST4DAT.BIN": "Chronological classifications of authors",
        "LIST3CLX.BIN": "Literary classifications of works (with x-refs)",
        "LIST3DAT.BIN": "Chronological classifications of authors",
        "LIST4EPI.BIN": "Classifications of authors by epithet or genre",
        "LIST4CLA.BIN": "Literary classifications of works",
        "LIST4CLX.BIN": "Literary classifications of works (with x-refs)",
        "LIST4GEO.BIN": "Geographical classifications of authors (provisional)",
        "LIST3FEM.BIN": "Female writers",
        "LIST3EPI.BIN": "Classifications of authors by epithet or genre",
        "LIST3GEO.BIN": "Geographical classifications of authors (provisional)",
        "LIST3CLA.BIN": "Literary classifications of works",
        "LIST4FEM.BIN": "Female writers",
    },
    "Lists pertaining to all works in Canon (chronological)": {
        "LIST1CLX.BIN": "Literary classifications of works (with x-refs)",
        "LIST1CLA.BIN": "Literary classifications of works",
        "LIST1FEM.BIN": "Female writers",
        "LIST2CLX.BIN": "Literary classifications of works (with x-refs)",
        "LIST1DAT.BIN": "Chronological classifications of authors",
        "LIST2DAT.BIN": "Chronological classifications of authors",
        "LIST1GEO.BIN": "Geographical classifications of authors (provisional)",
        "LIST2EPI.BIN": "Classifications of authors by epithet or genre",
        "LIST2GEO.BIN": "Geographical classifications of authors (provisional)",
        "LIST2CLA.BIN": "Literary classifications of works",
        "LIST1EPI.BIN": "Classifications of authors by epithet or genre",
        "LIST2FEM.BIN": "Female writers",
    },
}
